//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class AER_YLQX
    {
        public decimal JLXH { get; set; }
        public string JLBH { get; set; }
        public string SBBH { get; set; }
        public string THYJ { get; set; }
        public Nullable<decimal> JZXH { get; set; }
        public string JZHM { get; set; }
        public Nullable<decimal> ZTBZ { get; set; }
        public string JLGH { get; set; }
        public Nullable<System.DateTime> JLSJ { get; set; }
        public Nullable<decimal> SHBZ { get; set; }
        public string SHGH { get; set; }
        public Nullable<System.DateTime> SHSJ { get; set; }
        public Nullable<decimal> SBBZ { get; set; }
        public string SBGH { get; set; }
        public Nullable<System.DateTime> SBSJ { get; set; }
        public Nullable<decimal> SZKS { get; set; }
        public Nullable<decimal> ZFBZ { get; set; }
        public string ZFGH { get; set; }
        public Nullable<System.DateTime> ZFSJ { get; set; }
        public string BZXX { get; set; }
        public Nullable<System.DateTime> FSRQ { get; set; }
        public Nullable<decimal> RQLX { get; set; }
        public Nullable<decimal> FSSJ { get; set; }
        public Nullable<decimal> BRXB { get; set; }
        public Nullable<decimal> BRNL { get; set; }
        public Nullable<decimal> BRZB { get; set; }
        public Nullable<decimal> ZLLB { get; set; }
        public Nullable<System.DateTime> ZLSJ { get; set; }
        public Nullable<decimal> YLLB { get; set; }
        public string JBMC { get; set; }
        public string QTQK { get; set; }
        public Nullable<decimal> SJJB { get; set; }
        public Nullable<decimal> SJFWQK { get; set; }
        public string SJBGMC { get; set; }
        public string SJBGQK { get; set; }
        public string SJXGYS { get; set; }
        public Nullable<decimal> YCZYFX { get; set; }
        public Nullable<decimal> YCLCBX { get; set; }
        public string YCPM { get; set; }
        public string YCXH { get; set; }
        public Nullable<System.DateTime> YCCCRQ { get; set; }
        public string YCPH { get; set; }
        public Nullable<System.DateTime> YCSCRQ { get; set; }
        public string YCXDYXQ { get; set; }
        public string GKYJSH { get; set; }
        public Nullable<decimal> GKYQSH { get; set; }
        public Nullable<decimal> GKLCBX { get; set; }
        public string GKPM { get; set; }
        public string GKXH { get; set; }
        public Nullable<System.DateTime> GKCCRQ { get; set; }
        public string GKPH { get; set; }
        public Nullable<System.DateTime> GKSCRQ { get; set; }
        public string GKXDYXQ { get; set; }
        public string GNLCBX { get; set; }
        public Nullable<decimal> GNBFZ { get; set; }
        public Nullable<decimal> GNTSQK { get; set; }
        public string GNPM { get; set; }
        public string GNXH { get; set; }
        public Nullable<System.DateTime> GNCCRQ { get; set; }
        public string GNPH { get; set; }
        public Nullable<System.DateTime> GNSCRQ { get; set; }
        public string GNXDYXQ { get; set; }
        public Nullable<decimal> JBTCBW { get; set; }
        public Nullable<decimal> JBYJSH { get; set; }
        public Nullable<decimal> JBYQSH { get; set; }
        public Nullable<decimal> JBLCBX { get; set; }
        public string JBPM { get; set; }
        public string JBXH { get; set; }
        public Nullable<System.DateTime> JBCCRQ { get; set; }
        public string JBPH { get; set; }
        public Nullable<System.DateTime> JBSCRQ { get; set; }
        public string JBXDYXQ { get; set; }
        public Nullable<decimal> JMYJSH { get; set; }
        public string JMPM { get; set; }
        public string JMXH { get; set; }
        public Nullable<System.DateTime> JMCCRQ { get; set; }
        public string JMPH { get; set; }
        public Nullable<System.DateTime> JMSCRQ { get; set; }
        public string JMXDYXQ { get; set; }
        public Nullable<decimal> XGPZ { get; set; }
        public string XGYJSH { get; set; }
        public string XGYQSH { get; set; }
        public string XGPM { get; set; }
        public string XGXH { get; set; }
        public Nullable<System.DateTime> XGCCRQ { get; set; }
        public string XGPH { get; set; }
        public Nullable<System.DateTime> XGSCRQ { get; set; }
        public string XGXDYXQ { get; set; }
        public Nullable<decimal> RGPZ { get; set; }
        public string RGYJSH { get; set; }
        public string RGYQSH { get; set; }
        public Nullable<decimal> RGXGZZ { get; set; }
        public string RGPM { get; set; }
        public string RGXH { get; set; }
        public Nullable<System.DateTime> RGCCRQ { get; set; }
        public string RGPH { get; set; }
        public Nullable<System.DateTime> RGSCRQ { get; set; }
        public string RGXDYXQ { get; set; }
        public Nullable<decimal> YXYJSH { get; set; }
        public string YXPM { get; set; }
        public string YXXH { get; set; }
        public Nullable<System.DateTime> YXCCRQ { get; set; }
        public string YXPH { get; set; }
        public Nullable<System.DateTime> YXSCRQ { get; set; }
        public string YXXDYXQ { get; set; }
        public Nullable<decimal> QTYLQX { get; set; }
        public Nullable<decimal> QTDG { get; set; }
        public Nullable<decimal> QTYJSH { get; set; }
        public string QTYQSH { get; set; }
        public string QTXGZZ { get; set; }
        public string QTPM { get; set; }
        public string QTXH { get; set; }
        public Nullable<System.DateTime> QTCCRQ { get; set; }
        public string QTPH { get; set; }
        public Nullable<System.DateTime> QTSCRQ { get; set; }
        public string QTXDYXQ { get; set; }
        public Nullable<decimal> HZBRZT { get; set; }
        public Nullable<decimal> HZBRSH { get; set; }
        public Nullable<decimal> HZSHCD { get; set; }
        public Nullable<decimal> XCZLKS { get; set; }
        public Nullable<decimal> XCFSDD { get; set; }
        public Nullable<decimal> DSRZB1 { get; set; }
        public Nullable<decimal> DSRZC1 { get; set; }
        public Nullable<decimal> DSRNZ1 { get; set; }
        public Nullable<decimal> DSRKS1 { get; set; }
        public Nullable<decimal> DSRSF1 { get; set; }
        public Nullable<decimal> DSRZB2 { get; set; }
        public Nullable<decimal> DSRZC2 { get; set; }
        public Nullable<decimal> DSRNZ2 { get; set; }
        public Nullable<decimal> DSRKS2 { get; set; }
        public Nullable<decimal> DSRSF2 { get; set; }
        public Nullable<decimal> DSRZB3 { get; set; }
        public Nullable<decimal> DSRZC3 { get; set; }
        public Nullable<decimal> DSRNZ3 { get; set; }
        public Nullable<decimal> DSRKS3 { get; set; }
        public Nullable<decimal> DSRSF3 { get; set; }
        public Nullable<decimal> QTYLJF { get; set; }
        public string QTJFMX { get; set; }
        public Nullable<decimal> BGZLB { get; set; }
        public Nullable<decimal> BGZZB { get; set; }
        public string BGZXM { get; set; }
        public string BGZDH { get; set; }
        public string EMAIL { get; set; }
        public string BGZZC { get; set; }
        public string BGZQT { get; set; }
        public decimal JGID { get; set; }
    }
}
