//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ba_brzd
    {
        public decimal zyh { get; set; }
        public Nullable<decimal> zymc { get; set; }
        public Nullable<decimal> zyrc { get; set; }
        public Nullable<decimal> zybz { get; set; }
        public Nullable<decimal> zyzf { get; set; }
        public Nullable<decimal> zyfy { get; set; }
        public Nullable<decimal> mcfh { get; set; }
        public Nullable<decimal> rcfh { get; set; }
        public Nullable<decimal> cydz { get; set; }
        public Nullable<decimal> qhfh { get; set; }
        public Nullable<decimal> blfh { get; set; }
        public Nullable<decimal> fsfh { get; set; }
        public Nullable<decimal> ctfh { get; set; }
        public Nullable<decimal> sjfh { get; set; }
        public Nullable<decimal> zllb { get; set; }
        public Nullable<decimal> qjff { get; set; }
        public Nullable<decimal> cyfs { get; set; }
        public Nullable<decimal> sxqk { get; set; }
        public Nullable<decimal> syqk { get; set; }
        public Nullable<decimal> sjba { get; set; }
        public Nullable<decimal> kyba { get; set; }
        public Nullable<decimal> bazl { get; set; }
        public Nullable<decimal> srqz { get; set; }
        public Nullable<decimal> wrqz { get; set; }
        public string hxbs { get; set; }
        public string xxbs { get; set; }
        public string sxjs { get; set; }
        public string sqxs { get; set; }
        public string qtxx { get; set; }
        public Nullable<decimal> rb { get; set; }
        public string zkys { get; set; }
        public string zkhs { get; set; }
        public string xxhm { get; set; }
        public string cthm { get; set; }
        public string mrih { get; set; }
        public string dsah { get; set; }
        public Nullable<decimal> dybz { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<System.DateTime> ZKRQ { get; set; }
    
        public virtual ba_brsy ba_brsy { get; set; }
    }
}
