//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ba_brsy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ba_brsy()
        {
            this.ba_brqt = new HashSet<ba_brqt>();
            this.ba_brss = new HashSet<ba_brss>();
            this.ba_brye = new HashSet<ba_brye>();
        }
    
        public decimal zyh { get; set; }
        public Nullable<decimal> ryqk { get; set; }
        public Nullable<decimal> wyzz { get; set; }
        public Nullable<decimal> rytj { get; set; }
        public Nullable<decimal> ryks { get; set; }
        public Nullable<decimal> rybq { get; set; }
        public string rych { get; set; }
        public Nullable<System.DateTime> ryrq { get; set; }
        public Nullable<decimal> zkqk { get; set; }
        public Nullable<decimal> zkks { get; set; }
        public Nullable<decimal> zkbq { get; set; }
        public string zkch { get; set; }
        public Nullable<System.DateTime> zkrq { get; set; }
        public Nullable<decimal> cyks { get; set; }
        public Nullable<decimal> cybq { get; set; }
        public string cych { get; set; }
        public Nullable<System.DateTime> cyrq { get; set; }
        public Nullable<decimal> zyts { get; set; }
        public Nullable<decimal> sqts { get; set; }
        public Nullable<System.DateTime> swrq { get; set; }
        public Nullable<decimal> swyy { get; set; }
        public Nullable<decimal> swzd { get; set; }
        public string swbh { get; set; }
        public Nullable<decimal> mzzd { get; set; }
        public Nullable<decimal> zymz { get; set; }
        public Nullable<decimal> ryzd { get; set; }
        public Nullable<decimal> zyry { get; set; }
        public Nullable<System.DateTime> qzrq { get; set; }
        public Nullable<decimal> qzts { get; set; }
        public Nullable<decimal> zyzb { get; set; }
        public Nullable<decimal> zbzg { get; set; }
        public string zbbm { get; set; }
        public Nullable<decimal> zyzz { get; set; }
        public Nullable<decimal> zzzg { get; set; }
        public string zzbm { get; set; }
        public Nullable<decimal> zyzd { get; set; }
        public Nullable<decimal> zgqk { get; set; }
        public string jbbm { get; set; }
        public Nullable<decimal> ssbf { get; set; }
        public Nullable<decimal> bfjg { get; set; }
        public string bfbm { get; set; }
        public Nullable<decimal> qtbf { get; set; }
        public Nullable<decimal> qtjg { get; set; }
        public string qtbm { get; set; }
        public Nullable<decimal> yngr { get; set; }
        public Nullable<decimal> grjg { get; set; }
        public string grbm { get; set; }
        public Nullable<decimal> sszd { get; set; }
        public string ssbm { get; set; }
        public Nullable<decimal> exzl { get; set; }
        public string zlbm { get; set; }
        public Nullable<decimal> sqzd { get; set; }
        public Nullable<decimal> shzd { get; set; }
        public Nullable<decimal> blzd { get; set; }
        public string blbh { get; set; }
        public string gmyw { get; set; }
        public Nullable<decimal> zzzy { get; set; }
        public Nullable<decimal> xxdm { get; set; }
        public Nullable<decimal> qjcs { get; set; }
        public Nullable<decimal> cgcs { get; set; }
        public Nullable<decimal> grcs { get; set; }
        public Nullable<decimal> szqk { get; set; }
        public Nullable<decimal> qzqx { get; set; }
        public Nullable<decimal> sjqk { get; set; }
        public Nullable<decimal> bqwz { get; set; }
        public Nullable<decimal> bqjz { get; set; }
        public Nullable<decimal> bqyn { get; set; }
        public string sxys { get; set; }
        public string mzys { get; set; }
        public string zyys { get; set; }
        public string zzys { get; set; }
        public string zrys { get; set; }
        public string glys { get; set; }
        public string bmys { get; set; }
        public string cfwz { get; set; }
        public Nullable<decimal> fmqk { get; set; }
        public Nullable<decimal> plqk { get; set; }
        public Nullable<decimal> sspb { get; set; }
        public Nullable<decimal> gdpb { get; set; }
        public Nullable<decimal> zdpb { get; set; }
        public Nullable<decimal> yepb { get; set; }
        public Nullable<decimal> sjzd { get; set; }
        public string sjph { get; set; }
        public Nullable<int> hbsag { get; set; }
        public Nullable<int> hcvab { get; set; }
        public Nullable<int> hivab { get; set; }
        public string kszr { get; set; }
        public string jxys { get; set; }
        public string xsys { get; set; }
        public Nullable<decimal> qxlx { get; set; }
        public Nullable<decimal> zzks { get; set; }
        public string SSZDMC { get; set; }
        public string XSENL { get; set; }
        public string ZRHS { get; set; }
        public string BLZDBM { get; set; }
        public string ZLLB { get; set; }
        public string BATM { get; set; }
        public string ZRYMD { get; set; }
        public string MZZDMC { get; set; }
        public string GDR { get; set; }
        public string BLZDMC { get; set; }
        public string MZZDBM { get; set; }
        public string ZKKB { get; set; }
        public string NJSYLJG { get; set; }
        public string ZYZDMC { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<System.DateTime> DJRQ { get; set; }
        public Nullable<System.DateTime> GDRQ { get; set; }
        public Nullable<System.DateTime> SJSJ { get; set; }
        public Nullable<decimal> LCLJ { get; set; }
        public Nullable<decimal> LNSSQ_H { get; set; }
        public Nullable<decimal> LYFS { get; set; }
        public Nullable<decimal> XSECSTZ { get; set; }
        public Nullable<decimal> SYZYZJ { get; set; }
        public Nullable<decimal> DJZT { get; set; }
        public Nullable<decimal> LNSSQ_M { get; set; }
        public Nullable<decimal> SYZLJS { get; set; }
        public Nullable<decimal> YEQK { get; set; }
        public Nullable<decimal> LNSSH_D { get; set; }
        public Nullable<decimal> BZSH { get; set; }
        public Nullable<decimal> FCQK { get; set; }
        public Nullable<decimal> SJBZ { get; set; }
        public Nullable<decimal> JYBZ { get; set; }
        public Nullable<decimal> YWGM { get; set; }
        public Nullable<decimal> ZZRYBQ { get; set; }
        public Nullable<decimal> ZRYJH { get; set; }
        public Nullable<decimal> XSERYTZ { get; set; }
        public Nullable<decimal> LNSSH_H { get; set; }
        public Nullable<decimal> SYZLSB { get; set; }
        public Nullable<decimal> LNSSQ_D { get; set; }
        public Nullable<decimal> LNSSH_M { get; set; }
    
        public virtual ba_brda ba_brda { get; set; }
        public virtual ba_brfy ba_brfy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ba_brqt> ba_brqt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ba_brss> ba_brss { get; set; }
        public virtual ba_brsw ba_brsw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ba_brye> ba_brye { get; set; }
        public virtual ba_brzd ba_brzd { get; set; }
    }
}
