//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ba_fkzl
    {
        public decimal tjyf { get; set; }
        public decimal ksdm { get; set; }
        public Nullable<decimal> cybr { get; set; }
        public Nullable<decimal> srqz { get; set; }
        public Nullable<decimal> wrqz { get; set; }
        public Nullable<decimal> mcfh { get; set; }
        public Nullable<decimal> mcbf { get; set; }
        public Nullable<decimal> mcyz { get; set; }
        public Nullable<decimal> rcfh { get; set; }
        public Nullable<decimal> rcbf { get; set; }
        public Nullable<decimal> rcyz { get; set; }
        public Nullable<decimal> cydz { get; set; }
        public Nullable<decimal> qhfh { get; set; }
        public Nullable<decimal> qhbf { get; set; }
        public Nullable<decimal> qhyz { get; set; }
        public Nullable<decimal> blfh { get; set; }
        public Nullable<decimal> blbf { get; set; }
        public Nullable<decimal> blyz { get; set; }
        public Nullable<decimal> fsfh { get; set; }
        public Nullable<decimal> fsbf { get; set; }
        public Nullable<decimal> fsyz { get; set; }
        public Nullable<decimal> ctfh { get; set; }
        public Nullable<decimal> ctbf { get; set; }
        public Nullable<decimal> ctyz { get; set; }
        public Nullable<decimal> sjfh { get; set; }
        public Nullable<decimal> sjbf { get; set; }
        public Nullable<decimal> sjyz { get; set; }
        public Nullable<decimal> wj1 { get; set; }
        public Nullable<decimal> wj2 { get; set; }
        public Nullable<decimal> wj3 { get; set; }
        public Nullable<decimal> kn1 { get; set; }
        public Nullable<decimal> kn2 { get; set; }
        public Nullable<decimal> kn3 { get; set; }
        public Nullable<decimal> sb1 { get; set; }
        public Nullable<decimal> sb2 { get; set; }
        public Nullable<decimal> sb3 { get; set; }
        public Nullable<decimal> bacc { get; set; }
        public Nullable<decimal> jjba { get; set; }
        public Nullable<decimal> yjba { get; set; }
        public Nullable<decimal> bjba { get; set; }
        public Nullable<decimal> qzts { get; set; }
        public Nullable<decimal> sqts { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
