//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class bk_jsb
    {
        public decimal kpbh { get; set; }
        public string sfzh { get; set; }
        public string jtdh { get; set; }
        public string lxrxm { get; set; }
        public string lxrdh { get; set; }
        public string hldz { get; set; }
        public string xzdz { get; set; }
        public string hzzy { get; set; }
        public string szzt { get; set; }
        public Nullable<System.DateTime> ccfbsj { get; set; }
        public Nullable<decimal> bz_jsflz { get; set; }
        public Nullable<decimal> bz_flqgxza { get; set; }
        public Nullable<decimal> bz_cjxdwxxza { get; set; }
        public Nullable<decimal> bz_ssza { get; set; }
        public Nullable<decimal> bz_dxszjsza { get; set; }
        public Nullable<decimal> bz_jsfyczbfjsza { get; set; }
        public Nullable<decimal> bz_qt { get; set; }
        public string qt { get; set; }
        public string tbys { get; set; }
        public string lxdh { get; set; }
        public string bgdwjks { get; set; }
        public Nullable<System.DateTime> tkrq { get; set; }
        public string jlxh { get; set; }
        public Nullable<decimal> brid { get; set; }
        public Nullable<decimal> jzxh { get; set; }
        public Nullable<decimal> bkzt { get; set; }
        public Nullable<System.DateTime> bksj { get; set; }
        public string lxrgx { get; set; }
        public string lxrsfzh { get; set; }
        public string shzt { get; set; }
        public Nullable<System.DateTime> shsj { get; set; }
        public Nullable<System.DateTime> tbrq { get; set; }
        public string wzx { get; set; }
        public string szzt2 { get; set; }
        public string szzt3 { get; set; }
        public string szzt4 { get; set; }
        public string szzt5 { get; set; }
        public string szzt_qt { get; set; }
        public string qzyy { get; set; }
        public Nullable<System.DateTime> qzrq { get; set; }
        public string jbmc { get; set; }
        public string icd10 { get; set; }
        public string bcryyy { get; set; }
        public string djpg { get; set; }
        public string lxrgzdw { get; set; }
        public string lxrhj { get; set; }
        public string hzhj { get; set; }
        public Nullable<decimal> zqty1 { get; set; }
        public Nullable<decimal> zqty2 { get; set; }
        public Nullable<decimal> zqty3 { get; set; }
        public Nullable<decimal> zqtyh { get; set; }
        public Nullable<decimal> zqtyj { get; set; }
        public Nullable<decimal> zqtyq { get; set; }
        public Nullable<decimal> zqty { get; set; }
        public Nullable<decimal> bdwd { get; set; }
        public string dcbz { get; set; }
    }
}
