//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class bl_zk_tjxm
    {
        public string xmbh { get; set; }
        public string tjbh { get; set; }
        public string xmmc { get; set; }
        public string xmzd { get; set; }
        public string sjdx { get; set; }
        public string zdlx { get; set; }
        public string ysf { get; set; }
        public string xmqz { get; set; }
        public string ljf { get; set; }
    }
}
