//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class bl_zk_sjxm
    {
        public string xmbh { get; set; }
        public string xmzh { get; set; }
        public string sjbh { get; set; }
        public Nullable<decimal> xmlx { get; set; }
        public string zybh { get; set; }
        public string zymc { get; set; }
        public Nullable<decimal> zylx { get; set; }
        public Nullable<decimal> mxlb { get; set; }
        public string yybm { get; set; }
        public string ksck { get; set; }
        public Nullable<decimal> kssj { get; set; }
        public Nullable<decimal> yxqx { get; set; }
        public string qxdw { get; set; }
        public Nullable<decimal> zycs { get; set; }
        public string tzck { get; set; }
        public Nullable<decimal> tzsj { get; set; }
        public Nullable<decimal> jslx { get; set; }
        public Nullable<decimal> pllx { get; set; }
        public string jgpl { get; set; }
        public Nullable<decimal> zyjb { get; set; }
        public string zytj { get; set; }
        public string pydm { get; set; }
        public string qxbh { get; set; }
        public Nullable<decimal> sjzt { get; set; }
        public Nullable<decimal> tqbz { get; set; }
        public Nullable<decimal> cydq { get; set; }
    }
}
