//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class bl_zk_pf03
    {
        public string jlid { get; set; }
        public string brbh { get; set; }
        public string zrks { get; set; }
        public string zrys { get; set; }
        public string bllx { get; set; }
        public string qxbm { get; set; }
        public string qxmc { get; set; }
        public Nullable<decimal> dxfj { get; set; }
        public Nullable<decimal> fjjb { get; set; }
        public Nullable<decimal> qxxs { get; set; }
        public Nullable<decimal> dxfz { get; set; }
        public Nullable<decimal> kffz { get; set; }
        public Nullable<System.DateTime> kfsj { get; set; }
        public Nullable<decimal> pffs { get; set; }
    }
}
