//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class BQ_PSCL
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public decimal YZXH { get; set; }
        public Nullable<decimal> YSYZBH { get; set; }
        public Nullable<decimal> ZYH { get; set; }
        public Nullable<decimal> PSJG { get; set; }
        public Nullable<System.DateTime> PSSJ { get; set; }
        public string PSGH { get; set; }
        public Nullable<decimal> YYPS { get; set; }
    }
}
