//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class BQ_SMTZ
    {
        public decimal CJH { get; set; }
        public decimal CJZH { get; set; }
        public Nullable<decimal> XMH { get; set; }
        public decimal JHBZ { get; set; }
        public System.DateTime CJSJ { get; set; }
        public decimal ZYH { get; set; }
        public Nullable<decimal> BRKS { get; set; }
        public Nullable<decimal> BRBQ { get; set; }
        public string BRCH { get; set; }
        public string TZNR { get; set; }
        public string XMXB { get; set; }
        public decimal FCBZ { get; set; }
        public Nullable<decimal> FCGL { get; set; }
        public Nullable<decimal> TWDXS { get; set; }
        public System.DateTime JLSJ { get; set; }
        public string JLGH { get; set; }
        public decimal ZFBZ { get; set; }
        public string BZXX { get; set; }
        public decimal YCBZ { get; set; }
        public Nullable<decimal> JLBH { get; set; }
        public decimal JGID { get; set; }
    }
}
