//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class bq_ztmx
    {
        public decimal ztxh { get; set; }
        public decimal yzzh { get; set; }
        public string xmmc { get; set; }
        public decimal xmxh { get; set; }
        public decimal xmlx { get; set; }
        public decimal xmsl { get; set; }
        public decimal ypyf { get; set; }
        public string sypc { get; set; }
        public Nullable<decimal> ypjl { get; set; }
    
        public virtual bq_yzzt bq_yzzt { get; set; }
    }
}
