//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_BZZB
    {
        public decimal ZBBH { get; set; }
        public string ZBDM { get; set; }
        public string ZBMC { get; set; }
        public string PYDM { get; set; }
        public string WBDM { get; set; }
        public string ZBSM { get; set; }
        public string SLLM { get; set; }
        public decimal BZBH { get; set; }
        public Nullable<decimal> BGBH { get; set; }
        public Nullable<decimal> PLSX { get; set; }
    }
}
