//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_BZZK3_CABG
    {
        public decimal JLXH { get; set; }
        public string PAT_ZDBM_1_I { get; set; }
        public string PAT_ZDMC_1_I { get; set; }
        public string PAT_ZDBM_1_II { get; set; }
        public string PAT_ZDMC_1_II { get; set; }
        public string PAT_ZDBM_2_I { get; set; }
        public string PAT_ZDMC_2_I { get; set; }
        public string PAT_ZDBM_2_II { get; set; }
        public string PAT_ZDMC_2_II { get; set; }
        public string PAT_SSBM { get; set; }
        public string PAT_SSMC { get; set; }
        public string PAT_BAHM { get; set; }
        public string PAT_ZYHM { get; set; }
        public Nullable<System.DateTime> PAT_CSRQ { get; set; }
        public string PAT_ZFFS { get; set; }
        public string PAT_RYTJ { get; set; }
        public string PAT_JTGJ { get; set; }
        public Nullable<System.DateTime> PAT_FBSJ { get; set; }
        public Nullable<System.DateTime> PAT_DDSJ { get; set; }
        public Nullable<System.DateTime> PAT_RYRQ { get; set; }
        public Nullable<System.DateTime> PAT_ZRSJ { get; set; }
        public Nullable<System.DateTime> PAT_SSKS { get; set; }
        public Nullable<System.DateTime> PAT_SSJS { get; set; }
        public Nullable<System.DateTime> PAT_CYRQ { get; set; }
        public Nullable<decimal> PAT_ZYFY { get; set; }
        public Nullable<decimal> PAT_YF { get; set; }
        public Nullable<decimal> PAT_ZYTS { get; set; }
        public string PAT_ZLJG { get; set; }
        public string PAT_CYQX { get; set; }
        public string CABG_1_1 { get; set; }
        public Nullable<System.DateTime> CABG_1_1_1 { get; set; }
        public string CABG_1_1_2 { get; set; }
        public string CABG_1_1_3 { get; set; }
        public string CABG_1_1_4 { get; set; }
        public string CABG_1_1_5 { get; set; }
        public string CABG_1_1_6 { get; set; }
        public string CABG_1_1_7 { get; set; }
        public string CABG_1_1_8 { get; set; }
        public string CABG_1_1_9 { get; set; }
        public string CABG_1_1_10 { get; set; }
        public string CABG_1_1_11 { get; set; }
        public string CABG_1_1_12 { get; set; }
        public string CABG_1_1_13 { get; set; }
        public string CABG_1_1_14 { get; set; }
        public string CABG_1_1_15 { get; set; }
        public string CABG_1_1_16 { get; set; }
        public string CABG_1_1_17 { get; set; }
        public string CABG_1_1_18 { get; set; }
        public string CABG_1_1_18_0 { get; set; }
        public string CABG_2_1 { get; set; }
        public Nullable<decimal> CABG_2_1_1 { get; set; }
        public Nullable<decimal> CABG_2_1_2 { get; set; }
        public string CABG_2_1_3 { get; set; }
        public Nullable<decimal> CABG_2_1_4 { get; set; }
        public string CABG_2_2 { get; set; }
        public string CABG_2_2_1 { get; set; }
        public string CABG_2_2_2 { get; set; }
        public string CABG_2_2_2_0 { get; set; }
        public string CABG_2_3 { get; set; }
        public string CABG_2_4 { get; set; }
        public string CABG_2_5 { get; set; }
        public Nullable<System.DateTime> CABG_3_1 { get; set; }
        public Nullable<System.DateTime> CABG_3_2 { get; set; }
        public string CABG_4_0 { get; set; }
        public string CABG_4_1 { get; set; }
        public Nullable<System.DateTime> CABG_4_2 { get; set; }
        public string CABG_4_3 { get; set; }
        public Nullable<decimal> CABG_4_4 { get; set; }
        public Nullable<System.DateTime> CABG_4_5 { get; set; }
        public Nullable<decimal> CABG_5_1 { get; set; }
        public Nullable<decimal> CABG_5_2 { get; set; }
        public string CABG_5_3 { get; set; }
        public string CABG_5_4 { get; set; }
        public string CABG_5_5 { get; set; }
        public string CABG_5_6 { get; set; }
        public string CABG_5_6_1 { get; set; }
        public string CABG_6 { get; set; }
        public string CABG_6_1 { get; set; }
        public string CABG_6_1_0 { get; set; }
        public string CABG_6_2 { get; set; }
        public string CABG_7_1 { get; set; }
        public string CABG_7_1_1 { get; set; }
        public string CABG_7_1_1_0 { get; set; }
        public string CABG_7_2 { get; set; }
        public string CABG_7_2_1 { get; set; }
        public string CABG_7_2_1_0 { get; set; }
        public string CABG_8_1 { get; set; }
        public string CABG_10_1 { get; set; }
        public string CABG_10_2 { get; set; }
        public string CABG_10_3 { get; set; }
        public string CABG_10_4 { get; set; }
        public string CABG_10_5 { get; set; }
        public string CABG_10_6 { get; set; }
        public string CABG_10_7 { get; set; }
        public string CABG_10_8 { get; set; }
    }
}
