//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_BZZK
    {
        public decimal JLXH { get; set; }
        public decimal BZBH { get; set; }
        public string JZHM { get; set; }
        public decimal JZXH { get; set; }
        public decimal ZKLX { get; set; }
        public System.DateTime SBSJ { get; set; }
        public string SBGH { get; set; }
        public decimal SBKS { get; set; }
        public decimal TJBZ { get; set; }
        public Nullable<System.DateTime> TJSJ { get; set; }
        public string TJGH { get; set; }
        public decimal QRBZ { get; set; }
        public Nullable<System.DateTime> QRSJ { get; set; }
        public string QRGH { get; set; }
        public decimal ZFBZ { get; set; }
        public decimal YSGL { get; set; }
        public decimal SJBS { get; set; }
        public Nullable<decimal> RYZD { get; set; }
        public Nullable<decimal> ZXZT { get; set; }
        public decimal JGID { get; set; }
    }
}
