//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CU_PTMS_PXCF
    {
        public decimal JLXH { get; set; }
        public Nullable<decimal> GLXH { get; set; }
        public Nullable<decimal> JZLX { get; set; }
        public Nullable<decimal> JZXH { get; set; }
        public string JZHM { get; set; }
        public Nullable<decimal> BXSF { get; set; }
        public string LZSJ { get; set; }
        public Nullable<decimal> ZLLC { get; set; }
        public Nullable<System.DateTime> JLSJ { get; set; }
        public string JLRY { get; set; }
        public decimal JGID { get; set; }
    }
}
