//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CU_PTMS_LLSQ
    {
        public decimal SQDH { get; set; }
        public Nullable<decimal> SQPB { get; set; }
        public string SQNR { get; set; }
        public decimal JZLX { get; set; }
        public decimal JZXH { get; set; }
        public string JZHM { get; set; }
        public string FPHM { get; set; }
        public string BRXM { get; set; }
        public Nullable<decimal> BRXB { get; set; }
        public Nullable<System.DateTime> CSNY { get; set; }
        public string BRNL { get; set; }
        public string ZYBS { get; set; }
        public string TJPD { get; set; }
        public string ZDMC { get; set; }
        public Nullable<decimal> SQKS { get; set; }
        public string SQYS { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public Nullable<decimal> DJZT { get; set; }
        public string JSRY { get; set; }
        public Nullable<System.DateTime> JSRQ { get; set; }
        public Nullable<decimal> ZFPB { get; set; }
        public string ZFYS { get; set; }
        public Nullable<System.DateTime> ZFRQ { get; set; }
        public string BZXX { get; set; }
        public Nullable<decimal> YJXH { get; set; }
        public Nullable<decimal> YYPB { get; set; }
        public decimal JGID { get; set; }
        public Nullable<decimal> ZXKS { get; set; }
    }
}
