//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class cu_register
    {
        public string jgdm { get; set; }
        public string tjlsh { get; set; }
        public string kh { get; set; }
        public Nullable<decimal> klx { get; set; }
        public string bjh { get; set; }
        public string tjzd { get; set; }
        public string tjrq { get; set; }
        public decimal scbz { get; set; }
    }
}
