//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class dz_dzjl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dz_dzjl()
        {
            this.dz_cdjl = new HashSet<dz_cdjl>();
            this.dz_fwjl = new HashSet<dz_fwjl>();
            this.dz_gqjl = new HashSet<dz_gqjl>();
            this.dz_zkjl = new HashSet<dz_zkjl>();
        }
    
        public decimal dzid { get; set; }
        public decimal dzth { get; set; }
        public decimal dzzt { get; set; }
        public decimal brid { get; set; }
        public string brxm { get; set; }
        public Nullable<decimal> ghsb { get; set; }
        public Nullable<System.DateTime> ghsj { get; set; }
        public string ksdm { get; set; }
        public string ysdm { get; set; }
        public string jzhm { get; set; }
        public Nullable<decimal> jzxh { get; set; }
        public decimal dzxh { get; set; }
        public decimal pdxh { get; set; }
        public System.DateTime dzsj { get; set; }
        public string dzsm { get; set; }
        public Nullable<decimal> brtw { get; set; }
        public Nullable<decimal> xy_1 { get; set; }
        public Nullable<decimal> xy_2 { get; set; }
        public Nullable<decimal> brmb { get; set; }
        public Nullable<System.DateTime> hzsj { get; set; }
        public Nullable<System.DateTime> kssj { get; set; }
        public Nullable<System.DateTime> jssj { get; set; }
        public Nullable<System.DateTime> zfsj { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dz_cdjl> dz_cdjl { get; set; }
        public virtual dz_ztxx dz_ztxx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dz_fwjl> dz_fwjl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dz_gqjl> dz_gqjl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dz_zkjl> dz_zkjl { get; set; }
    }
}
