//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EA_SSFJ_ZZSQ
    {
        public decimal SQDH { get; set; }
        public decimal SQKS { get; set; }
        public string SQGH { get; set; }
        public System.DateTime SQRQ { get; set; }
        public Nullable<System.DateTime> JYRQ { get; set; }
        public Nullable<decimal> YGZC { get; set; }
        public Nullable<System.DateTime> ZCRQ { get; set; }
        public Nullable<decimal> YGXW { get; set; }
        public Nullable<System.DateTime> XWRQ { get; set; }
        public Nullable<decimal> SQDJ1 { get; set; }
        public Nullable<decimal> SQDJ2 { get; set; }
        public Nullable<decimal> SQDJ3 { get; set; }
        public Nullable<decimal> SQDJ4 { get; set; }
        public string TJRGH { get; set; }
        public Nullable<decimal> TJRZC { get; set; }
        public string TJRGH2 { get; set; }
        public Nullable<decimal> TJRZC2 { get; set; }
        public string KSSPYJ { get; set; }
        public string KSSPGH { get; set; }
        public Nullable<System.DateTime> KSSPRQ { get; set; }
        public string YWBSPYJ { get; set; }
        public string YWBSPGH { get; set; }
        public Nullable<System.DateTime> YWBSPRQ { get; set; }
        public string WYHSPYJ { get; set; }
        public string WYHSPGH { get; set; }
        public Nullable<System.DateTime> WYHSPRQ { get; set; }
        public string YZSPYJ { get; set; }
        public string YZSPGH { get; set; }
        public Nullable<System.DateTime> YZSPRQ { get; set; }
        public string BZXX { get; set; }
        public decimal DJZT { get; set; }
        public decimal JGID { get; set; }
    }
}
