//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EA_SWBL
    {
        public decimal JLXH { get; set; }
        public string JZHM { get; set; }
        public string BRBH { get; set; }
        public string BRXM { get; set; }
        public string BRCH { get; set; }
        public decimal BRKS { get; set; }
        public decimal BRBQ { get; set; }
        public Nullable<decimal> ZLXZ { get; set; }
        public string ZYYS { get; set; }
        public string ZRYS { get; set; }
        public string ZZYS { get; set; }
        public Nullable<decimal> HLJB { get; set; }
        public Nullable<decimal> BRQK { get; set; }
        public decimal BLBH { get; set; }
        public decimal BLLX { get; set; }
        public System.DateTime SWSJ { get; set; }
        public string ZCRY { get; set; }
        public System.DateTime TLRQ { get; set; }
        public string TLDD { get; set; }
        public string CJRY { get; set; }
        public string BQSM { get; set; }
        public string TLNR { get; set; }
        public string TLXJ { get; set; }
        public decimal DJZT { get; set; }
        public decimal ZFBZ { get; set; }
        public string BZXX { get; set; }
        public string WCYS { get; set; }
        public Nullable<System.DateTime> WCSJ { get; set; }
        public string JLGH { get; set; }
        public string ZCRSH { get; set; }
        public Nullable<System.DateTime> ZCRSHSJ { get; set; }
        public string CZGH { get; set; }
        public System.DateTime CZSJ { get; set; }
        public decimal JGID { get; set; }
    }
}
