//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_JLXG
    {
        public decimal RZBH { get; set; }
        public decimal JZXH { get; set; }
        public decimal FZXH { get; set; }
        public decimal MBBH { get; set; }
        public decimal JLBH { get; set; }
        public decimal MXBH { get; set; }
        public decimal XMBH { get; set; }
        public string XMMC { get; set; }
        public string GQXMQZ { get; set; }
        public string GHXMQZ { get; set; }
        public string XGSM { get; set; }
        public string XGGH { get; set; }
        public System.DateTime XGSJ { get; set; }
        public decimal JGID { get; set; }
    }
}
