//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_JL01
    {
        public decimal JLBH { get; set; }
        public decimal JZXH { get; set; }
        public decimal FZXH { get; set; }
        public decimal MBBH { get; set; }
        public string JLMC { get; set; }
        public decimal JLHS { get; set; }
        public System.DateTime JLSJ { get; set; }
        public decimal HYBZ { get; set; }
        public System.DateTime SXSJ { get; set; }
        public Nullable<decimal> JZLX { get; set; }
        public string SXHS { get; set; }
        public Nullable<decimal> WCQM { get; set; }
        public Nullable<System.DateTime> WCSJ { get; set; }
        public string WCHS { get; set; }
        public Nullable<decimal> SYBZ { get; set; }
        public Nullable<System.DateTime> SYSJ { get; set; }
        public string SYHS { get; set; }
        public Nullable<decimal> SYQM { get; set; }
        public decimal DYBZ { get; set; }
        public decimal JLZT { get; set; }
        public Nullable<decimal> ZJBH { get; set; }
        public string ZJMC { get; set; }
        public Nullable<decimal> ZJLX { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public decimal JGID { get; set; }
    }
}
