//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_CWSZ
    {
        public decimal JGID { get; set; }
        public string BRCH { get; set; }
        public string FJHM { get; set; }
        public Nullable<decimal> CWKS { get; set; }
        public decimal CWFY { get; set; }
        public Nullable<decimal> JZXH { get; set; }
        public decimal JZFQ { get; set; }
    }
}
