//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_YJPF
    {
        public decimal XXBS { get; set; }
        public decimal PFLB { get; set; }
        public string XXNR { get; set; }
        public string PYDM { get; set; }
        public Nullable<decimal> XXFZ { get; set; }
        public Nullable<decimal> XXFL { get; set; }
        public Nullable<decimal> XXLX { get; set; }
        public string XSSX { get; set; }
        public Nullable<decimal> ZFBZ { get; set; }
    }
}
