//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_HLMB
    {
        public decimal MBBH { get; set; }
        public string MBMC { get; set; }
        public string MBDX { get; set; }
        public string PYDM { get; set; }
        public string WBDM { get; set; }
        public Nullable<decimal> ZZDX { get; set; }
        public Nullable<decimal> ZZKD { get; set; }
        public Nullable<decimal> ZZGD { get; set; }
        public Nullable<decimal> ZZFX { get; set; }
        public Nullable<decimal> MYHS { get; set; }
        public Nullable<decimal> DLYM { get; set; }
        public decimal XTBZ { get; set; }
        public string BZXX { get; set; }
        public decimal PX { get; set; }
        public decimal JGID { get; set; }
    }
}
