//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_RYPG
    {
        public decimal JLBH { get; set; }
        public Nullable<decimal> JZXH { get; set; }
        public Nullable<decimal> FZXH { get; set; }
        public string CZGH { get; set; }
        public Nullable<System.DateTime> CZSJ { get; set; }
        public string SZ { get; set; }
        public string SZ_OTHER { get; set; }
        public string QD { get; set; }
        public string QD_OTHER { get; set; }
        public string HX { get; set; }
        public string HX_OTHER { get; set; }
        public string XH { get; set; }
        public string XH_OTHER { get; set; }
        public string CX { get; set; }
        public string CX_OTHER { get; set; }
        public string SJ { get; set; }
        public string SJ_OTHER { get; set; }
        public string SJYY { get; set; }
        public string SJTT { get; set; }
        public string ZTK { get; set; }
        public string ZTK_OTHER { get; set; }
        public string ZTKZJ { get; set; }
        public string YTK { get; set; }
        public string YTK_OTHER { get; set; }
        public string YTKZJ { get; set; }
        public string JB1 { get; set; }
        public string JB2 { get; set; }
        public string JB3 { get; set; }
        public string JB4 { get; set; }
        public string JB5 { get; set; }
        public string JB6 { get; set; }
        public string JB7 { get; set; }
        public string JB8 { get; set; }
        public string JB9 { get; set; }
        public string JB10 { get; set; }
        public string JB_OTHER { get; set; }
        public string XB1 { get; set; }
        public string XB2 { get; set; }
        public string XB3 { get; set; }
        public string XB4 { get; set; }
        public string XB5 { get; set; }
        public string XB6 { get; set; }
        public string XB7 { get; set; }
        public string XB8 { get; set; }
        public string XB9 { get; set; }
        public string XB10 { get; set; }
        public string XB_OTHER { get; set; }
        public string FB1 { get; set; }
        public string FB2 { get; set; }
        public string FB3 { get; set; }
        public string FB4 { get; set; }
        public string FB5 { get; set; }
        public string FB6 { get; set; }
        public string FB7 { get; set; }
        public string FB8 { get; set; }
        public string FB9 { get; set; }
        public string FB10 { get; set; }
        public string FB_OTHER { get; set; }
        public string PF1 { get; set; }
        public string PF2 { get; set; }
        public string PF3 { get; set; }
        public string PF4 { get; set; }
        public string PF5 { get; set; }
        public string PF6 { get; set; }
        public string PF7 { get; set; }
        public string PF8 { get; set; }
        public string PF9 { get; set; }
        public string PF10 { get; set; }
        public string PF_OTHER { get; set; }
        public string FSDD { get; set; }
        public string HSR1 { get; set; }
        public string HSR2 { get; set; }
        public string HSR3 { get; set; }
        public string HSR4 { get; set; }
        public string HSR5 { get; set; }
        public string HSR6 { get; set; }
        public string HSR7 { get; set; }
        public string HSR8 { get; set; }
        public string HSR9 { get; set; }
        public string HSR_OTHER { get; set; }
        public string HSFS { get; set; }
        public string LXR { get; set; }
        public string LXDH { get; set; }
        public decimal JGID { get; set; }
    }
}
