//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_JBMX
    {
        public decimal MXXH { get; set; }
        public decimal JBXH { get; set; }
        public decimal JZXH { get; set; }
        public decimal FZXH { get; set; }
        public string BRCH { get; set; }
        public string BRXM { get; set; }
        public string BRZD { get; set; }
        public decimal BRZT { get; set; }
        public string JBNR { get; set; }
        public Nullable<decimal> LSTD { get; set; }
        public Nullable<decimal> CSBZ { get; set; }
        public decimal JGID { get; set; }
    }
}
