//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_zkbz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emr_zkbz()
        {
            this.emr_bzgl = new HashSet<emr_bzgl>();
            this.emr_bzpc = new HashSet<emr_bzpc>();
        }
    
        public decimal bzbh { get; set; }
        public string bzmc { get; set; }
        public Nullable<decimal> sszk { get; set; }
        public string pydm { get; set; }
        public string wbdm { get; set; }
        public string qtdm { get; set; }
        public decimal cpbz { get; set; }
        public decimal zxbz { get; set; }
        public string bzbm { get; set; }
        public string bzms { get; set; }
        public Nullable<decimal> zdbz { get; set; }
        public Nullable<decimal> zkbz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_bzgl> emr_bzgl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_bzpc> emr_bzpc { get; set; }
        public virtual emr_zkfl emr_zkfl { get; set; }
    }
}
