//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_PFXMZD
    {
        public decimal XMXH { get; set; }
        public decimal XMFL { get; set; }
        public string XMMC { get; set; }
        public decimal XMLX { get; set; }
        public string QZSQL { get; set; }
        public string LJID { get; set; }
        public string BZXX { get; set; }
        public Nullable<decimal> ZFBZ { get; set; }
        public Nullable<decimal> DXBZ { get; set; }
        public Nullable<decimal> QZMS { get; set; }
        public Nullable<decimal> JFXS { get; set; }
        public string PYDM { get; set; }
        public Nullable<decimal> ZDZ { get; set; }
        public Nullable<decimal> ZXZ { get; set; }
        public Nullable<decimal> XSWS { get; set; }
        public Nullable<decimal> ZDSJZY { get; set; }
    }
}
