//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_BL_KSZK
    {
        public string KSDM { get; set; }
        public decimal JGID { get; set; }
        public string ZKYDM { get; set; }
        public string ZKYMC { get; set; }
        public string GLGJZ { get; set; }
        public Nullable<decimal> GLQY { get; set; }
        public Nullable<decimal> LTQY { get; set; }
        public Nullable<decimal> CCQY { get; set; }
    }
}
