//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_GA_SZCL02
    {
        public decimal JLXH { get; set; }
        public decimal SBXH { get; set; }
        public byte[] XTJT { get; set; }
        public string JTMS { get; set; }
        public string JTMC { get; set; }
    }
}
