//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_GZYWSJ
    {
        public decimal JLXH { get; set; }
        public decimal JZXH { get; set; }
        public decimal SJZH { get; set; }
        public decimal GZZH { get; set; }
        public decimal QDLX { get; set; }
        public decimal CYXH { get; set; }
        public decimal CYLX { get; set; }
        public string DXFL { get; set; }
        public string DXSB { get; set; }
        public string DXMS { get; set; }
        public decimal JZBZ { get; set; }
        public string BZXX { get; set; }
        public decimal CZBZ { get; set; }
        public Nullable<decimal> CZGL { get; set; }
        public string QXMS { get; set; }
        public Nullable<System.DateTime> CZSJ { get; set; }
    }
}
