//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_wh_zkss
    {
        public decimal jlxh { get; set; }
        public decimal sszk { get; set; }
        public decimal ssnm { get; set; }
        public decimal zxbz { get; set; }
        public Nullable<decimal> ssdj { get; set; }
        public Nullable<decimal> qgzc { get; set; }
        public Nullable<decimal> zcss { get; set; }
        public Nullable<decimal> tcss { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
