//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_yzdy
    {
        public decimal dyxh { get; set; }
        public decimal zyh { get; set; }
        public decimal yzqx { get; set; }
        public Nullable<System.DateTime> dyrq { get; set; }
        public string dynr { get; set; }
        public decimal dyym { get; set; }
        public decimal dyhh { get; set; }
        public decimal czbz { get; set; }
        public decimal yzbxh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
