//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_sys_syxmgz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emr_sys_syxmgz()
        {
            this.emr_kbm_syxmjy = new HashSet<emr_kbm_syxmjy>();
        }
    
        public decimal gzxh { get; set; }
        public decimal gzlb { get; set; }
        public string gzmc { get; set; }
        public string gzkz { get; set; }
        public string gzsm { get; set; }
        public decimal syzt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_kbm_syxmjy> emr_kbm_syxmjy { get; set; }
    }
}
