//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_wh_ysxzqx
    {
        public decimal jlxh { get; set; }
        public string ysdm { get; set; }
        public decimal xzxh { get; set; }
        public decimal qxjb { get; set; }
        public Nullable<decimal> mrbz { get; set; }
        public Nullable<decimal> jgid { get; set; }
    
        public virtual emr_wh_zlxz emr_wh_zlxz { get; set; }
    }
}
