//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_mb_tbjl
    {
        public decimal jlbh { get; set; }
        public decimal jhbh { get; set; }
        public decimal tbbz { get; set; }
        public decimal mbbh { get; set; }
        public System.DateTime jlsj { get; set; }
        public Nullable<System.DateTime> tbwcsj { get; set; }
    }
}
