//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_GZJZ
    {
        public decimal GZZH { get; set; }
        public string GZZM { get; set; }
        public decimal QDLX { get; set; }
        public string BZXX { get; set; }
        public decimal QYBZ { get; set; }
    }
}
