//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_YXPFB_JL01
    {
        public decimal PFSB { get; set; }
        public decimal JZXH { get; set; }
        public decimal BRKS { get; set; }
        public Nullable<decimal> ZLXZ { get; set; }
        public string GCYS { get; set; }
        public string ZZYS { get; set; }
        public string ZRYS { get; set; }
        public decimal PFBLX { get; set; }
        public decimal PFBXH { get; set; }
        public string PFBMC { get; set; }
        public Nullable<decimal> DFZZ { get; set; }
        public Nullable<decimal> QTZZ { get; set; }
        public string LCYY { get; set; }
        public string QTLCYY { get; set; }
        public string PFYS { get; set; }
        public System.DateTime PFSJ { get; set; }
        public Nullable<decimal> BLBH { get; set; }
        public decimal ZFBZ { get; set; }
        public Nullable<decimal> APACHE { get; set; }
        public Nullable<System.DateTime> APACHE_JZSJ { get; set; }
        public Nullable<decimal> APACHE_PFSB { get; set; }
    }
}
