//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_kbm_syxm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emr_kbm_syxm()
        {
            this.emr_bl_basysj = new HashSet<emr_bl_basysj>();
            this.emr_kbm_syxmjy = new HashSet<emr_kbm_syxmjy>();
        }
    
        public decimal xmxh { get; set; }
        public decimal xmlb { get; set; }
        public string xmbm { get; set; }
        public string xmmc { get; set; }
        public decimal sjlx { get; set; }
        public string sjgs { get; set; }
        public Nullable<decimal> tqgz { get; set; }
        public string gzkz { get; set; }
        public string dyys { get; set; }
        public string mrz { get; set; }
        public string ksmrz { get; set; }
        public decimal zdhd { get; set; }
        public string xsmc { get; set; }
        public decimal dqfs { get; set; }
        public decimal xskd { get; set; }
        public string bzxx { get; set; }
        public decimal syzt { get; set; }
        public string glzd { get; set; }
        public Nullable<decimal> gxfs { get; set; }
        public Nullable<decimal> xmfl { get; set; }
        public Nullable<decimal> sybtx { get; set; }
        public string bxx { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_bl_basysj> emr_bl_basysj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_kbm_syxmjy> emr_kbm_syxmjy { get; set; }
    }
}
