//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_wh_ylqxtsbr
    {
        public decimal jlxh { get; set; }
        public decimal qxxh { get; set; }
        public decimal tsbm { get; set; }
        public decimal kzfs { get; set; }
        public string bzxx { get; set; }
    
        public virtual emr_wh_ylqx emr_wh_ylqx { get; set; }
    }
}
