//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_mb_grys
    {
        public decimal ysbh { get; set; }
        public string ysmc { get; set; }
        public string yslb { get; set; }
        public string ysnr { get; set; }
        public Nullable<decimal> sszk { get; set; }
        public string ssks { get; set; }
        public Nullable<decimal> ssqy { get; set; }
        public string pydm { get; set; }
        public Nullable<System.DateTime> cjsj { get; set; }
        public Nullable<System.DateTime> gxsj { get; set; }
        public string ysdm { get; set; }
        public string ysxm { get; set; }
        public Nullable<decimal> syzt { get; set; }
    }
}
