//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_jcxm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emr_jcxm()
        {
            this.emr_jcbw = new HashSet<emr_jcbw>();
        }
    
        public decimal sqdh { get; set; }
        public decimal zlxmid { get; set; }
        public decimal jczt { get; set; }
        public string bzxx { get; set; }
        public Nullable<decimal> jcbws { get; set; }
        public Nullable<decimal> yzxh { get; set; }
        public string risid { get; set; }
        public Nullable<System.DateTime> yysj { get; set; }
        public decimal zfbz { get; set; }
        public string jcmc { get; set; }
        public string jcbw { get; set; }
        public string jcff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_jcbw> emr_jcbw { get; set; }
        public virtual emr_jcsq emr_jcsq { get; set; }
    }
}
