//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_wh_ysjs
    {
        public decimal jlxh { get; set; }
        public string ysdm { get; set; }
        public Nullable<decimal> jsxh { get; set; }
        public string bzxx { get; set; }
    
        public virtual emr_wh_yljs emr_wh_yljs { get; set; }
    }
}
