//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_GA_JCXX
    {
        public decimal JLXH { get; set; }
        public string YYMC { get; set; }
        public decimal JGID { get; set; }
        public Nullable<decimal> YYDJ { get; set; }
        public Nullable<decimal> YYXZ { get; set; }
        public Nullable<decimal> YQSL { get; set; }
        public Nullable<decimal> JZMJ { get; set; }
        public Nullable<decimal> ZGZS { get; set; }
        public Nullable<decimal> YSRS { get; set; }
        public Nullable<decimal> HSRS { get; set; }
        public Nullable<decimal> YJRS { get; set; }
        public Nullable<decimal> NMZRC { get; set; }
        public Nullable<decimal> NZYRC { get; set; }
        public Nullable<decimal> NSSRC { get; set; }
        public Nullable<decimal> SSSSL { get; set; }
        public Nullable<decimal> ZZCWS { get; set; }
        public Nullable<decimal> BFSL { get; set; }
        public Nullable<decimal> MZKS { get; set; }
        public Nullable<decimal> CWSL { get; set; }
        public Nullable<decimal> XXBZ { get; set; }
        public Nullable<decimal> FGXXBZ { get; set; }
        public Nullable<decimal> XXZRS { get; set; }
        public Nullable<decimal> YJSRS { get; set; }
        public Nullable<decimal> BKRS { get; set; }
        public Nullable<decimal> DZRS { get; set; }
        public Nullable<decimal> GZRS { get; set; }
        public Nullable<decimal> GLRS { get; set; }
        public Nullable<decimal> XXRS { get; set; }
        public Nullable<decimal> YXRS { get; set; }
        public Nullable<decimal> QTRS { get; set; }
        public Nullable<decimal> JHSBS { get; set; }
        public Nullable<int> YLZCSJ { get; set; }
        public Nullable<decimal> QNZSR { get; set; }
        public Nullable<decimal> SNLJTR { get; set; }
        public Nullable<decimal> QNXXTR { get; set; }
        public Nullable<decimal> CSBZ { get; set; }
        public Nullable<decimal> FSBZ { get; set; }
        public Nullable<decimal> NJBZ { get; set; }
        public Nullable<decimal> BLBZ { get; set; }
        public Nullable<decimal> XDTBZ { get; set; }
        public Nullable<decimal> NDTBZ { get; set; }
        public Nullable<decimal> JDTBZ { get; set; }
        public Nullable<decimal> FGNBZ { get; set; }
        public Nullable<decimal> SMHXBZ { get; set; }
        public Nullable<decimal> QTJC { get; set; }
        public Nullable<decimal> ZJBZ { get; set; }
        public Nullable<decimal> TNBZ { get; set; }
        public Nullable<decimal> LLBZ { get; set; }
        public Nullable<decimal> FLBZ { get; set; }
        public Nullable<decimal> XTBZ { get; set; }
        public Nullable<decimal> GYYC { get; set; }
        public Nullable<decimal> QTZL { get; set; }
        public Nullable<System.DateTime> DJSJ { get; set; }
    }
}
