//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMRA_WDSCRZ
    {
        public decimal JLXH { get; set; }
        public decimal SJLY { get; set; }
        public decimal JGID { get; set; }
        public string JZHM { get; set; }
        public string WJMC { get; set; }
        public Nullable<decimal> LBBM { get; set; }
        public Nullable<decimal> JYFS { get; set; }
        public Nullable<decimal> WJZT { get; set; }
        public string ZTSM { get; set; }
        public Nullable<System.DateTime> CZRQ { get; set; }
        public string CZR { get; set; }
    }
}
