//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMRA_WH_JSBLQX
    {
        public decimal JLXH { get; set; }
        public decimal JSBM { get; set; }
        public Nullable<decimal> LBBM { get; set; }
        public string LBMC { get; set; }
        public Nullable<decimal> CKQX { get; set; }
        public Nullable<decimal> BJQX { get; set; }
        public Nullable<decimal> SYQX { get; set; }
        public Nullable<decimal> DCQX { get; set; }
        public Nullable<decimal> DYQX { get; set; }
        public Nullable<decimal> QYZT { get; set; }
    }
}
