//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMRA_WH_BAML
    {
        public decimal LBBM { get; set; }
        public string LBMC { get; set; }
        public Nullable<decimal> LBXH { get; set; }
        public Nullable<decimal> DYWD { get; set; }
        public Nullable<decimal> QSTJ { get; set; }
        public Nullable<decimal> QSGD { get; set; }
        public Nullable<decimal> QMGS { get; set; }
        public Nullable<decimal> SJLY { get; set; }
        public string CJBM { get; set; }
    }
}
