//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class GY_DZLJ
    {
        public decimal JGID { get; set; }
        public decimal DZXH { get; set; }
        public decimal KSD { get; set; }
        public decimal JSD { get; set; }
        public decimal DZBL { get; set; }
        public decimal SYLB { get; set; }
        public decimal QYBZ { get; set; }
        public Nullable<System.DateTime> QYSJ { get; set; }
        public Nullable<System.DateTime> ZZSJ { get; set; }
    }
}
