//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class gy_fybr
    {
        public decimal brxz { get; set; }
        public string fyzh { get; set; }
        public Nullable<decimal> fydw { get; set; }
        public string brxm { get; set; }
        public string pydm { get; set; }
        public Nullable<decimal> brxb { get; set; }
        public Nullable<System.DateTime> csny { get; set; }
        public Nullable<System.DateTime> lzrq { get; set; }
        public string jzxm { get; set; }
        public decimal zfpb { get; set; }
        public Nullable<System.DateTime> zhxq { get; set; }
    
        public virtual gy_brxz gy_brxz { get; set; }
        public virtual gy_fydw gy_fydw { get; set; }
    }
}
