//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class GY_JBTJM
    {
        public decimal TJXH { get; set; }
        public string TJBM { get; set; }
        public string TJMC { get; set; }
        public string MLBM { get; set; }
        public string GLICD { get; set; }
        public string PYDM { get; set; }
        public string WBDM { get; set; }
        public decimal ZXBZ { get; set; }
        public string BZXX { get; set; }
    }
}
