//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HIQC_EMR_LIST
    {
        public string PATIENT_ID { get; set; }
        public string EMR_ID { get; set; }
        public string EMR_ITEM { get; set; }
        public string EMR_CREATEDOC { get; set; }
        public Nullable<System.DateTime> EMR_CREATEDATE { get; set; }
        public string EMR_FLAG { get; set; }
        public Nullable<System.DateTime> EMR_LASTMODIFY { get; set; }
        public string EMR_TYPE { get; set; }
        public byte[] EMR_TEXT { get; set; }
        public string EMR_CONTENT { get; set; }
        public string EMR_ROWSTATUS { get; set; }
        public decimal JGID { get; set; }
    }
}
