//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HIQC_ELEMENT_CONDITION
    {
        public string ELEMENT_CONID { get; set; }
        public string ELEMENT_REA { get; set; }
        public string ELEMENT_CLSID { get; set; }
        public string ELEMENT_CONNAME { get; set; }
        public Nullable<decimal> ELEMENT_VALUE { get; set; }
        public string ELEMENT_STOP { get; set; }
        public Nullable<decimal> ELEMENT_DAYS { get; set; }
        public decimal JGID { get; set; }
    }
}
