//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hl_jydx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hl_jydx()
        {
            this.hl_jypf = new HashSet<hl_jypf>();
        }
    
        public decimal jyjhbh { get; set; }
        public decimal jydxbh { get; set; }
        public string jydx { get; set; }
    
        public virtual hl_jyjh hl_jyjh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hl_jypf> hl_jypf { get; set; }
    }
}
