//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_KJXX
    {
        public System.DateTime NF { get; set; }
        public Nullable<decimal> ISSN { get; set; }
        public Nullable<decimal> YYCS { get; set; }
        public Nullable<decimal> SCI { get; set; }
        public Nullable<decimal> WCGJKYKTS { get; set; }
        public Nullable<decimal> WCSJKYKTS { get; set; }
        public Nullable<decimal> GJKYJJED { get; set; }
        public Nullable<decimal> SJKYJJED { get; set; }
        public string DJYG { get; set; }
        public Nullable<System.DateTime> DJRQ { get; set; }
        public Nullable<decimal> SPJG { get; set; }
        public string SPYG { get; set; }
        public Nullable<System.DateTime> SPRQ { get; set; }
        public string THYY { get; set; }
        public decimal JGID { get; set; }
    }
}
