//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_YYGR
    {
        public decimal JLXH { get; set; }
        public decimal JCLX { get; set; }
        public decimal SBLX { get; set; }
        public decimal SBXH { get; set; }
        public decimal ZYH { get; set; }
        public Nullable<decimal> BGKS { get; set; }
        public Nullable<System.DateTime> BGRQ { get; set; }
        public string CZGH { get; set; }
        public System.DateTime CDATE { get; set; }
        public decimal ZFPB { get; set; }
        public decimal JGID { get; set; }
    }
}
