//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_PSZD
    {
        public string PSBB { get; set; }
        public decimal PSXH { get; set; }
        public string PSDM { get; set; }
        public string PSMC { get; set; }
        public string PYDM { get; set; }
        public string WBDM { get; set; }
        public string JXDM { get; set; }
        public string QTDM { get; set; }
        public Nullable<decimal> SJXH { get; set; }
        public string PSLB { get; set; }
        public string BZ { get; set; }
        public decimal PSHX { get; set; }
        public decimal PSTY { get; set; }
    }
}
