//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hs_pzlx
    {
        public decimal pzlx { get; set; }
        public string pzmc { get; set; }
        public Nullable<int> hslx { get; set; }
        public Nullable<int> fspb { get; set; }
        public string fzfs { get; set; }
        public string jdfs { get; set; }
        public string hzyz { get; set; }
        public Nullable<int> kmgd { get; set; }
        public string zdkm { get; set; }
        public string kmtx { get; set; }
        public Nullable<int> kmcc { get; set; }
        public string kmly { get; set; }
        public string ksly { get; set; }
        public string pzsm { get; set; }
        public Nullable<int> cjpl { get; set; }
        public Nullable<System.DateTime> mcsj { get; set; }
        public Nullable<int> sybp { get; set; }
        public Nullable<System.DateTime> sysj { get; set; }
    }
}
