//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hs_zy_hldy
    {
        public string jzxh { get; set; }
        public decimal hllb { get; set; }
        public decimal hlxh { get; set; }
        public decimal dyhh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
