//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hzyb_ka82
    {
        public string aka090 { get; set; }
        public string aka091 { get; set; }
        public string bka030 { get; set; }
        public string aka120 { get; set; }
        public string aka121 { get; set; }
        public Nullable<System.DateTime> aae036 { get; set; }
    }
}
