//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hzyb_kb01
    {
        public string akb020 { get; set; }
        public string akb021 { get; set; }
        public string aka101 { get; set; }
        public Nullable<System.DateTime> aae036 { get; set; }
    }
}
