//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hzyb_bxjs
    {
        public string brxm { get; set; }
        public string xb { get; set; }
        public string sfzh { get; set; }
        public string yllb { get; set; }
        public string yybh { get; set; }
        public string yymc { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public string bxlsh { get; set; }
        public Nullable<decimal> ylfze { get; set; }
        public Nullable<decimal> bxje { get; set; }
        public Nullable<decimal> zfje { get; set; }
        public Nullable<decimal> zlje { get; set; }
        public Nullable<decimal> zfuje { get; set; }
        public string sh { get; set; }
    }
}
