//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ipt_record
    {
        public string jgdm { get; set; }
        public string kh { get; set; }
        public Nullable<decimal> klx { get; set; }
        public string jzlsh { get; set; }
        public string bzbah { get; set; }
        public string zyjzlx { get; set; }
        public string ryksbm { get; set; }
        public string cyksbm { get; set; }
        public Nullable<System.DateTime> rysj { get; set; }
        public Nullable<System.DateTime> cysj { get; set; }
        public string cyzd { get; set; }
        public string zdmc { get; set; }
        public decimal scbz { get; set; }
    }
}
