//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ka56
    {
        public string aka090 { get; set; }
        public string aka091 { get; set; }
        public string aka100 { get; set; }
        public string aka101 { get; set; }
        public Nullable<decimal> aka102 { get; set; }
        public string aae011 { get; set; }
        public System.DateTime aae036 { get; set; }
        public System.DateTime aka234 { get; set; }
        public Nullable<System.DateTime> aka235 { get; set; }
        public decimal xzxh { get; set; }
    }
}
