//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class KH_KPDY
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public decimal BRID { get; set; }
        public System.DateTime DYRQ { get; set; }
        public string DYGH { get; set; }
        public decimal KPID { get; set; }
        public decimal KPLB { get; set; }
        public string WJ_1 { get; set; }
        public string WJ_2 { get; set; }
        public string WJ_3 { get; set; }
    }
}
