//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class lg_hcmx
    {
        public decimal zyh { get; set; }
        public System.DateTime hcrq { get; set; }
        public Nullable<System.DateTime> zzrq { get; set; }
        public decimal hclx { get; set; }
        public string hqch { get; set; }
        public string hhch { get; set; }
        public Nullable<decimal> hqks { get; set; }
        public Nullable<decimal> hhks { get; set; }
        public Nullable<decimal> hqbq { get; set; }
        public Nullable<decimal> hhbq { get; set; }
        public Nullable<decimal> jscs { get; set; }
        public string czgh { get; set; }
    
        public virtual lg_brry lg_brry { get; set; }
    }
}
