//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class lg_jsmx
    {
        public decimal zyh { get; set; }
        public decimal jscs { get; set; }
        public decimal ksdm { get; set; }
        public decimal fyxm { get; set; }
        public decimal zjje { get; set; }
        public decimal zfje { get; set; }
        public decimal zlje { get; set; }
    
        public virtual lg_zyjs lg_zyjs { get; set; }
    }
}
