//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class lg_jzxx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lg_jzxx()
        {
            this.lg_zfpj = new HashSet<lg_zfpj>();
        }
    
        public System.DateTime jzrq { get; set; }
        public string czgh { get; set; }
        public decimal cysr { get; set; }
        public decimal yjje { get; set; }
        public decimal yjxj { get; set; }
        public decimal yjzp { get; set; }
        public decimal tpje { get; set; }
        public string qsfp { get; set; }
        public string zzfp { get; set; }
        public string qssj { get; set; }
        public string zzsj { get; set; }
        public decimal fpzs { get; set; }
        public decimal sjzs { get; set; }
        public decimal ysje { get; set; }
        public decimal ysxj { get; set; }
        public decimal yszp { get; set; }
        public decimal zpzs { get; set; }
        public decimal tyjj { get; set; }
        public decimal tjks { get; set; }
        public decimal kbje { get; set; }
        public decimal kbzp { get; set; }
        public Nullable<System.DateTime> hzrq { get; set; }
        public decimal yjqt { get; set; }
        public decimal ysqt { get; set; }
        public decimal qtzs { get; set; }
        public decimal srje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lg_zfpj> lg_zfpj { get; set; }
    }
}
