//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class MQMS_WH_CFYYYLFL
    {
        public decimal FZXH { get; set; }
        public string YLFL { get; set; }
        public string FZMC { get; set; }
        public string FLMC { get; set; }
        public System.DateTime CJSJ { get; set; }
    }
}
