//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ms_cf01_ls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ms_cf01_ls()
        {
            this.ms_cf02_ls = new HashSet<ms_cf02_ls>();
        }
    
        public decimal cfsb { get; set; }
        public string cfhm { get; set; }
        public string fphm { get; set; }
        public Nullable<decimal> mzxh { get; set; }
        public decimal cflx { get; set; }
        public Nullable<decimal> brid { get; set; }
        public string brxm { get; set; }
        public System.DateTime kfrq { get; set; }
        public decimal cfts { get; set; }
        public Nullable<decimal> ksdm { get; set; }
        public string ysdm { get; set; }
        public Nullable<System.DateTime> fyrq { get; set; }
        public Nullable<decimal> fyck { get; set; }
        public string hjgh { get; set; }
        public string pygh { get; set; }
        public string fygh { get; set; }
        public decimal pybz { get; set; }
        public decimal fybz { get; set; }
        public Nullable<decimal> cfgl { get; set; }
        public decimal zfpb { get; set; }
        public Nullable<decimal> dybz { get; set; }
        public decimal yfsb { get; set; }
        public Nullable<decimal> tscf { get; set; }
        public Nullable<int> tslx { get; set; }
        public Nullable<decimal> tybz { get; set; }
        public Nullable<decimal> cfbz { get; set; }
        public Nullable<decimal> jzxh { get; set; }
        public decimal yxpb { get; set; }
        public string jzkh { get; set; }
        public Nullable<decimal> brtz { get; set; }
        public Nullable<decimal> sydybz { get; set; }
        public Nullable<decimal> cflb { get; set; }
        public string jbzd { get; set; }
        public Nullable<decimal> sydybz1 { get; set; }
        public Nullable<decimal> qybr { get; set; }
        public Nullable<decimal> cgdy { get; set; }
        public string KJLYLY { get; set; }
        public string HDGH { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<System.DateTime> HDRQ { get; set; }
        public Nullable<System.DateTime> ZFSJ { get; set; }
        public Nullable<decimal> BRXZ { get; set; }
        public Nullable<decimal> KJLY { get; set; }
        public Nullable<decimal> TYSM { get; set; }
        public Nullable<decimal> DJYBZ { get; set; }
        public Nullable<decimal> DJLY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ms_cf02_ls> ms_cf02_ls { get; set; }
    }
}
