//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class MS_SZMX_LS
    {
        public decimal SBXH { get; set; }
        public decimal JGID { get; set; }
        public decimal BRID { get; set; }
        public System.DateTime RQ { get; set; }
        public string ZY { get; set; }
        public Nullable<decimal> ZHYE { get; set; }
        public Nullable<decimal> JKFS { get; set; }
        public decimal JFJE { get; set; }
        public decimal DFJE { get; set; }
        public string CZGH { get; set; }
        public string SZLB { get; set; }
        public string PZHM { get; set; }
        public Nullable<System.DateTime> JZRQ { get; set; }
        public Nullable<System.DateTime> HZRQ { get; set; }
    }
}
