//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class mzyy_pbbg
    {
        public decimal jlxh { get; set; }
        public string trade { get; set; }
        public string bglx { get; set; }
        public string pbid { get; set; }
        public System.DateTime bgsj { get; set; }
        public System.DateTime kssj { get; set; }
        public Nullable<System.DateTime> jssj { get; set; }
        public Nullable<decimal> swtz { get; set; }
        public Nullable<decimal> xwtz { get; set; }
        public string bzxx { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> tzlx { get; set; }
        public decimal scbz { get; set; }
    }
}
