//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pay_qfxx
    {
        public decimal qfxh { get; set; }
        public string sfzh { get; set; }
        public string brxm { get; set; }
        public string smkno { get; set; }
        public string tel { get; set; }
        public decimal zjje { get; set; }
        public decimal zfje { get; set; }
        public string fydw { get; set; }
        public System.DateTime fyrq { get; set; }
        public string fphm { get; set; }
        public decimal sfbz { get; set; }
        public string sfdw { get; set; }
        public Nullable<System.DateTime> sfrq { get; set; }
        public string sfgh { get; set; }
        public string sfdwmc { get; set; }
        public string fydwmc { get; set; }
        public decimal mzzy { get; set; }
        public Nullable<decimal> paymode { get; set; }
        public string fphm_sf { get; set; }
        public Nullable<decimal> znj { get; set; }
        public Nullable<decimal> yshj { get; set; }
    }
}
