//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pd_dlqd
    {
        public decimal dlid { get; set; }
        public string dlbh { get; set; }
        public string dlmc { get; set; }
        public string dlsm { get; set; }
        public decimal dlcc { get; set; }
        public decimal sjdl { get; set; }
        public decimal hmid { get; set; }
        public decimal pmid { get; set; }
        public decimal pmsc { get; set; }
        public decimal pmqc { get; set; }
        public decimal yysc { get; set; }
        public decimal jzfs { get; set; }
        public decimal jzjs { get; set; }
        public string dysm { get; set; }
        public string PACSDL { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> DLLB { get; set; }
    }
}
