//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pd_ffdl
    {
        public decimal dlid { get; set; }
        public decimal ffrq { get; set; }
        public decimal jsdl { get; set; }
        public decimal zdcd { get; set; }
        public decimal zxcd { get; set; }
        public decimal ztbz { get; set; }
        public Nullable<decimal> ifcall { get; set; }
    
        public virtual pd_zdff pd_zdff { get; set; }
    }
}
