//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class PD_ZXYS
    {
        public decimal JGID { get; set; }
        public string YSDM { get; set; }
        public string YSXM { get; set; }
        public decimal DLID { get; set; }
        public Nullable<System.DateTime> DLSJ { get; set; }
        public decimal DLLB { get; set; }
        public string JSJM { get; set; }
        public decimal ZXZT { get; set; }
    }
}
