//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pt_diagnosis
    {
        public string jgdm { get; set; }
        public string jzlsh { get; set; }
        public string zdlsh { get; set; }
        public Nullable<decimal> brbslb { get; set; }
        public string jbdm { get; set; }
        public string jbmc { get; set; }
        public Nullable<decimal> zyzdlbdm { get; set; }
        public string xyzdlbdm { get; set; }
        public string zyzdbz { get; set; }
        public string yszdbz { get; set; }
        public Nullable<decimal> zdyjdm { get; set; }
        public Nullable<System.DateTime> zdrq { get; set; }
        public string zgqk { get; set; }
        public decimal scbz { get; set; }
    }
}
