//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class py_zwjl
    {
        public decimal jlxh { get; set; }
        public decimal pdxh { get; set; }
        public string zwhm { get; set; }
        public decimal sysh { get; set; }
        public decimal brid { get; set; }
        public string mzhm { get; set; }
        public string brxm { get; set; }
        public decimal brxb { get; set; }
        public decimal brnl { get; set; }
        public decimal dybz { get; set; }
        public decimal lsbz { get; set; }
        public decimal zfbz { get; set; }
        public System.DateTime ksrq { get; set; }
        public Nullable<System.DateTime> sysj { get; set; }
        public decimal yjsj { get; set; }
        public decimal sypc { get; set; }
        public decimal syps { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public string djgh { get; set; }
        public string sjgh { get; set; }
        public string jsgh { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> czbz { get; set; }
        public string pygh { get; set; }
        public string zsgh { get; set; }
        public string hygh { get; set; }
    }
}
