//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class rs_yljff
    {
        public string ygdm { get; set; }
        public decimal ffnf { get; set; }
        public decimal ffyf { get; set; }
        public Nullable<System.DateTime> ffrq { get; set; }
        public Nullable<decimal> ffje { get; set; }
        public string bz { get; set; }
    
        public virtual rs_jbxx rs_jbxx { get; set; }
    }
}
