//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class RY_YYDJ
    {
        public decimal JGID { get; set; }
        public decimal YYBH { get; set; }
        public decimal TZBH { get; set; }
        public string YYDJR { get; set; }
        public Nullable<System.DateTime> YYDJRQ { get; set; }
        public string QXYY { get; set; }
        public string QXR { get; set; }
        public Nullable<System.DateTime> QXSJ { get; set; }
        public Nullable<decimal> YYBZ { get; set; }
        public string BZ { get; set; }
    }
}
