//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sb_szmx_ext
    {
        public decimal sbxh { get; set; }
        public decimal zbxh { get; set; }
        public System.DateTime szrq { get; set; }
        public decimal xmxh { get; set; }
        public Nullable<decimal> xmje { get; set; }
    
        public virtual sb_kzxm sb_kzxm { get; set; }
    }
}
