//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sb_sblb
    {
        public decimal bbld { get; set; }
        public string kfsb { get; set; }
        public decimal zbxh { get; set; }
        public string sbbh { get; set; }
        public Nullable<decimal> czyz { get; set; }
        public Nullable<decimal> zyks { get; set; }
        public string bggh { get; set; }
        public Nullable<decimal> state { get; set; }
        public Nullable<System.DateTime> czrq { get; set; }
        public Nullable<System.DateTime> zjrq { get; set; }
        public Nullable<decimal> jtzj { get; set; }
    }
}
