//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class SDCC_CYMB
    {
        public decimal MBBS { get; set; }
        public string MBMC { get; set; }
        public string MBNR { get; set; }
        public decimal MBLB { get; set; }
        public decimal GSLB { get; set; }
        public string GSDM { get; set; }
        public string PYDM { get; set; }
        public string WBDM { get; set; }
        public string QTDM { get; set; }
        public decimal ZXBZ { get; set; }
    }
}
