//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sm_qxzb
    {
        public decimal ssbh { get; set; }
        public string qxbh { get; set; }
        public Nullable<decimal> qxsl { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        public virtual sm_ssqx sm_ssqx { get; set; }
        public virtual sm_ssap sm_ssap { get; set; }
    }
}
