//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sm_shxx
    {
        public decimal ssbh { get; set; }
        public Nullable<decimal> zyh { get; set; }
        public Nullable<decimal> mzsfbz { get; set; }
        public string mzsfxx { get; set; }
        public Nullable<decimal> hssfbz { get; set; }
        public string hssfxx { get; set; }
        public Nullable<decimal> ssgr { get; set; }
        public Nullable<decimal> brmy { get; set; }
        public Nullable<decimal> ssbfz { get; set; }
        public Nullable<decimal> yhlb { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        public virtual sm_ssap sm_ssap { get; set; }
    }
}
