//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class smk_dzqb
    {
        public decimal jlxh { get; set; }
        public string jslx { get; set; }
        public string fphm { get; set; }
        public string xflx { get; set; }
        public string jylx { get; set; }
        public string shh { get; set; }
        public string tac { get; set; }
        public string zdh { get; set; }
        public string zdbh { get; set; }
        public string kh { get; set; }
        public string dzqbjyxh { get; set; }
        public string zdjyxh { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public Nullable<decimal> jyje { get; set; }
        public Nullable<decimal> qbye { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> zfpb { get; set; }
        public Nullable<decimal> czbz { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public string ssls { get; set; }
    }
}
