//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ss_operate_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ss_operate_user()
        {
            this.ss_register = new HashSet<ss_register>();
        }
    
        public int xtsb { get; set; }
        public string yhdm { get; set; }
        public string yhzm { get; set; }
        public string yhmc { get; set; }
        public string yhkl { get; set; }
    
        public virtual ss_group ss_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ss_register> ss_register { get; set; }
    }
}
