//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class tj_gcbb
    {
        public decimal ksdm { get; set; }
        public System.DateTime tjrq { get; set; }
        public Nullable<decimal> mrbc { get; set; }
        public Nullable<decimal> yyrs { get; set; }
        public Nullable<decimal> rgrs { get; set; }
        public Nullable<decimal> cgzs { get; set; }
        public Nullable<decimal> cgrs { get; set; }
        public Nullable<decimal> ryrs { get; set; }
        public Nullable<decimal> zyrs { get; set; }
        public Nullable<decimal> swrs { get; set; }
        public Nullable<decimal> lgrs { get; set; }
        public Nullable<decimal> qjrc { get; set; }
        public Nullable<decimal> cgrc { get; set; }
        public Nullable<decimal> wxrc { get; set; }
        public Nullable<decimal> qjsw { get; set; }
        public Nullable<decimal> sycs { get; set; }
        public Nullable<decimal> syfy { get; set; }
        public Nullable<decimal> sxcs { get; set; }
        public Nullable<decimal> sxfy { get; set; }
        public Nullable<decimal> cgcr { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> JLXH { get; set; }
    }
}
