//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wxyb_spxx
    {
        public decimal jlxh { get; set; }
        public Nullable<decimal> splx { get; set; }
        public decimal jylx { get; set; }
        public decimal brid { get; set; }
        public string icxx { get; set; }
        public string ickh { get; set; }
        public string grbh { get; set; }
        public decimal fyxh { get; set; }
        public Nullable<decimal> yplx { get; set; }
        public decimal xmlx { get; set; }
        public string ybbm { get; set; }
        public string fymc { get; set; }
        public string sqyy { get; set; }
        public string sqnd { get; set; }
        public string zzyy { get; set; }
        public decimal sqsl { get; set; }
        public Nullable<decimal> basl { get; set; }
        public Nullable<decimal> spsl { get; set; }
        public Nullable<decimal> cxsl { get; set; }
        public Nullable<decimal> sysl { get; set; }
        public string spbh { get; set; }
        public Nullable<decimal> spzt { get; set; }
        public Nullable<decimal> spqr { get; set; }
        public string icd9 { get; set; }
        public decimal jbxh { get; set; }
        public string jbmc { get; set; }
        public string zllb { get; set; }
        public Nullable<System.DateTime> ksrq { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public string sqys { get; set; }
        public System.DateTime sqrq { get; set; }
        public Nullable<decimal> spjg { get; set; }
        public string czgh { get; set; }
        public string brxm { get; set; }
        public Nullable<decimal> scsl { get; set; }
        public Nullable<decimal> ypcd { get; set; }
        public string mzhm { get; set; }
        public string bz { get; set; }
        public decimal ypjl { get; set; }
        public string jldw { get; set; }
    }
}
