//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class WXYB_ZFJZXXSC_JZLB
    {
        public string zyxlh { get; set; }
        public string tfbz { get; set; }
        public string yzyxlh { get; set; }
        public string xm { get; set; }
        public string sfz { get; set; }
        public string fph { get; set; }
        public string blh { get; set; }
        public System.DateTime ryrq { get; set; }
        public System.DateTime cyrq { get; set; }
        public string jzfs { get; set; }
        public decimal zfy { get; set; }
        public decimal fymxts { get; set; }
        public string zyzdjbbm { get; set; }
        public string zyzdjbmc { get; set; }
        public string bqms { get; set; }
        public string ksmc { get; set; }
        public string bqcw { get; set; }
        public string ysfwbm { get; set; }
        public string kjysxm { get; set; }
        public decimal scbz { get; set; }
        public System.DateTime scsj { get; set; }
        public string czgh { get; set; }
        public decimal jycljg { get; set; }
        public string cwxx { get; set; }
    }
}
