//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class WXYB_SXJLSC
    {
        public string jzlsh { get; set; }
        public string grbh { get; set; }
        public string qx { get; set; }
        public string hxbxy { get; set; }
        public string qbhxbxy { get; set; }
        public string xxb { get; set; }
        public string lcd { get; set; }
        public string xj { get; set; }
        public string zssx { get; set; }
        public decimal scbz { get; set; }
        public System.DateTime scsj { get; set; }
        public string czgh { get; set; }
        public decimal jycljg { get; set; }
        public string cwxx { get; set; }
    }
}
