//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class WXYKT_JYGN
    {
        public decimal GNH { get; set; }
        public string GNMS { get; set; }
        public Nullable<decimal> JYSQ { get; set; }
        public Nullable<decimal> TFJY { get; set; }
        public Nullable<decimal> JYCX { get; set; }
        public Nullable<decimal> JYQR { get; set; }
        public string BZ { get; set; }
    }
}
