//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wz_bs01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wz_bs01()
        {
            this.wz_bs02 = new HashSet<wz_bs02>();
        }
    
        public decimal djbh { get; set; }
        public decimal ckbh { get; set; }
        public string lzdh { get; set; }
        public Nullable<decimal> ksdm { get; set; }
        public Nullable<decimal> xtsb { get; set; }
        public Nullable<System.DateTime> zdsj { get; set; }
        public string zdgh { get; set; }
        public Nullable<System.DateTime> jzsj { get; set; }
        public string jzgh { get; set; }
        public string djzt { get; set; }
        public string djbz { get; set; }
    
        public virtual wz_ckxx wz_ckxx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wz_bs02> wz_bs02 { get; set; }
    }
}
