//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wz_ck01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wz_ck01()
        {
            this.wz_ck02 = new HashSet<wz_ck02>();
        }
    
        public decimal djbh { get; set; }
        public decimal ckbh { get; set; }
        public Nullable<decimal> lzfs { get; set; }
        public string lzdh { get; set; }
        public string ckdw { get; set; }
        public Nullable<System.DateTime> zdsj { get; set; }
        public string zdgh { get; set; }
        public Nullable<System.DateTime> yssj { get; set; }
        public string ysgh { get; set; }
        public string djzt { get; set; }
        public string fphm { get; set; }
        public Nullable<System.DateTime> jzsj { get; set; }
        public string jzgh { get; set; }
        public string djbz { get; set; }
        public string brxm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wz_ck02> wz_ck02 { get; set; }
    }
}
