//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yf_rk01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yf_rk01()
        {
            this.yf_rk02 = new HashSet<yf_rk02>();
        }
    
        public decimal yfsb { get; set; }
        public decimal ckbh { get; set; }
        public decimal rkfs { get; set; }
        public decimal rkdh { get; set; }
        public System.DateTime rkrq { get; set; }
        public string rkbz { get; set; }
        public decimal RKPB { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        public virtual yf_rkfs yf_rkfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yf_rk02> yf_rk02 { get; set; }
    }
}
