//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yf_yfrb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yf_yfrb()
        {
            this.yf_rbmx = new HashSet<yf_rbmx>();
        }
    
        public decimal yfsb { get; set; }
        public System.DateTime rbrq { get; set; }
        public Nullable<System.DateTime> qssj { get; set; }
        public Nullable<System.DateTime> zzsj { get; set; }
        public string BZ { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yf_rbmx> yf_rbmx { get; set; }
    }
}
