//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YF_ZY_SFJL
    {
        public decimal JGID { get; set; }
        public decimal JLXH { get; set; }
        public decimal ZYH { get; set; }
        public Nullable<decimal> SFCS { get; set; }
        public decimal YPXH { get; set; }
        public Nullable<decimal> YPCD { get; set; }
        public string YPMC { get; set; }
        public Nullable<decimal> YPSL { get; set; }
        public string YFGG { get; set; }
        public string YFDW { get; set; }
        public Nullable<decimal> YFBZ { get; set; }
        public Nullable<decimal> CFTS { get; set; }
        public string SYPC { get; set; }
        public Nullable<decimal> YPYF { get; set; }
        public decimal YZXH { get; set; }
        public Nullable<decimal> YZZH { get; set; }
        public Nullable<decimal> SFBZ { get; set; }
        public string SFGH { get; set; }
        public Nullable<System.DateTime> SFSJ { get; set; }
        public string SFYJ { get; set; }
    }
}
