//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yj_bg01
    {
        public decimal yjxh { get; set; }
        public Nullable<decimal> mbxh { get; set; }
        public decimal mzzy { get; set; }
        public string tjhm { get; set; }
        public string brhm { get; set; }
        public Nullable<decimal> zyh { get; set; }
        public string brxm { get; set; }
        public string brxb { get; set; }
        public Nullable<decimal> brnl { get; set; }
        public string sjys { get; set; }
        public Nullable<decimal> sjks { get; set; }
        public string jcys { get; set; }
        public Nullable<decimal> jcks { get; set; }
        public Nullable<System.DateTime> jcrq { get; set; }
        public Nullable<decimal> xmxh { get; set; }
        public string xmmc { get; set; }
        public Nullable<decimal> hjje { get; set; }
        public string zddm { get; set; }
        public string yqdh { get; set; }
        public string bbbm { get; set; }
        public string yjph { get; set; }
        public Nullable<decimal> wcbz { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
