//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yj_dajg_ext
    {
        public decimal ksdm { get; set; }
        public Nullable<int> pos_x { get; set; }
        public Nullable<int> pos_y { get; set; }
        public Nullable<int> zdkd { get; set; }
        public Nullable<int> zdgd { get; set; }
        public Nullable<decimal> bgcolor { get; set; }
        public Nullable<int> zdfg { get; set; }
        public string txmb { get; set; }
        public Nullable<int> detailheight { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
