//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yj_yjyy
    {
        public decimal jlxh { get; set; }
        public decimal zyh { get; set; }
        public Nullable<decimal> yepb { get; set; }
        public System.DateTime kdsj { get; set; }
        public decimal ypxh { get; set; }
        public Nullable<decimal> ypsl { get; set; }
        public decimal ypdj { get; set; }
        public decimal zfbl { get; set; }
        public Nullable<decimal> yfsb { get; set; }
        public Nullable<decimal> kdks { get; set; }
        public string kdys { get; set; }
        public string czgh { get; set; }
        public string fygh { get; set; }
        public Nullable<System.DateTime> fyrq { get; set; }
        public Nullable<decimal> sybz { get; set; }
        public Nullable<decimal> ypcd { get; set; }
        public string ZTMC { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> FYBQ { get; set; }
    }
}
