//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YK_CDYPLB
    {
        public decimal YPXH { get; set; }
        public decimal YPCD { get; set; }
        public string PZWH { get; set; }
        public decimal TYBZ { get; set; }
        public Nullable<System.DateTime> TYRQ { get; set; }
        public Nullable<decimal> YPDJ { get; set; }
    }
}
