//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yk_jhdw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yk_jhdw()
        {
            this.yk_rk01 = new HashSet<yk_rk01>();
        }
    
        public decimal dwxh { get; set; }
        public string dwmc { get; set; }
        public string pydm { get; set; }
        public string khyh { get; set; }
        public string dwzh { get; set; }
        public Nullable<decimal> xtsb { get; set; }
        public string dwbm { get; set; }
        public string lxr { get; set; }
        public string lxdh { get; set; }
        public string dwdz { get; set; }
        public string bzxx { get; set; }
        public decimal zfpb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yk_rk01> yk_rk01 { get; set; }
    }
}
