//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yk_ypxxbz
    {
        public decimal ypxh { get; set; }
        public string bz1 { get; set; }
        public string bz2 { get; set; }
        public string bz3 { get; set; }
        public string bz4 { get; set; }
        public string bz5 { get; set; }
        public string bz6 { get; set; }
        public string bz7 { get; set; }
        public string bz8 { get; set; }
        public string bz9 { get; set; }
        public string bz10 { get; set; }
        public string bzsm { get; set; }
        public string bz11 { get; set; }
    }
}
