//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ykt_hz_jygn
    {
        public string xzdm { get; set; }
        public string gndm { get; set; }
        public decimal gnh { get; set; }
        public string gnms { get; set; }
        public Nullable<decimal> jysq { get; set; }
        public Nullable<decimal> tfjy { get; set; }
        public Nullable<decimal> jycx { get; set; }
        public Nullable<decimal> jycz { get; set; }
        public string bz { get; set; }
        public Nullable<decimal> wjbz { get; set; }
    }
}
