//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ys_mz_jzls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ys_mz_jzls()
        {
            this.ys_mz_jbzd = new HashSet<ys_mz_jbzd>();
        }
    
        public decimal jzxh { get; set; }
        public decimal ghxh { get; set; }
        public decimal brbh { get; set; }
        public decimal ksdm { get; set; }
        public string ysdm { get; set; }
        public Nullable<decimal> zyzd { get; set; }
        public System.DateTime kssj { get; set; }
        public Nullable<System.DateTime> jssj { get; set; }
        public decimal jzzt { get; set; }
        public Nullable<decimal> yyxh { get; set; }
        public Nullable<System.DateTime> fzrq { get; set; }
        public Nullable<decimal> ghfz { get; set; }
        public Nullable<decimal> jzlx { get; set; }
        public Nullable<decimal> brqx { get; set; }
        public Nullable<decimal> crb { get; set; }
        public string bz { get; set; }
        public string ghks { get; set; }
        public Nullable<decimal> crbsb { get; set; }
        public string bzxx { get; set; }
        public Nullable<decimal> xuey1 { get; set; }
        public Nullable<decimal> xuey2 { get; set; }
        public Nullable<int> bk_crb { get; set; }
        public Nullable<int> bk_jsb { get; set; }
        public Nullable<int> bk_tnb { get; set; }
        public Nullable<int> bk_gxy { get; set; }
        public Nullable<int> bk_zl { get; set; }
        public Nullable<decimal> zhiye { get; set; }
        public Nullable<decimal> zfpb { get; set; }
        public Nullable<decimal> rzzt { get; set; }
        public Nullable<decimal> ycs_ys { get; set; }
        public Nullable<decimal> ycs_cs { get; set; }
        public Nullable<decimal> yz { get; set; }
        public Nullable<decimal> zybk { get; set; }
        public Nullable<decimal> gybk { get; set; }
        public string actnumber { get; set; }
        public string pbzxm { get; set; }
        public Nullable<decimal> pbzgx { get; set; }
        public string pbzdh { get; set; }
        public string pbzdz { get; set; }
        public string pbzdw { get; set; }
        public string zdmc { get; set; }
        public Nullable<decimal> czpb { get; set; }
        public Nullable<decimal> jzbz { get; set; }
        public Nullable<System.DateTime> fbrq { get; set; }
        public string RYNL { get; set; }
        public string LKDJ { get; set; }
        public string BRCH { get; set; }
        public string MQZD { get; set; }
        public string TZLX { get; set; }
        public string RKDJ { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<System.DateTime> BLCJSJ { get; set; }
        public Nullable<decimal> QYBZ { get; set; }
        public Nullable<decimal> XYCLBZ { get; set; }
        public Nullable<decimal> BRLY { get; set; }
        public Nullable<decimal> LKQX { get; set; }
        public Nullable<decimal> LKZD { get; set; }
        public Nullable<decimal> ZXZT { get; set; }
        public Nullable<decimal> FZXH { get; set; }
        public Nullable<decimal> ZDLX { get; set; }
        public Nullable<decimal> JZQJSWBZ { get; set; }
        public Nullable<decimal> JZQJBZ { get; set; }
        public Nullable<decimal> ZGQK { get; set; }
    
        public virtual ys_mz_bcjl ys_mz_bcjl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ys_mz_jbzd> ys_mz_jbzd { get; set; }
    }
}
