//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ys_zy_ysyz
    {
        public string yzbh { get; set; }
        public string jzhm { get; set; }
        public string brbh { get; set; }
        public decimal yzlb { get; set; }
        public string yzzh { get; set; }
        public decimal yzzx { get; set; }
        public decimal xmlb { get; set; }
        public decimal xmzlb { get; set; }
        public string xmdm { get; set; }
        public string ypcd { get; set; }
        public string xmmc { get; set; }
        public System.DateTime kzsj { get; set; }
        public string kzys { get; set; }
        public string sypc { get; set; }
        public decimal mcsl { get; set; }
        public Nullable<decimal> ypbz { get; set; }
        public string xmdw { get; set; }
        public Nullable<decimal> ypjl { get; set; }
        public string jldw { get; set; }
        public Nullable<System.DateTime> tzsj { get; set; }
        public string tzys { get; set; }
        public string gytj { get; set; }
        public decimal xmdj { get; set; }
        public string ksdm { get; set; }
        public string bqid { get; set; }
        public string fyyf { get; set; }
        public string zxks { get; set; }
        public string zxr { get; set; }
        public Nullable<System.DateTime> zxsj { get; set; }
        public string yedm { get; set; }
        public Nullable<decimal> fysx { get; set; }
        public decimal tjbz { get; set; }
        public decimal sqbz { get; set; }
        public string sqdh { get; set; }
        public decimal bgbz { get; set; }
        public Nullable<decimal> fyfs { get; set; }
        public string bzxx { get; set; }
    }
}
