//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yw_ylyh
    {
        public decimal xh { get; set; }
        public string yhms { get; set; }
        public string cljg { get; set; }
        public string djr { get; set; }
        public Nullable<System.DateTime> djsj { get; set; }
        public Nullable<int> qrbz { get; set; }
    }
}
