//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yy_brxx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yy_brxx()
        {
            this.yy_cfxz = new HashSet<yy_cfxz>();
            this.yy_xhmx = new HashSet<yy_xhmx>();
        }
    
        public decimal zkxh { get; set; }
        public Nullable<System.DateTime> jlsj { get; set; }
        public Nullable<decimal> zyh { get; set; }
        public string brxm { get; set; }
        public Nullable<decimal> brxb { get; set; }
        public Nullable<System.DateTime> csny { get; set; }
        public Nullable<decimal> brsg { get; set; }
        public Nullable<decimal> brtz { get; set; }
        public Nullable<decimal> jbbh { get; set; }
        public Nullable<decimal> dqjl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yy_cfxz> yy_cfxz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yy_xhmx> yy_xhmx { get; set; }
    }
}
