//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yy_swcf
    {
        public decimal swxh { get; set; }
        public decimal cfxh { get; set; }
        public decimal cfsl { get; set; }
        public string cfbz { get; set; }
    
        public virtual yy_swdm yy_swdm { get; set; }
        public virtual yy_yycf_wh yy_yycf_wh { get; set; }
    }
}
