//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yy_yyxz_wh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yy_yyxz_wh()
        {
            this.yy_xzmx_wh = new HashSet<yy_xzmx_wh>();
        }
    
        public decimal xzxh { get; set; }
        public string xzmc { get; set; }
        public string xzsm { get; set; }
        public string pydm { get; set; }
        public string tjlb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yy_xzmx_wh> yy_xzmx_wh { get; set; }
    }
}
