//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yy_yypj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yy_yypj()
        {
            this.yy_pjnr = new HashSet<yy_pjnr>();
        }
    
        public decimal pjbh { get; set; }
        public Nullable<System.DateTime> txrq { get; set; }
        public Nullable<decimal> zyh { get; set; }
        public Nullable<decimal> blbh { get; set; }
        public Nullable<decimal> yqzs { get; set; }
        public string pjjy { get; set; }
        public string zkpj { get; set; }
        public Nullable<decimal> bcxh { get; set; }
        public string czgh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yy_pjnr> yy_pjnr { get; set; }
    }
}
