//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yz_mrtj
    {
        public decimal gnbh { get; set; }
        public string yhdm { get; set; }
        public string rqfs { get; set; }
        public string ksrq { get; set; }
        public string jsrq { get; set; }
        public Nullable<decimal> ksdm { get; set; }
        public Nullable<decimal> kscc { get; set; }
        public string ksmc { get; set; }
        public string ysdm { get; set; }
        public string ysxm { get; set; }
        public Nullable<decimal> brxz { get; set; }
        public Nullable<decimal> xzcc { get; set; }
        public string xzmc { get; set; }
        public Nullable<decimal> jbxh { get; set; }
        public string jbbm { get; set; }
        public string jbmc { get; set; }
        public string ypfs { get; set; }
        public Nullable<decimal> xtsb { get; set; }
        public Nullable<decimal> ypxh { get; set; }
        public string ypbm { get; set; }
        public string ypmc { get; set; }
        public string fyfs { get; set; }
        public Nullable<decimal> fyfl { get; set; }
        public Nullable<decimal> fyxm { get; set; }
        public Nullable<decimal> fyxh { get; set; }
        public string fymc { get; set; }
        public Nullable<decimal> dm_1 { get; set; }
        public Nullable<decimal> dm_2 { get; set; }
        public string mc_1 { get; set; }
        public string mc_2 { get; set; }
        public Nullable<decimal> by_1 { get; set; }
        public Nullable<decimal> by_2 { get; set; }
        public Nullable<decimal> tjfs { get; set; }
        public string GNMC { get; set; }
        public string GNCK { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        public virtual yz_gnmk yz_gnmk { get; set; }
    }
}
