//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yz_wzzb
    {
        public decimal jlxh { get; set; }
        public Nullable<System.DateTime> hzrq { get; set; }
        public Nullable<decimal> wpbh { get; set; }
        public string wplb { get; set; }
        public decimal lzfs { get; set; }
        public decimal wpsl { get; set; }
        public decimal lsje { get; set; }
        public decimal pfje { get; set; }
        public decimal jhje { get; set; }
        public decimal ckbh { get; set; }
        public decimal szpb { get; set; }
        public decimal cjbh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
