//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yz_ylsf
    {
        public decimal fyxh { get; set; }
        public string fymc { get; set; }
        public string fydw { get; set; }
        public decimal fygb { get; set; }
        public Nullable<decimal> fyks { get; set; }
        public string pydm { get; set; }
    
        public virtual yz_sfxm yz_sfxm { get; set; }
    }
}
