//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zc_cs01_addition
    {
        public decimal csxh { get; set; }
        public decimal sxxh { get; set; }
        public string sxz { get; set; }
    
        public virtual zc_cs01 zc_cs01 { get; set; }
    }
}
