//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zc_yjjg
    {
        public System.DateTime cwyf { get; set; }
        public decimal zbxh { get; set; }
        public string kfsb { get; set; }
        public decimal zcxz { get; set; }
        public decimal jtzj { get; set; }
        public Nullable<decimal> zyks { get; set; }
        public decimal zczt { get; set; }
    
        public virtual zc_zczb zc_zczb { get; set; }
        public virtual zc_yjjl zc_yjjl { get; set; }
    }
}
