//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zc_zcfj
    {
        public decimal sbxh { get; set; }
        public decimal zbxh { get; set; }
        public string fjmc { get; set; }
        public decimal fjsl { get; set; }
        public decimal fjdj { get; set; }
    
        public virtual zc_zczb zc_zczb { get; set; }
    }
}
