//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_bqyd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zj_bqyd()
        {
            this.zj_bqyd2 = new HashSet<zj_bqyd2>();
        }
    
        public string sbh { get; set; }
        public int fjh { get; set; }
        public string qydw { get; set; }
        public string jyxm { get; set; }
        public string qyz { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
        public string bz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zj_bqyd2> zj_bqyd2 { get; set; }
    }
}
