//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_cfxx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zj_cfxx()
        {
            this.zj_cfmx = new HashSet<zj_cfmx>();
            this.zj_zjtp01 = new HashSet<zj_zjtp01>();
        }
    
        public decimal cfbh { get; set; }
        public Nullable<System.DateTime> lrrq { get; set; }
        public string cfmc { get; set; }
        public string cfly { get; set; }
        public decimal zjbh { get; set; }
        public decimal bzpl { get; set; }
        public string cfbz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zj_cfmx> zj_cfmx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zj_zjtp01> zj_zjtp01 { get; set; }
    }
}
