//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_ckfs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zj_ckfs()
        {
            this.zj_ck01 = new HashSet<zj_ck01>();
        }
    
        public decimal ckfs { get; set; }
        public string fsmc { get; set; }
        public string pydm { get; set; }
        public decimal ckdh { get; set; }
        public Nullable<decimal> dyfs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zj_ck01> zj_ck01 { get; set; }
    }
}
