//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_ddjl
    {
        public string sbh { get; set; }
        public int fjh { get; set; }
        public int xlh { get; set; }
        public string bcbz { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public Nullable<System.DateTime> bgrq { get; set; }
        public Nullable<decimal> ypbh { get; set; }
        public string ypmc { get; set; }
        public string ypgg { get; set; }
        public string ypph { get; set; }
        public string mat { get; set; }
        public Nullable<decimal> wd { get; set; }
        public string ddy { get; set; }
        public string ddsj { get; set; }
        public string zsj { get; set; }
        public string cdff { get; set; }
        public string xhry { get; set; }
        public string sjxhry { get; set; }
        public string jsgs { get; set; }
        public string jsgc { get; set; }
        public string cdhl { get; set; }
        public string zcz { get; set; }
        public string jg { get; set; }
        public string czr { get; set; }
        public string fjr { get; set; }
    }
}
