//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_ryjy
    {
        public string sbh { get; set; }
        public int fjh { get; set; }
        public int xlh { get; set; }
        public string bcbz { get; set; }
        public Nullable<System.DateTime> bgrq { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public Nullable<System.DateTime> zssj { get; set; }
        public Nullable<decimal> sw { get; set; }
        public Nullable<decimal> ypbh { get; set; }
        public string ypmc { get; set; }
        public string ypgg { get; set; }
        public string ypph { get; set; }
        public Nullable<System.DateTime> gjsj { get; set; }
        public Nullable<System.DateTime> sxsj { get; set; }
        public string jsbh { get; set; }
        public Nullable<decimal> jstz { get; set; }
        public Nullable<decimal> sycs { get; set; }
        public Nullable<decimal> sxtw1 { get; set; }
        public Nullable<decimal> sxtw2 { get; set; }
        public Nullable<decimal> sxtw3 { get; set; }
        public Nullable<decimal> pjtw { get; set; }
        public Nullable<decimal> zssl { get; set; }
        public Nullable<decimal> zstw1 { get; set; }
        public Nullable<decimal> zstw2 { get; set; }
        public Nullable<decimal> zstw3 { get; set; }
        public Nullable<decimal> zgtw { get; set; }
        public Nullable<decimal> sgzh { get; set; }
        public string jg { get; set; }
        public string jyr { get; set; }
        public string fjr { get; set; }
    }
}
