//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_zbjl
    {
        public string sbh { get; set; }
        public decimal ypxh { get; set; }
        public string zjmc { get; set; }
        public Nullable<int> tlpb { get; set; }
        public Nullable<int> yflgy { get; set; }
        public Nullable<int> yflpb { get; set; }
        public Nullable<System.DateTime> yflrq { get; set; }
        public string zbgy { get; set; }
        public string bjcxm { get; set; }
        public string cjcxm { get; set; }
        public Nullable<System.DateTime> jcrq { get; set; }
        public Nullable<System.DateTime> zbrq { get; set; }
        public Nullable<int> djbz { get; set; }
        public Nullable<System.DateTime> djrq { get; set; }
        public Nullable<int> lybz { get; set; }
        public Nullable<System.DateTime> lyrq { get; set; }
        public Nullable<int> rkbz { get; set; }
        public Nullable<System.DateTime> rkrq { get; set; }
        public Nullable<decimal> zjsl { get; set; }
        public string zbbz { get; set; }
    }
}
