//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zy_bqjyyz
    {
        public decimal sbxh { get; set; }
        public decimal yzxh { get; set; }
        public decimal zyh { get; set; }
        public string zyhm { get; set; }
        public string brxm { get; set; }
        public decimal fyxh { get; set; }
        public string fymc { get; set; }
        public Nullable<decimal> jyks { get; set; }
        public System.DateTime kdsj { get; set; }
        public decimal kdks { get; set; }
        public string kdys { get; set; }
        public decimal zxpb { get; set; }
        public decimal jspb { get; set; }
        public decimal yepb { get; set; }
        public string bbbm { get; set; }
        public string zysx { get; set; }
        public System.DateTime tjsj { get; set; }
        public string tjgh { get; set; }
    }
}
