//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zy_cwtj
    {
        public decimal jlxh { get; set; }
        public Nullable<System.DateTime> czrq { get; set; }
        public Nullable<decimal> czlx { get; set; }
        public Nullable<decimal> zyh { get; set; }
        public Nullable<decimal> brks { get; set; }
        public Nullable<decimal> ysys { get; set; }
        public Nullable<decimal> xsys { get; set; }
        public Nullable<decimal> bqpb { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
