//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ZY_ERXX
    {
        public decimal JLXH { get; set; }
        public string ERID { get; set; }
        public decimal MQZYH { get; set; }
        public string ERXM { get; set; }
        public Nullable<decimal> ERXB { get; set; }
        public Nullable<decimal> ERTZ { get; set; }
        public Nullable<System.DateTime> CSRQ { get; set; }
        public Nullable<decimal> ZFPB { get; set; }
        public Nullable<decimal> SHBZ { get; set; }
        public string SHGH { get; set; }
    }
}
