//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ZY_ZYYJ
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public decimal ZYH { get; set; }
        public decimal ZJJE { get; set; }
        public decimal ZFJE { get; set; }
        public Nullable<System.DateTime> YJRQ { get; set; }
        public string YJR { get; set; }
        public Nullable<System.DateTime> HZRQ { get; set; }
        public decimal YJLX { get; set; }
        public decimal ZYLB { get; set; }
    }
}
