//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ZY_ZLXZ_BAK
    {
        public decimal JGID { get; set; }
        public decimal XZXH { get; set; }
        public string XZMC { get; set; }
        public Nullable<decimal> SSKS { get; set; }
    }
}
