//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zy_zyhs
    {
        public string hsrq { get; set; }
        public decimal hssf { get; set; }
        public decimal kjzd { get; set; }
        public decimal zyh { get; set; }
        public string zyhm { get; set; }
        public string brxm { get; set; }
        public string brch { get; set; }
        public decimal brxz { get; set; }
        public decimal zyks { get; set; }
        public decimal fyxm { get; set; }
        public decimal fyje { get; set; }
        public decimal zfje { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> HSXH { get; set; }
    }
}
