//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class BA_HQMS
    {
        public decimal ZYH { get; set; }
        public decimal JGID { get; set; }
        public Nullable<decimal> RYQK { get; set; }
        public string RYZD { get; set; }
        public Nullable<System.DateTime> QZRQ { get; set; }
        public Nullable<decimal> MCFH { get; set; }
        public Nullable<decimal> RCFH { get; set; }
        public Nullable<decimal> QHFH { get; set; }
        public Nullable<decimal> BLFH { get; set; }
        public Nullable<decimal> FSFH { get; set; }
        public Nullable<decimal> CTFH { get; set; }
        public Nullable<decimal> SJFH { get; set; }
        public Nullable<decimal> ZDYJ { get; set; }
        public Nullable<decimal> FHCD { get; set; }
        public string ICUMC { get; set; }
        public Nullable<System.DateTime> JRSJ { get; set; }
        public Nullable<System.DateTime> TCSJ { get; set; }
        public Nullable<decimal> TJHL { get; set; }
        public Nullable<decimal> YJHL { get; set; }
        public Nullable<decimal> EJHL { get; set; }
        public Nullable<decimal> SJHL { get; set; }
        public Nullable<decimal> HZLX { get; set; }
        public Nullable<decimal> HXJSY_D { get; set; }
        public Nullable<decimal> HXJSY_H { get; set; }
        public Nullable<decimal> HXJSY_M { get; set; }
        public Nullable<decimal> BYSL { get; set; }
        public Nullable<decimal> QJCS { get; set; }
        public Nullable<decimal> CGCS { get; set; }
        public Nullable<decimal> HBSAG { get; set; }
        public Nullable<decimal> HIVAB { get; set; }
        public Nullable<decimal> HCVAB { get; set; }
        public Nullable<decimal> SJBL { get; set; }
        public Nullable<decimal> GRCS { get; set; }
        public Nullable<decimal> SZPB { get; set; }
        public Nullable<decimal> SZZS { get; set; }
        public Nullable<decimal> SZYS { get; set; }
        public Nullable<decimal> SZNS { get; set; }
        public Nullable<decimal> CYQK { get; set; }
        public Nullable<decimal> QZTS { get; set; }
        public string RYZDBM { get; set; }
    }
}
