//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ba_zybz
    {
        public decimal tjyf { get; set; }
        public decimal flzh { get; set; }
        public string zybm { get; set; }
        public Nullable<decimal> cyrs { get; set; }
        public Nullable<decimal> cybr { get; set; }
        public Nullable<decimal> zycy { get; set; }
        public Nullable<decimal> hzcy { get; set; }
        public Nullable<decimal> wycy { get; set; }
        public Nullable<decimal> swcy { get; set; }
        public Nullable<decimal> qtcy { get; set; }
        public Nullable<decimal> zyts { get; set; }
        public Nullable<decimal> brts { get; set; }
        public Nullable<decimal> zyzl { get; set; }
        public Nullable<decimal> mcfh { get; set; }
        public Nullable<decimal> rcfh { get; set; }
        public Nullable<decimal> srqz { get; set; }
        public Nullable<decimal> wj1 { get; set; }
        public Nullable<decimal> wj2 { get; set; }
        public Nullable<decimal> wj3 { get; set; }
        public Nullable<decimal> sqts { get; set; }
        public Nullable<decimal> zyfy { get; set; }
        public Nullable<decimal> brfy { get; set; }
        public Nullable<decimal> zyf { get; set; }
        public Nullable<decimal> xyf { get; set; }
        public Nullable<decimal> zcy { get; set; }
        public Nullable<decimal> ccf { get; set; }
        public Nullable<decimal> ssf { get; set; }
        public Nullable<decimal> zlf { get; set; }
        public Nullable<decimal> jcf { get; set; }
        public Nullable<decimal> qtf { get; set; }
    }
}
