//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class bl_zk_bbsz
    {
        public string bbbh { get; set; }
        public decimal xmxh { get; set; }
        public Nullable<decimal> flag { get; set; }
        public string code { get; set; }
        public string xmmc { get; set; }
        public string lastcol { get; set; }
        public string xmgs { get; set; }
        public string alignment { get; set; }
        public string border { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
    }
}
