//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class BQ_HLHZ_ENR
    {
        public decimal SQDH { get; set; }
        public string SQHS { get; set; }
        public string SQKS { get; set; }
        public string YQDX { get; set; }
        public Nullable<System.DateTime> SQSJ { get; set; }
        public string XCG { get; set; }
        public string WBC { get; set; }
        public string PLT { get; set; }
        public string NXGN { get; set; }
        public string PT { get; set; }
        public string EJT { get; set; }
        public string HZMD { get; set; }
        public string CCFF { get; set; }
        public string CCCS { get; set; }
        public string JMYDJ { get; set; }
        public string DGQK { get; set; }
        public string WSYW { get; set; }
        public string WSFW { get; set; }
        public string SFSX { get; set; }
        public string SFSY { get; set; }
        public string GRQK { get; set; }
        public string BGQK { get; set; }
        public string QTMS { get; set; }
        public string QKMS { get; set; }
        public Nullable<System.DateTime> HZSJ { get; set; }
        public Nullable<decimal> ZFBZ { get; set; }
        public Nullable<decimal> JSBZ { get; set; }
        public Nullable<decimal> TJBZ { get; set; }
        public string JZHM { get; set; }
        public string TJHS { get; set; }
        public Nullable<System.DateTime> TJSJ { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public Nullable<decimal> HZLX { get; set; }
        public string HZYJ { get; set; }
        public string QMHS { get; set; }
        public Nullable<System.DateTime> QMSJ { get; set; }
        public decimal JGID { get; set; }
    }
}
