//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class BQ_JHZTBD
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public decimal JHXH { get; set; }
        public decimal YZXH { get; set; }
        public decimal YZZH { get; set; }
        public decimal ZYH { get; set; }
        public System.DateTime JHSJ { get; set; }
        public string YZT { get; set; }
        public string XZT { get; set; }
        public string BHYY { get; set; }
        public string CZR { get; set; }
        public string CZKHD { get; set; }
        public System.DateTime CZSJ { get; set; }
    }
}
