//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class BQ_TKZL
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public decimal ZYH { get; set; }
        public Nullable<decimal> SQKS { get; set; }
        public Nullable<decimal> SQBQ { get; set; }
        public string SQGH { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public Nullable<decimal> ZLKS { get; set; }
        public Nullable<decimal> ZLBQ { get; set; }
        public string ZLYS { get; set; }
        public Nullable<System.DateTime> QSRQ { get; set; }
        public Nullable<System.DateTime> ZZRQ { get; set; }
        public Nullable<decimal> ZXBZ { get; set; }
        public string JSGH { get; set; }
        public Nullable<System.DateTime> JSRQ { get; set; }
        public string WCGH { get; set; }
        public Nullable<System.DateTime> WCRQ { get; set; }
        public Nullable<decimal> ZFPB { get; set; }
        public string ZFGH { get; set; }
        public Nullable<System.DateTime> ZFRQ { get; set; }
        public string BZXX { get; set; }
    }
}
