//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class bq_yzdy
    {
        public decimal zyh { get; set; }
        public decimal yzlx { get; set; }
        public decimal jlxh { get; set; }
        public decimal dyhh { get; set; }
        public decimal dyyh { get; set; }
        public string TZYS { get; set; }
        public string CZGH { get; set; }
        public string YSGH { get; set; }
        public string DYNR { get; set; }
        public string BZXX { get; set; }
        public string FHGH { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<System.DateTime> QRSJ { get; set; }
        public Nullable<System.DateTime> TZSJ { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public Nullable<decimal> SRKS { get; set; }
        public Nullable<decimal> XH { get; set; }
    }
}
