//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class BQ_YZJH
    {
        public decimal JHH { get; set; }
        public decimal JGID { get; set; }
        public decimal GSLX { get; set; }
        public decimal LXH { get; set; }
        public decimal ZYH { get; set; }
        public decimal BRBQ { get; set; }
        public decimal YZZH { get; set; }
        public Nullable<decimal> YSYZBH { get; set; }
        public decimal YZXH { get; set; }
        public Nullable<decimal> XMLX { get; set; }
        public Nullable<decimal> XMXH { get; set; }
        public decimal YZZX { get; set; }
        public string YZMC { get; set; }
        public Nullable<decimal> YPYF { get; set; }
        public string SYPC { get; set; }
        public Nullable<decimal> YCJL { get; set; }
        public string JLDW { get; set; }
        public Nullable<decimal> YCSL { get; set; }
        public string SLDW { get; set; }
        public System.DateTime JHRQ { get; set; }
        public System.DateTime JHSJ { get; set; }
        public decimal JHSD { get; set; }
        public System.DateTime CSSJ { get; set; }
        public decimal ZFBZ { get; set; }
        public Nullable<decimal> QRBZ { get; set; }
        public Nullable<decimal> QRDH { get; set; }
        public decimal ZXZT { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public string KSGH { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public string JSGH { get; set; }
        public Nullable<decimal> KPDYXH { get; set; }
        public Nullable<decimal> ZXDDYXH { get; set; }
        public Nullable<decimal> JHLX { get; set; }
        public decimal FJLX { get; set; }
        public Nullable<decimal> TJYF { get; set; }
        public decimal TZBZ { get; set; }
        public decimal QFBZ { get; set; }
        public decimal QYBZ { get; set; }
        public decimal YPZT { get; set; }
        public decimal YJZT { get; set; }
        public decimal XMZT { get; set; }
        public decimal LSBZ { get; set; }
        public string BZXX { get; set; }
        public string CZR { get; set; }
        public string CZKHD { get; set; }
        public Nullable<decimal> YEPB { get; set; }
        public decimal TBBZ { get; set; }
        public string TMBH { get; set; }
        public decimal JPBZ { get; set; }
        public Nullable<decimal> LSYZ { get; set; }
        public Nullable<decimal> SJBH { get; set; }
        public string SJMC { get; set; }
        public Nullable<decimal> SRHDBZ { get; set; }
        public string KSHDGH { get; set; }
        public Nullable<System.DateTime> KSHDSJ { get; set; }
        public Nullable<System.DateTime> JSHDSJ { get; set; }
        public string JSHDGH { get; set; }
        public Nullable<System.DateTime> ZQRQ { get; set; }
        public Nullable<decimal> ZXLX { get; set; }
        public string ZXZD { get; set; }
        public Nullable<decimal> ZDLX { get; set; }
        public Nullable<decimal> ZXWZ { get; set; }
        public Nullable<decimal> GLJHH { get; set; }
    }
}
