//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_BGRZ
    {
        public decimal RZXH { get; set; }
        public decimal BRLJ { get; set; }
        public decimal CZLB { get; set; }
        public Nullable<System.DateTime> CPRYR { get; set; }
        public Nullable<System.DateTime> CPSSR { get; set; }
        public Nullable<System.DateTime> CPCYR { get; set; }
        public string CZGH { get; set; }
        public System.DateTime CZSJ { get; set; }
        public string BGGH { get; set; }
        public System.DateTime BGSJ { get; set; }
        public decimal BYXH { get; set; }
        public decimal LJBH { get; set; }
    }
}
