//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_BZZK3_STK
    {
        public decimal JLXH { get; set; }
        public string PAT_ZDBM_1_I { get; set; }
        public string PAT_ZDMC_1_I { get; set; }
        public string PAT_ZDBM_1_II { get; set; }
        public string PAT_ZDMC_1_II { get; set; }
        public string PAT_ZDBM_2_I { get; set; }
        public string PAT_ZDMC_2_I { get; set; }
        public string PAT_ZDBM_2_II { get; set; }
        public string PAT_ZDMC_2_II { get; set; }
        public string PAT_SSBM { get; set; }
        public string PAT_SSMC { get; set; }
        public string PAT_ZYHM { get; set; }
        public string PAT_BAHM { get; set; }
        public Nullable<System.DateTime> PAT_CSRQ { get; set; }
        public string PAT_ZFFS { get; set; }
        public string PAT_RYTJ { get; set; }
        public string PAT_JTGJ { get; set; }
        public Nullable<System.DateTime> PAT_FBSJ { get; set; }
        public Nullable<System.DateTime> PAT_DDSJ { get; set; }
        public Nullable<System.DateTime> PAT_RYRQ { get; set; }
        public Nullable<System.DateTime> PAT_ZRSJ { get; set; }
        public Nullable<System.DateTime> PAT_SSKS { get; set; }
        public Nullable<System.DateTime> PAT_SSJS { get; set; }
        public Nullable<System.DateTime> PAT_CYRQ { get; set; }
        public Nullable<decimal> PAT_ZYFY { get; set; }
        public Nullable<decimal> PAT_YF { get; set; }
        public Nullable<decimal> PAT_ZYTS { get; set; }
        public string PAT_ZLJG { get; set; }
        public string PAT_CYQX { get; set; }
        public string STK_1_1 { get; set; }
        public Nullable<System.DateTime> STK_1_1_1 { get; set; }
        public string STK_1_2 { get; set; }
        public Nullable<decimal> STK_1_2_1 { get; set; }
        public Nullable<decimal> STK_1_2_2 { get; set; }
        public string STK_1_3 { get; set; }
        public Nullable<decimal> STK_1_3_1 { get; set; }
        public Nullable<decimal> STK_1_3_2 { get; set; }
        public string STK_1_4 { get; set; }
        public Nullable<System.DateTime> STK_1_4_1 { get; set; }
        public Nullable<System.DateTime> STK_1_4_2 { get; set; }
        public string STK_1_5 { get; set; }
        public Nullable<System.DateTime> STK_1_5_1 { get; set; }
        public Nullable<System.DateTime> STK_1_5_2 { get; set; }
        public Nullable<decimal> STK_1_5_3 { get; set; }
        public Nullable<decimal> STK_1_5_4 { get; set; }
        public string STK_1_6 { get; set; }
        public Nullable<System.DateTime> STK_1_6_1 { get; set; }
        public Nullable<System.DateTime> STK_1_6_2 { get; set; }
        public string STK_1_6_3 { get; set; }
        public string STK_2_1 { get; set; }
        public Nullable<decimal> STK_2_1_1 { get; set; }
        public string STK_2_2_1 { get; set; }
        public string STK_2_2_2 { get; set; }
        public string STK_2_2_3 { get; set; }
        public string STK_2_2_4 { get; set; }
        public string STK_2_2_5 { get; set; }
        public string STK_2_3 { get; set; }
        public string STK_2_3_1 { get; set; }
        public string STK_2_4 { get; set; }
        public string STK_2_5 { get; set; }
        public Nullable<System.DateTime> STK_2_6 { get; set; }
        public string STK_2_6_1 { get; set; }
        public string STK_2_8_1 { get; set; }
        public Nullable<decimal> STK_2_8_1_1 { get; set; }
        public string STK_2_8_2 { get; set; }
        public Nullable<decimal> STK_2_8_2_1 { get; set; }
        public string STK_2_8_3 { get; set; }
        public string STK_2_8_3_1 { get; set; }
        public string STK_2_8_3_2 { get; set; }
        public string STK_2_9 { get; set; }
        public string STK_3_1 { get; set; }
        public string STK_3_2 { get; set; }
        public string STK_3_3 { get; set; }
        public string STK_3_3_1 { get; set; }
        public string STK_3_4 { get; set; }
        public string STK_3_4_1 { get; set; }
        public string STK_3_5 { get; set; }
        public string STK_3_5_1 { get; set; }
        public string STK_4 { get; set; }
        public string STK_4_1 { get; set; }
        public string STK_4_1_0 { get; set; }
        public string STK_4_2A { get; set; }
        public string STK_4_2 { get; set; }
        public string STK_4_3 { get; set; }
        public string STK_5 { get; set; }
        public string STK_5_1 { get; set; }
        public string STK_5_2 { get; set; }
        public string STK_5_2_0 { get; set; }
        public string STK_5_3 { get; set; }
        public string STK_5_4 { get; set; }
        public string STK_6_1 { get; set; }
        public string STK_6_2 { get; set; }
        public string STK_6_3 { get; set; }
        public string STK_6_4 { get; set; }
        public string STK_6_5 { get; set; }
        public string STK_7_1 { get; set; }
        public string STK_7_1_1 { get; set; }
        public string STK_7_2 { get; set; }
        public string STK_7_2_1 { get; set; }
        public string STK_7_2_2 { get; set; }
        public string STK_7_2_3 { get; set; }
        public string STK_7_2_4 { get; set; }
        public string STK_8_1 { get; set; }
        public Nullable<System.DateTime> STK_9_1_1 { get; set; }
        public string STK_9_1_2 { get; set; }
        public string STK_9_1_3 { get; set; }
        public string STK_9_1_4 { get; set; }
        public string STK_9_1_5 { get; set; }
        public Nullable<decimal> STK_9_1_6 { get; set; }
        public string STK_9_1_7 { get; set; }
        public string STK_9_1_8 { get; set; }
        public Nullable<System.DateTime> STK_9_1_9 { get; set; }
        public Nullable<System.DateTime> STK_9_1_10 { get; set; }
        public Nullable<decimal> STK_9_1_11 { get; set; }
        public string STK_9_1 { get; set; }
        public string STK_9_1_0 { get; set; }
        public string STK_9_2 { get; set; }
        public string STK_9_3A { get; set; }
        public string STK_9_3 { get; set; }
        public string STK_9_4 { get; set; }
        public string STK_9_5 { get; set; }
        public string STK_9_6 { get; set; }
        public string STK_10_1 { get; set; }
        public string STK_10_1_1 { get; set; }
        public string STK_10_1_2 { get; set; }
        public Nullable<decimal> STK_11_3_1 { get; set; }
        public Nullable<decimal> STK_11_3_2 { get; set; }
        public string STK_11_4 { get; set; }
        public string STK_11_4_1 { get; set; }
        public Nullable<System.DateTime> STK_11_4_2 { get; set; }
        public string STK_11_4_3 { get; set; }
        public string STK_11_4_4 { get; set; }
        public string STK_11_5 { get; set; }
        public string STK_11_5_0 { get; set; }
        public string STK_11_7 { get; set; }
        public Nullable<decimal> STK_11_7_1 { get; set; }
        public string STK_12_1 { get; set; }
        public string STK_12_2 { get; set; }
        public string STK_12_3 { get; set; }
        public string STK_12_4 { get; set; }
        public string STK_12_5 { get; set; }
        public string STK_12_6 { get; set; }
        public string STK_12_7 { get; set; }
        public string STK_12_8 { get; set; }
        public string STK_13_1 { get; set; }
        public string STK_13_2_1 { get; set; }
        public string STK_13_2_1_0 { get; set; }
        public string STK_13_2_2 { get; set; }
        public string STK_13_3 { get; set; }
    }
}
