//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_BZZK3_AMI
    {
        public string PAT_ZDBM_1_I { get; set; }
        public string PAT_ZDMC_1_I { get; set; }
        public string PAT_ZDBM_1_II { get; set; }
        public string PAT_ZDMC_1_II { get; set; }
        public string PAT_ZDBM_2_I { get; set; }
        public string PAT_ZDMC_2_I { get; set; }
        public string PAT_ZDBM_2_II { get; set; }
        public string PAT_ZDMC_2_II { get; set; }
        public string PAT_SSBM { get; set; }
        public string PAT_SSMC { get; set; }
        public string PAT_SSBM_0 { get; set; }
        public string PAT_ZYHM { get; set; }
        public string PAT_BAHM { get; set; }
        public Nullable<System.DateTime> PAT_CSRQ { get; set; }
        public string PAT_ZFFS { get; set; }
        public string PAT_RYTJ { get; set; }
        public string PAT_JTGJ { get; set; }
        public Nullable<System.DateTime> PAT_FBSJ { get; set; }
        public string PAT_DDLX { get; set; }
        public Nullable<System.DateTime> PAT_DDSJ { get; set; }
        public Nullable<System.DateTime> PAT_RYRQ { get; set; }
        public Nullable<System.DateTime> PAT_SSKS { get; set; }
        public Nullable<System.DateTime> PAT_SSJS { get; set; }
        public Nullable<System.DateTime> PAT_CYRQ { get; set; }
        public string PAT_ZLJG { get; set; }
        public string PAT_CYQX { get; set; }
        public Nullable<decimal> PAT_ZYFY { get; set; }
        public Nullable<decimal> PAT_YF { get; set; }
        public Nullable<decimal> PAT_ZYTS { get; set; }
        public string AMI_0_12 { get; set; }
        public string AMI_0_12_0 { get; set; }
        public Nullable<System.DateTime> AMI_0_4_10 { get; set; }
        public decimal JLXH { get; set; }
        public string AMI_1_1 { get; set; }
        public string AMI_1_2 { get; set; }
        public Nullable<System.DateTime> AMI_1_2_1 { get; set; }
        public string AMI_1_3 { get; set; }
        public Nullable<System.DateTime> AMI_1_3_1 { get; set; }
        public string AMI_1_4 { get; set; }
        public Nullable<System.DateTime> AMI_1_4_1 { get; set; }
        public string AMI_1_5 { get; set; }
        public Nullable<System.DateTime> AMI_1_5_1 { get; set; }
        public string AMI_1_6 { get; set; }
        public Nullable<System.DateTime> AMI_1_6_1 { get; set; }
        public string AMI_1_6_2 { get; set; }
        public Nullable<decimal> AMI_1_6_2_1 { get; set; }
        public string AMI_2 { get; set; }
        public string AMI_YY { get; set; }
        public string AMI_2_0 { get; set; }
        public string AMI_2_0_1 { get; set; }
        public Nullable<System.DateTime> AMI_2_0_2 { get; set; }
        public Nullable<System.DateTime> AMI_2_0_3 { get; set; }
        public Nullable<System.DateTime> AMI_2_0_4 { get; set; }
        public string AMI_2_1 { get; set; }
        public string AMI_2_2 { get; set; }
        public Nullable<decimal> AMI_2_2_1 { get; set; }
        public Nullable<decimal> AMI_2_2_2 { get; set; }
        public string AMI_2_2_3 { get; set; }
        public string AMI_2_2_4 { get; set; }
        public Nullable<decimal> AMI_2_2_5 { get; set; }
        public Nullable<System.DateTime> AMI_2_2_7 { get; set; }
        public string AMI_2_3 { get; set; }
        public Nullable<System.DateTime> AMI_2_3_0 { get; set; }
        public string AMI_2_3_1 { get; set; }
        public string AMI_2_3_2 { get; set; }
        public string AMI_2_3_3 { get; set; }
        public string AMI_2_3_4 { get; set; }
        public string AMI_2_3_5 { get; set; }
        public string AMI_2_4 { get; set; }
        public Nullable<System.DateTime> AMI_2_4_1 { get; set; }
        public string AMI_2_4_2 { get; set; }
        public string AMI_2_4_2_0 { get; set; }
        public Nullable<decimal> AMI_2_4_2_00 { get; set; }
        public string AMI_4_1 { get; set; }
        public Nullable<System.DateTime> AMI_4_1_1 { get; set; }
        public string AMI_4_1_2 { get; set; }
        public string AMI_4_1_3 { get; set; }
        public string AMI_5_1 { get; set; }
        public string AMI_5_2 { get; set; }
        public string AMI_5_3 { get; set; }
        public string AMI_5_4 { get; set; }
        public string AMI_5_5 { get; set; }
        public string AMI_6_1 { get; set; }
        public string AMI_6_2 { get; set; }
        public string AMI_6_3 { get; set; }
        public string AMI_6_4 { get; set; }
        public string AMI_6_5 { get; set; }
        public string AMI_7_1 { get; set; }
        public string AMI_7_2 { get; set; }
        public string AMI_7_3 { get; set; }
        public string AMI_8_3 { get; set; }
        public string AMI_8_3_1 { get; set; }
        public string AMI_8_3_1_0 { get; set; }
        public string AMI_8_3_2 { get; set; }
        public string AMI_8_3_2_0 { get; set; }
        public string AMI_9_1 { get; set; }
        public string AMI_9_2 { get; set; }
        public string AMI_9_3 { get; set; }
        public string AMI_9_4 { get; set; }
        public string AMI_9_5 { get; set; }
        public string AMI_9_6 { get; set; }
        public string AMI_9_7 { get; set; }
        public string AMI_9_8 { get; set; }
        public Nullable<System.DateTime> PAT_ZRSJ { get; set; }
        public string AMI_3_1 { get; set; }
        public Nullable<System.DateTime> AMI_3_1_1_1 { get; set; }
        public string AMI_3_1_1_2 { get; set; }
        public string AMI_3_1_1_3 { get; set; }
        public string AMI_3_1_1_4 { get; set; }
        public string AMI_3_1_2 { get; set; }
        public string AMI_3_1_2_0 { get; set; }
        public string AMI_3_1_3 { get; set; }
        public string AMI_3_2 { get; set; }
        public string AMI_3_2_1 { get; set; }
        public string AMI_3_2_3 { get; set; }
        public string AMI_3_2_2 { get; set; }
        public string AMI_3_2_3_1 { get; set; }
        public string AMI_3_2_3_2 { get; set; }
        public string AMI_3_2_4 { get; set; }
        public string AMI_3_2_5 { get; set; }
        public string AMI_3_2_5_0 { get; set; }
        public string AMI_3_2_6 { get; set; }
        public string AMI_3_2_7 { get; set; }
        public string AMI_3_2_7_0 { get; set; }
        public string AMI_3_2_8 { get; set; }
        public string AMI_3_2_8_0 { get; set; }
        public Nullable<System.DateTime> AMI_3_2_9 { get; set; }
        public Nullable<System.DateTime> AMI_3_2_10 { get; set; }
        public string AMI_3_3 { get; set; }
        public string AMI_3_3_1_1 { get; set; }
        public string AMI_3_3_2 { get; set; }
        public Nullable<System.DateTime> AMI_3_3_2_1 { get; set; }
        public string AMI_3_3_1_2 { get; set; }
    }
}
