//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_BZZK3_CAP2
    {
        public decimal JLXH { get; set; }
        public string PAT_ZDBM_1_I { get; set; }
        public string PAT_ZDMC_1_I { get; set; }
        public string PAT_ZDBM_1_II { get; set; }
        public string PAT_ZDMC_1_II { get; set; }
        public string PAT_ZDBM_2_I { get; set; }
        public string PAT_ZDMC_2_I { get; set; }
        public string PAT_ZDBM_2_II { get; set; }
        public string PAT_ZDMC_2_II { get; set; }
        public string PAT_SSBM { get; set; }
        public string PAT_SSMC { get; set; }
        public string PAT_ZYHM { get; set; }
        public string PAT_BAHM { get; set; }
        public Nullable<System.DateTime> PAT_CSRQ { get; set; }
        public string PAT_ZFFS { get; set; }
        public string PAT_RYTJ { get; set; }
        public string PAT_JTGJ { get; set; }
        public Nullable<System.DateTime> PAT_FBSJ { get; set; }
        public Nullable<System.DateTime> PAT_DDSJ { get; set; }
        public Nullable<System.DateTime> PAT_RYRQ { get; set; }
        public Nullable<System.DateTime> PAT_ZRSJ { get; set; }
        public Nullable<System.DateTime> PAT_SSKS { get; set; }
        public Nullable<System.DateTime> PAT_SSJS { get; set; }
        public Nullable<System.DateTime> PAT_CYRQ { get; set; }
        public Nullable<decimal> PAT_ZYFY { get; set; }
        public Nullable<decimal> PAT_YF { get; set; }
        public Nullable<decimal> PAT_ZYTS { get; set; }
        public string PAT_ZLJG { get; set; }
        public string PAT_CYQX { get; set; }
        public string CAP2_1 { get; set; }
        public string CAP2_1_1 { get; set; }
        public string CAP2_1_1_0 { get; set; }
        public string CAP2_1_2 { get; set; }
        public string CAP2_1_2_0 { get; set; }
        public string CAP2_2_1 { get; set; }
        public Nullable<System.DateTime> CAP2_2_2 { get; set; }
        public Nullable<decimal> CAP2_2_3 { get; set; }
        public Nullable<decimal> CAP2_2_4 { get; set; }
        public Nullable<decimal> CAP2_2_5 { get; set; }
        public string CAP2_3_1 { get; set; }
        public string CAP2_3_2 { get; set; }
        public string CAP2_3_2_1 { get; set; }
        public string CAP2_4_1 { get; set; }
        public Nullable<System.DateTime> CAP2_4_1_1 { get; set; }
        public string CAP2_4_2 { get; set; }
        public Nullable<decimal> CAP2_4_2_1 { get; set; }
        public Nullable<decimal> CAP2_4_2_2 { get; set; }
        public string CAP2_5_1 { get; set; }
        public string CAP2_5_1_0 { get; set; }
        public string CAP2_5_2 { get; set; }
        public string CAP2_5_2_0 { get; set; }
        public string CAP2_6_1 { get; set; }
        public string CAP2_6_2 { get; set; }
        public string CAP2_7_1 { get; set; }
        public string CAP2_7_1_0 { get; set; }
        public string CAP2_8_1 { get; set; }
        public string CAP2_9_1 { get; set; }
        public string CAP2_9_2 { get; set; }
        public string CAP2_9_3 { get; set; }
        public string CAP2_9_4 { get; set; }
        public string CAP2_9_5 { get; set; }
        public string CAP2_9_6 { get; set; }
        public string CAP2_9_7 { get; set; }
        public string CAP2_9_8 { get; set; }
    }
}
