//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_YZMX
    {
        public decimal MXID { get; set; }
        public decimal ZXXH { get; set; }
        public Nullable<decimal> BRLJ { get; set; }
        public decimal XMLB { get; set; }
        public decimal XMDM { get; set; }
        public string XMMC { get; set; }
        public Nullable<decimal> YPCD { get; set; }
        public Nullable<decimal> YCSL { get; set; }
        public string SLDW { get; set; }
        public Nullable<decimal> GYTJ { get; set; }
        public string SYPC { get; set; }
        public decimal YZZH { get; set; }
        public string YSYZBH { get; set; }
        public decimal BXBZ { get; set; }
        public Nullable<decimal> XXXZ { get; set; }
        public decimal YZZT { get; set; }
        public Nullable<decimal> PLSX { get; set; }
        public Nullable<System.DateTime> KZSJ { get; set; }
        public Nullable<System.DateTime> TZSJ { get; set; }
        public Nullable<decimal> HDQX { get; set; }
        public Nullable<decimal> YSXM { get; set; }
        public Nullable<decimal> FZLJ { get; set; }
        public string BZXX { get; set; }
    }
}
