//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class CP_ZLLJ
    {
        public decimal LJBH { get; set; }
        public string LJMC { get; set; }
        public Nullable<decimal> BLFX { get; set; }
        public Nullable<decimal> BZZYR { get; set; }
        public Nullable<decimal> ZYTZ { get; set; }
        public Nullable<decimal> ZZSSR { get; set; }
        public decimal SSTZ { get; set; }
        public Nullable<decimal> LJZT { get; set; }
        public decimal BZBH { get; set; }
        public Nullable<decimal> CKXX { get; set; }
        public Nullable<decimal> CKSX { get; set; }
        public Nullable<System.DateTime> XGSJ { get; set; }
        public decimal JGID { get; set; }
    }
}
