//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class DX_YSXX
    {
        public decimal JSXH { get; set; }
        public decimal JGID { get; set; }
        public Nullable<decimal> GLXH { get; set; }
        public string DXDM { get; set; }
        public string DXNR { get; set; }
        public Nullable<decimal> SFJE { get; set; }
        public Nullable<System.DateTime> FSSJ { get; set; }
        public string FSHM { get; set; }
        public string FSRM { get; set; }
        public string JSHM { get; set; }
        public string JSRM { get; set; }
        public string KHID { get; set; }
    }
}
