//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class dz_gqjl
    {
        public decimal gqid { get; set; }
        public decimal dzth { get; set; }
        public decimal dzid { get; set; }
        public decimal brid { get; set; }
        public string brxm { get; set; }
        public string ksdm { get; set; }
        public string ysdm { get; set; }
        public System.DateTime gqsj { get; set; }
        public string gqyy { get; set; }
        public Nullable<System.DateTime> hfsj { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        public virtual dz_dzjl dz_dzjl { get; set; }
    }
}
