//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EA_WZQJ_WZDJ
    {
        public decimal JLXH { get; set; }
        public string JZHM { get; set; }
        public string BRBH { get; set; }
        public string BRXM { get; set; }
        public decimal BRKS { get; set; }
        public Nullable<decimal> KSFSXX { get; set; }
        public string KSFSGH { get; set; }
        public Nullable<System.DateTime> KSFSRQ { get; set; }
        public string YXBJSGH { get; set; }
        public Nullable<System.DateTime> YXBJSRQ { get; set; }
        public Nullable<decimal> YXBFSXX { get; set; }
        public string YXBFSGH { get; set; }
        public Nullable<System.DateTime> YXBFSRQ { get; set; }
        public string YWBJSGH { get; set; }
        public Nullable<System.DateTime> YWBJSRQ { get; set; }
        public Nullable<decimal> YWBFSXX { get; set; }
        public string YWBFSGH { get; set; }
        public Nullable<System.DateTime> YWBFSRQ { get; set; }
        public string YZJSGH { get; set; }
        public Nullable<System.DateTime> YZJSRQ { get; set; }
        public decimal JGID { get; set; }
    }
}
