//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EA_XJS_ZJ
    {
        public decimal JLXH { get; set; }
        public string XMMC { get; set; }
        public string ZJKS { get; set; }
        public string XMFZR { get; set; }
        public System.DateTime XMKZSJ { get; set; }
        public System.DateTime XMZJSJ { get; set; }
        public Nullable<decimal> KZBLS { get; set; }
        public string KSPJ { get; set; }
        public string QTWT { get; set; }
        public string ZJZYJ { get; set; }
        public string YWBPJ { get; set; }
        public decimal DJZT { get; set; }
        public System.DateTime ZJRQ { get; set; }
        public decimal JGID { get; set; }
    }
}
