//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EA_XJS_YYSF
    {
        public decimal JLXH { get; set; }
        public decimal ZYH { get; set; }
        public string JZHM { get; set; }
        public string BRZD { get; set; }
        public string XJSMC { get; set; }
        public string XMFZR { get; set; }
        public string SFQK { get; set; }
        public string SFYS { get; set; }
        public string KZRYJ { get; set; }
        public System.DateTime SFRQ { get; set; }
        public string BRXM { get; set; }
        public decimal BRKS { get; set; }
        public decimal DJZT { get; set; }
        public decimal JGID { get; set; }
    }
}
