//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_TZKJ
    {
        public decimal KJBH { get; set; }
        public Nullable<decimal> TZBH { get; set; }
        public Nullable<decimal> TZLB { get; set; }
        public decimal KJLX { get; set; }
        public decimal KJCD { get; set; }
        public string KJNR { get; set; }
        public decimal SZBZ { get; set; }
        public Nullable<decimal> XSSX { get; set; }
        public string KJSM { get; set; }
        public decimal JGID { get; set; }
    }
}
