//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_GGWSSJ
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string JZYY { get; set; }
        public Nullable<System.DateTime> SJ { get; set; }
        public Nullable<System.DateTime> JHCSJ { get; set; }
        public Nullable<System.DateTime> HBSJ { get; set; }
        public string HBBM { get; set; }
        public string JZGH { get; set; }
        public Nullable<System.DateTime> KSHJQK1_HJSJ { get; set; }
        public Nullable<System.DateTime> KSHJQK1_DDSJ { get; set; }
        public Nullable<decimal> KSHJQK1_KS { get; set; }
        public string KSHJQK1_TEXT { get; set; }
        public Nullable<System.DateTime> KSHJQK2_HJSJ { get; set; }
        public Nullable<System.DateTime> KSHJQK2_DDSJ { get; set; }
        public Nullable<decimal> KSHJQK2_KS { get; set; }
        public string KSHJQK2_TEXT { get; set; }
        public Nullable<System.DateTime> KSHJQK3_HJSJ { get; set; }
        public Nullable<System.DateTime> KSHJQK3_DDSJ { get; set; }
        public Nullable<decimal> KSHJQK3_KS { get; set; }
        public string KSHJQK3_TEXT { get; set; }
        public Nullable<System.DateTime> KSHJQK4_HJSJ { get; set; }
        public Nullable<System.DateTime> KSHJQK4_DDSJ { get; set; }
        public Nullable<decimal> KSHJQK4_KS { get; set; }
        public string KSHJQK4_TEXT { get; set; }
        public Nullable<System.DateTime> KSHJQK5_HJSJ { get; set; }
        public Nullable<System.DateTime> KSHJQK5_DDSJ { get; set; }
        public Nullable<decimal> KSHJQK5_KS { get; set; }
        public string KSHJQK5_TEXT { get; set; }
        public decimal JGID { get; set; }
    }
}
