//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_YJFZ_XT
    {
        public decimal JLXH { get; set; }
        public Nullable<decimal> BRID { get; set; }
        public Nullable<decimal> FZXH { get; set; }
        public decimal JGID { get; set; }
        public string GWPG { get; set; }
        public string GWPG_0 { get; set; }
        public Nullable<decimal> WSS { get; set; }
        public string JWBS { get; set; }
        public string JWBS_0 { get; set; }
        public string TTYS { get; set; }
        public string TTYS_0 { get; set; }
        public string TTGJ { get; set; }
        public string TTGJ_0 { get; set; }
        public string TTBW { get; set; }
        public string TTBW_0 { get; set; }
        public string FSBW { get; set; }
        public string FSBW_0 { get; set; }
        public string CXSJ { get; set; }
        public string HJFS { get; set; }
        public string HJFS_0 { get; set; }
    }
}
