//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_YJFZ_QT
    {
        public decimal JLXH { get; set; }
        public Nullable<decimal> BRID { get; set; }
        public Nullable<decimal> FZXH { get; set; }
        public decimal JGID { get; set; }
        public string CXQK { get; set; }
        public string CXQK_0 { get; set; }
        public string CXXG { get; set; }
        public string PLT9 { get; set; }
        public string HB { get; set; }
        public string HBJMX { get; set; }
        public string HBJMX_0 { get; set; }
        public string XXNT { get; set; }
        public string XXNT_0 { get; set; }
        public string QTBX { get; set; }
        public string QTBX_0 { get; set; }
        public string FBSJ { get; set; }
        public string FBSJ_0 { get; set; }
        public string FZXT { get; set; }
        public string FZXT_0 { get; set; }
        public string FZHZT { get; set; }
        public string FZHZT_0 { get; set; }
        public string YSZT { get; set; }
        public string FZZZ { get; set; }
        public string FZZZ_0 { get; set; }
        public string QTZZ { get; set; }
        public string QTZZ_0 { get; set; }
        public string TS { get; set; }
        public string YCS { get; set; }
        public string BFZ { get; set; }
        public string BFZ_0 { get; set; }
        public string CL { get; set; }
        public string CL_0 { get; set; }
        public string RSXY24Z { get; set; }
        public string YJBT { get; set; }
        public string FT { get; set; }
        public string BFZQT { get; set; }
        public string BFZQT_0 { get; set; }
        public string TNBBS { get; set; }
        public string XTS { get; set; }
        public string BSZT { get; set; }
        public string BSZT_0 { get; set; }
        public string GMJCS { get; set; }
        public string GMJCS_0 { get; set; }
        public string GMZZ { get; set; }
        public string GMZZ_0 { get; set; }
        public string YJBZ { get; set; }
        public string YJBZ_0 { get; set; }
        public string YJZZ { get; set; }
        public string YJZZ_0 { get; set; }
        public string YJQT { get; set; }
        public string JSXZZ { get; set; }
        public string JSXZZ_0 { get; set; }
        public string SJXZZ { get; set; }
        public string SJXZZ_0 { get; set; }
        public string H { get; set; }
        public string H_0 { get; set; }
        public string B { get; set; }
        public string B_0 { get; set; }
        public string E { get; set; }
        public string E_0 { get; set; }
        public string KQZZ { get; set; }
        public string KQZZ_0 { get; set; }
        public string BYHCX { get; set; }
        public string JXNZL { get; set; }
        public string XN { get; set; }
        public string XN_0 { get; set; }
        public string MNZZ { get; set; }
        public string MNZZ_0 { get; set; }
        public string ZD { get; set; }
        public string ZD_0 { get; set; }
        public string DJSZZ { get; set; }
        public string DJSZZ_0 { get; set; }
        public string CS { get; set; }
        public string CS_0 { get; set; }
        public string QT { get; set; }
    }
}
