//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ECIS_LCSJ
    {
        public decimal SJBH { get; set; }
        public decimal JZXH { get; set; }
        public decimal FZXH { get; set; }
        public decimal SJ { get; set; }
        public System.DateTime SJSJ { get; set; }
        public string SJMS { get; set; }
        public string JLGH { get; set; }
        public System.DateTime JLSJ { get; set; }
        public decimal JZLX { get; set; }
        public decimal ZF { get; set; }
        public decimal JGID { get; set; }
    }
}
