//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_bl_blsy
    {
        public decimal jlxh { get; set; }
        public decimal blbh { get; set; }
        public decimal syqx { get; set; }
        public string syys { get; set; }
        public System.DateTime sysj { get; set; }
        public System.DateTime jlsj { get; set; }
        public string bzxx { get; set; }
        public Nullable<decimal> qxjb { get; set; }
        public Nullable<decimal> qmlx { get; set; }
        public Nullable<decimal> qmlsh { get; set; }
        public string dllj { get; set; }
        public string qmys { get; set; }
        public string ysmrz { get; set; }
        public string qmysz { get; set; }
        public Nullable<decimal> zjbj { get; set; }
        public Nullable<decimal> glxh { get; set; }
    }
}
