//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_dmzd
    {
        public decimal dmlb { get; set; }
        public decimal dmsb { get; set; }
        public string dmmc { get; set; }
        public string ywmc { get; set; }
        public string pydm { get; set; }
        public string wbdm { get; set; }
        public string jxdm { get; set; }
        public string qtdm { get; set; }
        public decimal plsx { get; set; }
        public Nullable<decimal> sjdm { get; set; }
        public string txid { get; set; }
    }
}
