//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_wh_cxjmmx
    {
        public decimal jlxh { get; set; }
        public decimal jmxh { get; set; }
        public decimal xslh { get; set; }
        public decimal xmxh { get; set; }
        public string xsmc { get; set; }
        public decimal dqfs { get; set; }
        public decimal xskd { get; set; }
    
        public virtual emr_wh_cxjm emr_wh_cxjm { get; set; }
    }
}
