//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_sjy
    {
        public decimal sjyid { get; set; }
        public string bzbm { get; set; }
        public string sjymc { get; set; }
        public string szdw { get; set; }
        public string sjydy { get; set; }
        public decimal sjlx { get; set; }
        public decimal sjcd { get; set; }
        public decimal sjjd { get; set; }
        public decimal btx { get; set; }
        public decimal xtbl { get; set; }
        public string pydm { get; set; }
    }
}
