//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_apache
    {
        public decimal pfxh { get; set; }
        public decimal zyh { get; set; }
        public decimal pfks { get; set; }
        public string pfys { get; set; }
        public System.DateTime pfrq { get; set; }
        public decimal zf { get; set; }
        public Nullable<decimal> zcwd { get; set; }
        public Nullable<decimal> pjdmy { get; set; }
        public Nullable<decimal> xl { get; set; }
        public Nullable<decimal> hxpl { get; set; }
        public Nullable<decimal> yhzy { get; set; }
        public Nullable<decimal> dmxyfy { get; set; }
        public Nullable<decimal> dmxph { get; set; }
        public Nullable<decimal> dmxhco3 { get; set; }
        public Nullable<decimal> xqn { get; set; }
        public Nullable<decimal> xqj { get; set; }
        public Nullable<decimal> xjg { get; set; }
        public Nullable<decimal> hxbbr { get; set; }
        public Nullable<decimal> bxbjs { get; set; }
        public Nullable<decimal> nlpf { get; set; }
        public Nullable<decimal> mxbpf { get; set; }
        public Nullable<decimal> zyfy { get; set; }
        public Nullable<decimal> yyfy { get; set; }
        public Nullable<decimal> ydfy { get; set; }
        public Nullable<decimal> hmpf { get; set; }
        public Nullable<decimal> wcbz { get; set; }
        public Nullable<decimal> dybz { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
