//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_ztmx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emr_ztmx()
        {
            this.emr_ztmx_jczx = new HashSet<emr_ztmx_jczx>();
        }
    
        public decimal mxid { get; set; }
        public decimal ztid { get; set; }
        public decimal xmlb { get; set; }
        public decimal xmdm { get; set; }
        public string xmmc { get; set; }
        public Nullable<decimal> mrsl { get; set; }
        public string sldw { get; set; }
        public Nullable<decimal> mrtj { get; set; }
        public string mrpc { get; set; }
        public decimal yzzh { get; set; }
        public decimal bxx { get; set; }
        public Nullable<decimal> xxxz { get; set; }
        public Nullable<decimal> yzqx { get; set; }
        public Nullable<decimal> plsx { get; set; }
        public string bzxx { get; set; }
    
        public virtual emr_yzzt emr_yzzt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_ztmx_jczx> emr_ztmx_jczx { get; set; }
    }
}
