//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_kbm_zdyy
    {
        public decimal jlxh { get; set; }
        public Nullable<decimal> lymblb { get; set; }
        public Nullable<decimal> lymbbh { get; set; }
        public string lydlj { get; set; }
        public string lyqsys { get; set; }
        public string lyzzys { get; set; }
        public string lyqswb { get; set; }
        public string lyzzwb { get; set; }
        public Nullable<decimal> bhbt { get; set; }
        public Nullable<decimal> mbmblb { get; set; }
        public Nullable<decimal> mbmbbh { get; set; }
        public string mbdlj { get; set; }
        public string mbys { get; set; }
    }
}
