//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_wjzdj
    {
        public decimal jlxh { get; set; }
        public string zyhm { get; set; }
        public string brxm { get; set; }
        public Nullable<decimal> brks { get; set; }
        public string brch { get; set; }
        public string ybh { get; set; }
        public Nullable<decimal> brbq { get; set; }
        public string jyid { get; set; }
        public string jyzwmc { get; set; }
        public string jyywmc { get; set; }
        public string wjzjg { get; set; }
        public Nullable<decimal> bgks { get; set; }
        public string bgksmc { get; set; }
        public string bgys { get; set; }
        public Nullable<System.DateTime> bgsj { get; set; }
        public Nullable<decimal> jsks { get; set; }
        public string jsys { get; set; }
        public Nullable<System.DateTime> jssj { get; set; }
        public string cljl { get; set; }
        public Nullable<decimal> cscz { get; set; }
        public Nullable<decimal> cssj { get; set; }
        public Nullable<decimal> jzxh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
