//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_bl04
    {
        public decimal fjbh { get; set; }
        public decimal wdbh { get; set; }
        public decimal fjlx { get; set; }
        public string fjmc { get; set; }
        public Nullable<decimal> fjgl { get; set; }
        public string wjlx { get; set; }
        public Nullable<decimal> wjcd { get; set; }
        public byte[] fjnr { get; set; }
    
        public virtual emr_bl03 emr_bl03 { get; set; }
    }
}
