//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class emr_zlxm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emr_zlxm()
        {
            this.emr_jczx = new HashSet<emr_jczx>();
            this.emr_lccs = new HashSet<emr_lccs>();
            this.emr_zlsfdz = new HashSet<emr_zlsfdz>();
            this.emr_syxm = new HashSet<emr_syxm>();
        }
    
        public decimal zlxmid { get; set; }
        public string xmmc { get; set; }
        public decimal ydyzlb { get; set; }
        public Nullable<decimal> mlbh { get; set; }
        public decimal zxpc { get; set; }
        public string jfpc { get; set; }
        public decimal jsfs { get; set; }
        public Nullable<decimal> jszq { get; set; }
        public string jsdw { get; set; }
        public decimal syxb { get; set; }
        public decimal mzsy { get; set; }
        public decimal zysy { get; set; }
        public Nullable<decimal> tjsy { get; set; }
        public decimal zxlb { get; set; }
        public Nullable<decimal> zxks { get; set; }
        public decimal zxgzid { get; set; }
        public decimal ywzx { get; set; }
        public decimal zxap { get; set; }
        public decimal cpzx { get; set; }
        public decimal szzx { get; set; }
        public decimal jjlx { get; set; }
        public Nullable<decimal> ycxzsl { get; set; }
        public Nullable<decimal> yblx { get; set; }
        public string pydm { get; set; }
        public string wbdm { get; set; }
        public string qtdm { get; set; }
        public string bzsm { get; set; }
        public decimal zxbz { get; set; }
        public string txid { get; set; }
        public Nullable<decimal> bgbh { get; set; }
        public decimal czsy { get; set; }
        public decimal lzsy { get; set; }
        public decimal lccs { get; set; }
        public Nullable<decimal> bwbz { get; set; }
        public Nullable<decimal> jfbz { get; set; }
        public string cfsql { get; set; }
        public Nullable<decimal> sqzb { get; set; }
        public string ZYD { get; set; }
        public string ZYDDYGS { get; set; }
        public Nullable<decimal> CHARGING { get; set; }
        public Nullable<decimal> psxmypid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_jczx> emr_jczx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_lccs> emr_lccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_zlsfdz> emr_zlsfdz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_syxm> emr_syxm { get; set; }
    }
}
