//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMR_JBBK_NCZ
    {
        public decimal JLXH { get; set; }
        public decimal GLBS { get; set; }
        public decimal BRID { get; set; }
        public decimal JZXH { get; set; }
        public Nullable<decimal> JBBM { get; set; }
        public string ICD10 { get; set; }
        public string BKBH { get; set; }
        public string BKLX { get; set; }
        public string BRLX { get; set; }
        public string BRXM { get; set; }
        public string BRDH { get; set; }
        public string GZDW { get; set; }
        public Nullable<decimal> ZY { get; set; }
        public Nullable<decimal> HJDS { get; set; }
        public Nullable<decimal> HJDS2 { get; set; }
        public Nullable<decimal> HJDX { get; set; }
        public string HJDJD { get; set; }
        public Nullable<decimal> XZZS { get; set; }
        public Nullable<decimal> XZZS2 { get; set; }
        public Nullable<decimal> XZZX { get; set; }
        public string XZZJD { get; set; }
        public Nullable<decimal> BRXB { get; set; }
        public string SFZH { get; set; }
        public Nullable<System.DateTime> CSRQ { get; set; }
        public string NL { get; set; }
        public Nullable<decimal> HYZK { get; set; }
        public Nullable<decimal> BRMZ { get; set; }
        public string WHCD { get; set; }
        public Nullable<System.DateTime> FBRQ { get; set; }
        public Nullable<decimal> FBCS { get; set; }
        public Nullable<System.DateTime> ZDRQ { get; set; }
        public string ZDYJ { get; set; }
        public string ZDYJ_OTHER { get; set; }
        public string ZDFL1 { get; set; }
        public string ZDFL2 { get; set; }
        public string ZDFL3 { get; set; }
        public string ZDFL4 { get; set; }
        public string ZDFL5 { get; set; }
        public string ZDFL_OTHER { get; set; }
        public string ZDFL_OTHERBZ { get; set; }
        public string J28TBS { get; set; }
        public Nullable<System.DateTime> SWRQ { get; set; }
        public Nullable<decimal> SWYY { get; set; }
        public string SWICDM { get; set; }
        public string QTJBQK { get; set; }
        public string BKDW { get; set; }
        public Nullable<decimal> BKKS { get; set; }
        public string BKYS { get; set; }
        public Nullable<System.DateTime> BKRQ { get; set; }
        public string BKRLXDH { get; set; }
        public decimal JGID { get; set; }
    }
}
