//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class EMRA_QMJL
    {
        public decimal JLXH { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public string MKID { get; set; }
        public string SYYS { get; set; }
        public Nullable<System.DateTime> SYSJ { get; set; }
        public byte[] QMZ { get; set; }
        public byte[] SJC { get; set; }
        public string ZSXH { get; set; }
        public Nullable<decimal> WDXH { get; set; }
        public byte[] YWSJ { get; set; }
        public string QMSM { get; set; }
    }
}
