//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class GY_AREA
    {
        public decimal ID { get; set; }
        public string CNAME { get; set; }
        public Nullable<decimal> DJLEVEL { get; set; }
        public string SUPERCNAME { get; set; }
        public Nullable<decimal> SUPERID { get; set; }
        public string STATU { get; set; }
        public Nullable<decimal> HOT { get; set; }
    }
}
