//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class gy_bbxx
    {
        public decimal jlxh { get; set; }
        public string jsjm { get; set; }
        public string ipdz { get; set; }
        public Nullable<int> xtsb { get; set; }
        public Nullable<decimal> bbhm_old { get; set; }
        public Nullable<decimal> bbhm { get; set; }
        public Nullable<System.DateTime> gxrq { get; set; }
    }
}
