//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class gy_bb02
    {
        public decimal sbxh { get; set; }
        public Nullable<decimal> bbsb { get; set; }
        public string wjmc { get; set; }
        public string wjlj { get; set; }
        public byte[] wjnr { get; set; }
    
        public virtual gy_bb01 gy_bb01 { get; set; }
    }
}
