//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class gy_jytc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gy_jytc()
        {
            this.gy_jytcmx = new HashSet<gy_jytcmx>();
        }
    
        public decimal tcxh { get; set; }
        public string tcmc { get; set; }
        public string pydm { get; set; }
        public Nullable<decimal> tclx { get; set; }
        public Nullable<decimal> ksdm { get; set; }
        public Nullable<decimal> mzzy { get; set; }
        public Nullable<decimal> bzzl { get; set; }
        public Nullable<decimal> fyhj { get; set; }
        public Nullable<decimal> zfbz { get; set; }
        public Nullable<decimal> sfkyhb { get; set; }
        public Nullable<decimal> sfjmcx { get; set; }
        public Nullable<decimal> sfxysg { get; set; }
        public Nullable<decimal> sgfyxh { get; set; }
        public Nullable<decimal> cxfyxh { get; set; }
        public Nullable<decimal> ybzl { get; set; }
        public Nullable<decimal> xsxh { get; set; }
        public string printjc { get; set; }
        public Nullable<decimal> dlcx { get; set; }
        public string xmzh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gy_jytcmx> gy_jytcmx { get; set; }
    }
}
