//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HIQC_TEMPERATURE
    {
        public string PATIENT_ID { get; set; }
        public string TEMPERATUREKEY { get; set; }
        public Nullable<System.DateTime> TEMPERATURE_DATE { get; set; }
        public string ITEM_DEPT { get; set; }
        public Nullable<decimal> TEMPERATURE_VALUE { get; set; }
        public string ITEM_DEPTCODE { get; set; }
        public string TEMP_TYPE { get; set; }
        public decimal JGID { get; set; }
    }
}
