//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HIQC_ZZFLTJB
    {
        public decimal JLXH { get; set; }
        public Nullable<System.DateTime> JLSJ { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<decimal> A1 { get; set; }
        public Nullable<decimal> A2 { get; set; }
        public Nullable<decimal> A3 { get; set; }
        public Nullable<decimal> A4 { get; set; }
        public Nullable<decimal> B1 { get; set; }
        public Nullable<decimal> B2 { get; set; }
        public Nullable<decimal> B3 { get; set; }
        public Nullable<decimal> B4 { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> D1 { get; set; }
        public Nullable<decimal> D2 { get; set; }
        public Nullable<decimal> D3 { get; set; }
        public Nullable<decimal> D4 { get; set; }
        public Nullable<decimal> E1 { get; set; }
        public Nullable<decimal> E2 { get; set; }
        public Nullable<decimal> E3 { get; set; }
        public Nullable<decimal> E4 { get; set; }
        public decimal JGID { get; set; }
    }
}
