//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HIQC_YGZD
    {
        public string JLXH { get; set; }
        public string JLXH_PARENT { get; set; }
        public string JLBMC { get; set; }
        public string JLMC { get; set; }
        public string XSZ { get; set; }
        public string SJZ { get; set; }
        public string PYDM { get; set; }
        public string SYSPARM { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string OPERCON { get; set; }
        public string SPECIALCOL { get; set; }
        public Nullable<decimal> LIQUIDDDD { get; set; }
        public Nullable<decimal> TABLETDDD { get; set; }
        public string ZDCLASS { get; set; }
        public string ANTIBIOTICTYPE { get; set; }
        public string JLXH_PARENT_EXPAND { get; set; }
        public string UNIT { get; set; }
        public string ANTIBIOTICCLASS { get; set; }
        public string ANTIBIOTICCLASS_SUB { get; set; }
        public Nullable<decimal> JLXH_LEVEL { get; set; }
    }
}
