//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HIQC_HJWSMX
    {
        public decimal JLXH { get; set; }
        public string JCLX { get; set; }
        public string JCKS { get; set; }
        public string JCZ { get; set; }
        public string BZZ { get; set; }
        public string DW { get; set; }
        public Nullable<System.DateTime> JYRQ { get; set; }
        public string BZ { get; set; }
        public string DJYG { get; set; }
        public Nullable<System.DateTime> DJSJ { get; set; }
        public string CYYG { get; set; }
        public string JYYG { get; set; }
        public Nullable<System.DateTime> CYRQ { get; set; }
        public Nullable<decimal> SFHG { get; set; }
        public decimal JGID { get; set; }
    }
}
