//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HIQC_YGXHL
    {
        public decimal JLXH { get; set; }
        public Nullable<decimal> ZYH { get; set; }
        public string ZYHM { get; set; }
        public string BAHM { get; set; }
        public string BRXM { get; set; }
        public string BRXB { get; set; }
        public Nullable<decimal> BRKS { get; set; }
        public string BRCH { get; set; }
        public string ZLXZ { get; set; }
        public Nullable<System.DateTime> CSRQ { get; set; }
        public string BRNL { get; set; }
        public string YSDM { get; set; }
        public Nullable<System.DateTime> JLRQ { get; set; }
        public string YGDM { get; set; }
        public Nullable<System.DateTime> DCRQ { get; set; }
        public Nullable<decimal> ZD { get; set; }
        public Nullable<decimal> SS { get; set; }
        public string QKLX { get; set; }
        public Nullable<decimal> GRFL { get; set; }
        public string BW1 { get; set; }
        public string BW2 { get; set; }
        public string BW3 { get; set; }
        public string BYT1 { get; set; }
        public string BYT2 { get; set; }
        public string BYT3 { get; set; }
        public Nullable<decimal> MND { get; set; }
        public Nullable<decimal> MND48 { get; set; }
        public Nullable<decimal> DJM { get; set; }
        public Nullable<decimal> DJM48 { get; set; }
        public Nullable<decimal> QGQK { get; set; }
        public Nullable<decimal> QGQK48 { get; set; }
        public Nullable<decimal> HXJ { get; set; }
        public Nullable<decimal> HXJ48 { get; set; }
        public Nullable<decimal> XYTX { get; set; }
        public Nullable<decimal> KJYW { get; set; }
        public Nullable<decimal> KJMD { get; set; }
        public Nullable<decimal> KJLY { get; set; }
        public Nullable<decimal> XJPY { get; set; }
        public decimal JGID { get; set; }
    }
}
