//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hl_hlxj
    {
        public decimal xjbh { get; set; }
        public string gzqq { get; set; }
        public string txry { get; set; }
        public Nullable<System.DateTime> txrq { get; set; }
        public Nullable<decimal> xjks { get; set; }
    }
}
