//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_PSZD_JGID
    {
        public decimal JGID { get; set; }
        public string PSBBDM { get; set; }
        public string PSBBMC { get; set; }
        public string PSBDDM { get; set; }
        public string PSBDMC { get; set; }
        public string BZ { get; set; }
        public decimal TY { get; set; }
    }
}
