//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_HXJYF
    {
        public decimal JLXH { get; set; }
        public decimal ZYH { get; set; }
        public string BRCH { get; set; }
        public decimal BRKS { get; set; }
        public decimal BRBQ { get; set; }
        public decimal YFRS { get; set; }
        public decimal YFKS { get; set; }
        public Nullable<System.DateTime> YFRQ { get; set; }
        public decimal DJWZ { get; set; }
        public decimal DJTJ { get; set; }
        public System.DateTime DJRQ { get; set; }
        public string DJYG { get; set; }
        public decimal ZFBZ { get; set; }
        public decimal JGID { get; set; }
    }
}
