//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_QTFXSJ
    {
        public decimal ZYH { get; set; }
        public Nullable<System.DateTime> CYRQ { get; set; }
        public Nullable<decimal> XSEBZ { get; set; }
        public Nullable<decimal> XSECSBZ { get; set; }
        public Nullable<decimal> CFBZ { get; set; }
        public Nullable<decimal> CFCSBZ { get; set; }
        public Nullable<decimal> YYCWBZ { get; set; }
        public Nullable<decimal> SXFYBZ { get; set; }
        public Nullable<decimal> SYFYBZ { get; set; }
        public Nullable<decimal> SSYWYLBZ { get; set; }
        public Nullable<decimal> YYXQXBZ { get; set; }
        public Nullable<decimal> YYXYWCCSBZ { get; set; }
        public Nullable<decimal> SWBZ { get; set; }
        public Nullable<decimal> TBFS { get; set; }
        public Nullable<System.DateTime> TBRQ { get; set; }
        public decimal JGID { get; set; }
    }
}
