//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_ARCHIVE_LOG
    {
        public string SID { get; set; }
        public string BRXM { get; set; }
        public Nullable<System.DateTime> RYRQ { get; set; }
        public Nullable<System.DateTime> CYRQ { get; set; }
        public string ZYHM { get; set; }
        public Nullable<decimal> JZXH { get; set; }
        public string JZHM { get; set; }
        public Nullable<System.DateTime> GDRQ { get; set; }
        public string CWXX { get; set; }
        public Nullable<System.DateTime> CZRQ { get; set; }
        public Nullable<decimal> CZLX { get; set; }
        public decimal JGID { get; set; }
    }
}
