//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_PSJL
    {
        public decimal XH { get; set; }
        public string PSBB { get; set; }
        public string PSMC { get; set; }
        public string PSPC { get; set; }
        public string PSNF { get; set; }
        public Nullable<System.DateTime> CJRQ { get; set; }
        public string CJGH { get; set; }
        public string CJR { get; set; }
        public Nullable<decimal> TY { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
