//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HMI_PSJL_ZCCL
    {
        public decimal XH { get; set; }
        public Nullable<decimal> PSJLXH { get; set; }
        public string WJMC { get; set; }
        public string WJLJ { get; set; }
        public byte[] WJNR { get; set; }
        public Nullable<decimal> PSXH { get; set; }
        public string CZZT { get; set; }
        public string SCGH { get; set; }
        public string IPDZ { get; set; }
        public string DNMC { get; set; }
        public Nullable<System.DateTime> SCSJ { get; set; }
        public string PSDM { get; set; }
        public decimal JGID { get; set; }
    }
}
