//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hs_jjff
    {
        public decimal hsxh { get; set; }
        public string ygdm { get; set; }
        public decimal jjje { get; set; }
    
        public virtual hs_szqk1 hs_szqk1 { get; set; }
    }
}
