//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hzyb_ka02
    {
        public string aka060 { get; set; }
        public string aka061 { get; set; }
        public string aka062 { get; set; }
        public string aka020 { get; set; }
        public string aka021 { get; set; }
        public string aka063 { get; set; }
        public string aka065 { get; set; }
        public string aka064 { get; set; }
        public string aka067 { get; set; }
        public string aka070 { get; set; }
        public Nullable<decimal> aka071 { get; set; }
        public string aka072 { get; set; }
        public string bka076 { get; set; }
        public string aka074 { get; set; }
        public string bka084 { get; set; }
        public string akb020 { get; set; }
        public string bka608 { get; set; }
        public string aka107 { get; set; }
        public string bka616 { get; set; }
        public string bka620 { get; set; }
        public string bka613 { get; set; }
        public string bka639 { get; set; }
        public string aka101 { get; set; }
        public string bka602 { get; set; }
        public string ala011 { get; set; }
        public string ama011 { get; set; }
        public System.DateTime aae030 { get; set; }
        public Nullable<System.DateTime> aae031 { get; set; }
        public string aae100 { get; set; }
        public string aae013 { get; set; }
        public string bka205 { get; set; }
        public Nullable<decimal> bka086 { get; set; }
        public Nullable<decimal> bka094 { get; set; }
        public Nullable<decimal> bka095 { get; set; }
        public Nullable<decimal> bka096 { get; set; }
        public Nullable<decimal> bka097 { get; set; }
        public Nullable<decimal> bka098 { get; set; }
        public Nullable<decimal> bka099 { get; set; }
        public string bka237 { get; set; }
        public string bka240 { get; set; }
        public string bka241 { get; set; }
        public string bka242 { get; set; }
        public string bka244 { get; set; }
        public string bka245 { get; set; }
        public string bka246 { get; set; }
        public string bka247 { get; set; }
        public string bka248 { get; set; }
        public string bka249 { get; set; }
        public string bka209 { get; set; }
        public string bka210 { get; set; }
        public string bka206 { get; set; }
        public string bka216 { get; set; }
        public string bka217 { get; set; }
        public string gjjb { get; set; }
        public string bka219 { get; set; }
        public string bka220 { get; set; }
        public string bka221 { get; set; }
        public string bka222 { get; set; }
        public string bka223 { get; set; }
        public string bka225 { get; set; }
        public string bka227 { get; set; }
        public string bka228 { get; set; }
        public string bka230 { get; set; }
        public string bka231 { get; set; }
        public string bka232 { get; set; }
        public string bka325 { get; set; }
        public string aka022 { get; set; }
        public string bka250 { get; set; }
        public string bka621 { get; set; }
        public string bka251 { get; set; }
        public Nullable<System.DateTime> aae036 { get; set; }
        public string bka218 { get; set; }
        public string bka070 { get; set; }
        public string bka253 { get; set; }
        public string bka710 { get; set; }
        public string bka716 { get; set; }
    }
}
