//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hzyb_jsd
    {
        public string jslsh { get; set; }
        public string grbh { get; set; }
        public string xm { get; set; }
        public string rylb { get; set; }
        public string shbzh { get; set; }
        public string zlbh { get; set; }
        public string yllb { get; set; }
        public string dwbh { get; set; }
        public string dwmc { get; set; }
        public string ryzd { get; set; }
        public string cyzd { get; set; }
        public string yymc { get; set; }
        public string yydj { get; set; }
        public string zycs { get; set; }
        public string ryrq { get; set; }
        public string cyrq { get; set; }
        public string knjzdj { get; set; }
        public string yllj { get; set; }
        public string zflj { get; set; }
        public string lnye { get; set; }
        public string zjje { get; set; }
        public string xjzfzf { get; set; }
        public string lnzf { get; set; }
        public string bjjjzf { get; set; }
        public string xjzl { get; set; }
        public string lnzl { get; set; }
        public string yycd { get; set; }
        public string qfbz { get; set; }
        public string xjzf { get; set; }
        public string fdzf1 { get; set; }
        public string fdzf2 { get; set; }
        public string fdzf3 { get; set; }
        public string fdzf4 { get; set; }
        public string lnzh { get; set; }
        public string knjz { get; set; }
        public string qtzf { get; set; }
        public string tcjj { get; set; }
        public string zbjj { get; set; }
        public string gljj { get; set; }
        public string grxj { get; set; }
        public string bz { get; set; }
        public string bjjj { get; set; }
        public string bjzfzf { get; set; }
        public string qtzl { get; set; }
    }
}
