//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class HZYB_SPBA
    {
        public decimal JLXH { get; set; }
        public decimal BRID { get; set; }
        public decimal MZZY { get; set; }
        public string BALB { get; set; }
        public string GRBH { get; set; }
        public System.DateTime KSRQ { get; set; }
        public Nullable<System.DateTime> ZZRQ { get; set; }
        public string JBBM { get; set; }
        public string JBMC { get; set; }
        public string BZXX { get; set; }
        public string XMBM { get; set; }
        public string XMMC { get; set; }
        public string ZSTJ { get; set; }
        public string BASL { get; set; }
        public string BAJE { get; set; }
        public string YYSQ { get; set; }
        public string KFBW { get; set; }
        public string YSGH { get; set; }
        public string YSXM { get; set; }
        public string JBR { get; set; }
        public string SPSSQ { get; set; }
        public Nullable<System.DateTime> ZYRQ { get; set; }
        public string ZYJG { get; set; }
        public string ZYJGMC { get; set; }
        public string ZWCS { get; set; }
        public string SSBM { get; set; }
        public decimal CXBZ { get; set; }
        public string BABH { get; set; }
        public decimal BAZSL { get; set; }
        public decimal BASYL { get; set; }
        public Nullable<decimal> YPCD { get; set; }
        public Nullable<decimal> YPXH { get; set; }
        public Nullable<decimal> XMLX { get; set; }
        public Nullable<decimal> JBXH { get; set; }
        public Nullable<decimal> SCBZ_YH { get; set; }
        public Nullable<decimal> SYSL { get; set; }
        public string BACD { get; set; }
        public Nullable<decimal> KSDM { get; set; }
        public string KSMC { get; set; }
    }
}
