//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class hzyb_kb23
    {
        public string bkc022 { get; set; }
        public System.DateTime aae030 { get; set; }
        public string aac001 { get; set; }
        public string aac003 { get; set; }
        public string aac004 { get; set; }
        public string aac005 { get; set; }
        public Nullable<System.DateTime> aac006 { get; set; }
        public string bae017 { get; set; }
        public string aac002 { get; set; }
        public string aae006 { get; set; }
        public Nullable<System.DateTime> aae036 { get; set; }
    }
}
