//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ipt_medicalrecordpage_new
    {
        public string jgdm { get; set; }
        public string jzlsh { get; set; }
        public string healthcardid { get; set; }
        public string hospizationid { get; set; }
        public string medicalrecordid { get; set; }
        public string pathologyid { get; set; }
        public string kh { get; set; }
        public Nullable<decimal> klx { get; set; }
        public string xm { get; set; }
        public Nullable<decimal> sex { get; set; }
        public Nullable<decimal> nl { get; set; }
        public Nullable<decimal> hyzkdm { get; set; }
        public string zylbdm { get; set; }
        public string gj { get; set; }
        public Nullable<System.DateTime> csrqsj { get; set; }
        public Nullable<decimal> aboxx { get; set; }
        public Nullable<decimal> rhxx { get; set; }
        public string originprovince { get; set; }
        public string origincity { get; set; }
        public string presentaddrprovince { get; set; }
        public string presentaddrcity { get; set; }
        public string presentaddrcounty { get; set; }
        public string presentaddrother { get; set; }
        public string presentaddrpostalcode { get; set; }
        public Nullable<decimal> medicalpayment { get; set; }
        public string outsidereasonofinjuryandpocode { get; set; }
        public string masterdiseasecode { get; set; }
        public string masterdiseasename { get; set; }
        public string pathologydiseasecode { get; set; }
        public string pathologydiseasename { get; set; }
        public string clinicwesterndiagnosiscode { get; set; }
        public string clinicdiagnosis { get; set; }
        public Nullable<decimal> masteradmissioncondition { get; set; }
        public string monthsage { get; set; }
        public Nullable<decimal> neonatalbirthweight { get; set; }
        public Nullable<decimal> neonataladmissionweight { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string patientphone { get; set; }
        public string registeredpermanentresidencepr { get; set; }
        public string registeredpermanentresidenceci { get; set; }
        public string registeredpermanentresidenceto { get; set; }
        public string registeredpermanentresidenceot { get; set; }
        public string registeredpermanentresidencepo { get; set; }
        public string workaddrphone { get; set; }
        public Nullable<decimal> admissionway { get; set; }
        public Nullable<System.DateTime> dischargedatetime { get; set; }
        public string dischargesickroom { get; set; }
        public Nullable<decimal> actualhospitalizationdays { get; set; }
        public string masterdischargeprognosiscondit { get; set; }
        public string outsidereasonofinjuryandpoison { get; set; }
        public Nullable<decimal> drugallergy { get; set; }
        public string allergicdrug { get; set; }
        public Nullable<System.DateTime> admissiondatetime { get; set; }
        public string admissionsickroom { get; set; }
        public Nullable<decimal> autopsysign { get; set; }
        public Nullable<decimal> medicalrecordquality { get; set; }
        public Nullable<System.DateTime> qualitycontroldate { get; set; }
        public Nullable<decimal> dischargemethods { get; set; }
        public string prepareaccepthospitalname { get; set; }
        public Nullable<decimal> day31inpatientmk { get; set; }
        public string day31inpatientaim { get; set; }
        public Nullable<decimal> stuportimebeforeadmission { get; set; }
        public Nullable<decimal> stuportimeafteradmission { get; set; }
        public Nullable<decimal> diagcoinoutpatientvsdischarge { get; set; }
        public Nullable<decimal> diagcoinadmssionvsdischarge { get; set; }
        public Nullable<decimal> diagcoinpreoperativevspost { get; set; }
        public Nullable<decimal> diagcoinclinicalvspathologica { get; set; }
        public Nullable<decimal> diagcoinradiologyvspathology { get; set; }
        public Nullable<decimal> salvageconditionsalvagetimes { get; set; }
        public Nullable<decimal> salvageconditionsuccesstimes { get; set; }
        public Nullable<decimal> clinicalpathmanagement { get; set; }
        public string attendingdoctor { get; set; }
        public string hospizationdoctor { get; set; }
        public string responsibilitynurse { get; set; }
        public string refresherdoctors { get; set; }
        public string interndoctor { get; set; }
        public string medicalrecordcodersign { get; set; }
        public string qualitycontroldoctor { get; set; }
        public string qualitycontrolsign { get; set; }
        public string transferreddeptname { get; set; }
        public string dischargedepartment { get; set; }
        public string admissiondeptname { get; set; }
        public Nullable<decimal> genermediservcharge { get; set; }
        public Nullable<decimal> genertreathandlingfee { get; set; }
        public Nullable<decimal> nurse { get; set; }
        public Nullable<decimal> genermediservchargeother { get; set; }
        public Nullable<decimal> pathologicalfee { get; set; }
        public Nullable<decimal> laboratoryfee { get; set; }
        public Nullable<decimal> imagingfee { get; set; }
        public Nullable<decimal> clinicaldiagnosisfee { get; set; }
        public Nullable<decimal> nonoperativetreatfee { get; set; }
        public Nullable<decimal> clinicalphysicaltreatment { get; set; }
        public Nullable<decimal> surgicaltreatment { get; set; }
        public Nullable<decimal> estheticfee { get; set; }
        public Nullable<decimal> operationfee { get; set; }
        public Nullable<decimal> rehabilitationfee { get; set; }
        public Nullable<decimal> zyzlfee { get; set; }
        public Nullable<decimal> medicinechina { get; set; }
        public Nullable<decimal> xyfee { get; set; }
        public Nullable<decimal> herbalmedicinefee { get; set; }
        public Nullable<decimal> antibacterialdrugexp { get; set; }
        public Nullable<decimal> bloodfee { get; set; }
        public Nullable<decimal> acpfee { get; set; }
        public Nullable<decimal> gcpfee { get; set; }
        public Nullable<decimal> nxyzfee { get; set; }
        public Nullable<decimal> xbyzfee { get; set; }
        public string deptmanager { get; set; }
        public Nullable<decimal> ycyycxfee { get; set; }
        public string chiefdoctorsign { get; set; }
        public Nullable<decimal> zlyycxfee { get; set; }
        public Nullable<decimal> ssyycxzlfee { get; set; }
        public Nullable<decimal> otherfee { get; set; }
        public Nullable<decimal> hospizationtotalpersonalcost { get; set; }
        public Nullable<decimal> hospizationtotalcost { get; set; }
        public Nullable<decimal> zycs { get; set; }
        public string gzdwdz { get; set; }
        public Nullable<decimal> gzddyb { get; set; }
        public string lxrxm { get; set; }
        public string gzdwmc { get; set; }
        public string lxrdz { get; set; }
        public string lxrdh { get; set; }
        public string gzdwdhhm { get; set; }
        public Nullable<decimal> mz { get; set; }
        public Nullable<decimal> lxryhzgx { get; set; }
        public decimal scbz { get; set; }
    }
}
