//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ipt_advicedetail
    {
        public string jgdm { get; set; }
        public string jzlsh { get; set; }
        public string yzid { get; set; }
        public string yzzh { get; set; }
        public Nullable<decimal> yzbs { get; set; }
        public string yzmxbm { get; set; }
        public string yzmxmc { get; set; }
        public string yptym { get; set; }
        public string ypspm { get; set; }
        public string cdid { get; set; }
        public string cdmc { get; set; }
        public string ypbzggxs { get; set; }
        public string ypbzggdw { get; set; }
        public Nullable<decimal> sfyp { get; set; }
        public string ypgg { get; set; }
        public Nullable<decimal> ypsl { get; set; }
        public string ypdw { get; set; }
        public string ypyf { get; set; }
        public string yypd { get; set; }
        public string ywfzy { get; set; }
        public Nullable<decimal> mcsyjl { get; set; }
        public string mcsyjldw { get; set; }
        public Nullable<decimal> mcsysl { get; set; }
        public Nullable<decimal> ywjxdm { get; set; }
        public string mcsysldw { get; set; }
        public Nullable<decimal> zfybs { get; set; }
        public Nullable<decimal> tjdm { get; set; }
        public string zyjzfdm { get; set; }
        public Nullable<decimal> yyts { get; set; }
        public string xsypdw { get; set; }
        public string ypyxcfsl { get; set; }
        public string ypyxcfdw { get; set; }
        public Nullable<decimal> yymd { get; set; }
        public string kdysgh { get; set; }
        public string kdysxm { get; set; }
        public string kdksdm { get; set; }
        public string kdyszc { get; set; }
        public Nullable<System.DateTime> kdsj { get; set; }
        public string zxrygh { get; set; }
        public string zxryxm { get; set; }
        public string zxksdm { get; set; }
        public Nullable<System.DateTime> zxsj { get; set; }
        public string jcbwacrbm { get; set; }
        public Nullable<decimal> dj { get; set; }
        public Nullable<decimal> ze { get; set; }
        public Nullable<System.DateTime> zzsj { get; set; }
        public decimal scbz { get; set; }
    }
}
