//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class kc24
    {
        public string akb020 { get; set; }
        public string akc190 { get; set; }
        public string ckc131 { get; set; }
        public string aae072 { get; set; }
        public Nullable<decimal> ckc130 { get; set; }
        public string aab001 { get; set; }
        public string aac001 { get; set; }
        public Nullable<decimal> aae040 { get; set; }
        public string aka130 { get; set; }
        public string akc021 { get; set; }
        public Nullable<decimal> akc264 { get; set; }
        public Nullable<decimal> akc251 { get; set; }
        public Nullable<decimal> akc263 { get; set; }
        public Nullable<decimal> akc252 { get; set; }
        public Nullable<decimal> ckc046 { get; set; }
        public Nullable<decimal> akc253 { get; set; }
        public Nullable<decimal> zkc033 { get; set; }
        public Nullable<decimal> zkc032 { get; set; }
        public Nullable<decimal> ckc066 { get; set; }
        public Nullable<decimal> akc256 { get; set; }
        public Nullable<decimal> ckc200 { get; set; }
        public Nullable<decimal> ckc201 { get; set; }
        public Nullable<decimal> akc257 { get; set; }
        public Nullable<decimal> ckc202 { get; set; }
        public Nullable<decimal> ckc203 { get; set; }
        public Nullable<decimal> ckc191 { get; set; }
        public Nullable<decimal> ckc192 { get; set; }
        public Nullable<decimal> ckc193 { get; set; }
        public Nullable<decimal> ckc194 { get; set; }
        public Nullable<decimal> ckc195 { get; set; }
        public Nullable<decimal> akc258 { get; set; }
        public Nullable<decimal> akc255 { get; set; }
        public Nullable<decimal> ckc039 { get; set; }
        public Nullable<decimal> akc260 { get; set; }
        public Nullable<decimal> akc261 { get; set; }
        public Nullable<decimal> zkc024 { get; set; }
        public Nullable<decimal> zkc025 { get; set; }
        public Nullable<decimal> akc265 { get; set; }
        public Nullable<System.DateTime> akc266 { get; set; }
        public string akc267 { get; set; }
        public string akc197 { get; set; }
        public string aae011 { get; set; }
        public Nullable<System.DateTime> aae036 { get; set; }
        public Nullable<decimal> aae074 { get; set; }
        public string aae117 { get; set; }
        public Nullable<decimal> aae076 { get; set; }
        public string cdc100 { get; set; }
        public Nullable<decimal> ckc502 { get; set; }
        public Nullable<decimal> ckc503 { get; set; }
        public Nullable<decimal> ckc504 { get; set; }
        public Nullable<decimal> ckc505 { get; set; }
        public string akc022 { get; set; }
        public string bkc131 { get; set; }
        public string ckc333 { get; set; }
        public string bkc001 { get; set; }
        public Nullable<decimal> bkc261 { get; set; }
        public string bkc263 { get; set; }
        public string bkc270 { get; set; }
        public Nullable<decimal> bkc265 { get; set; }
        public string akc020 { get; set; }
        public Nullable<decimal> ckc602 { get; set; }
        public string ckc031 { get; set; }
        public string ckc603 { get; set; }
        public string ckc604 { get; set; }
        public Nullable<double> ckc606 { get; set; }
        public Nullable<double> ckc607 { get; set; }
        public string ckc205 { get; set; }
        public string ckc030 { get; set; }
        public Nullable<decimal> ckc625 { get; set; }
        public Nullable<decimal> ckc626 { get; set; }
        public Nullable<decimal> ckc627 { get; set; }
        public string aac008 { get; set; }
        public string aac039 { get; set; }
        public string aac020 { get; set; }
        public string aac021 { get; set; }
        public string aac016 { get; set; }
        public string aac133 { get; set; }
        public string aac135 { get; set; }
        public string aac137 { get; set; }
        public string ckc506 { get; set; }
        public string aab019 { get; set; }
        public string aab020 { get; set; }
        public Nullable<decimal> akc023 { get; set; }
        public Nullable<decimal> ckc643 { get; set; }
        public Nullable<decimal> ckc644 { get; set; }
        public Nullable<decimal> ckc645 { get; set; }
        public Nullable<decimal> ckc652 { get; set; }
        public Nullable<decimal> ckc653 { get; set; }
        public Nullable<decimal> ckc654 { get; set; }
        public string ckc679 { get; set; }
        public string ckc680 { get; set; }
        public string ckc711 { get; set; }
        public Nullable<decimal> ckc706 { get; set; }
        public Nullable<decimal> ckc941 { get; set; }
        public Nullable<decimal> ckc942 { get; set; }
        public string ckc939 { get; set; }
        public string aac002 { get; set; }
        public string akc026 { get; set; }
        public Nullable<decimal> ckc943 { get; set; }
    }
}
