//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class KH_DWDA
    {
        public decimal DWID { get; set; }
        public decimal JGID { get; set; }
        public decimal DWLB { get; set; }
        public string DWBH { get; set; }
        public string DWMC { get; set; }
        public string DWDZ { get; set; }
        public string DWYB { get; set; }
        public string DWDH { get; set; }
        public string CZHM { get; set; }
        public string LXRM { get; set; }
        public string LXDZ { get; set; }
        public string LXYB { get; set; }
        public string LXDH { get; set; }
        public string SJHM { get; set; }
        public string DZYX { get; set; }
        public decimal MZXFJE { get; set; }
        public decimal MZXFJF { get; set; }
        public decimal MZZSJF { get; set; }
        public decimal MZXFLJ { get; set; }
        public decimal MZJFLJ { get; set; }
        public decimal MZZSLJ { get; set; }
        public decimal ZYXFJE { get; set; }
        public decimal ZYXFJF { get; set; }
        public decimal ZYZSJF { get; set; }
        public decimal ZYXFLJ { get; set; }
        public decimal ZYJFLJ { get; set; }
        public decimal ZYZSLJ { get; set; }
        public Nullable<System.DateTime> JDRQ { get; set; }
        public string JDRY { get; set; }
    }
}
