//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class KH_SFJL
    {
        public decimal SFXH { get; set; }
        public decimal JGID { get; set; }
        public decimal RYXH { get; set; }
        public decimal BRID { get; set; }
        public string KSDM { get; set; }
        public string YSDM { get; set; }
        public System.DateTime SFRQ { get; set; }
        public decimal SFLB { get; set; }
        public string SFKS { get; set; }
        public string SFRY { get; set; }
        public string SFDX { get; set; }
        public Nullable<decimal> SFZQ { get; set; }
        public Nullable<System.DateTime> XCSF { get; set; }
        public decimal SWBZ { get; set; }
        public decimal YDBZ { get; set; }
        public System.DateTime LRRQ { get; set; }
        public string LRRY { get; set; }
        public Nullable<decimal> SFGL { get; set; }
    }
}
