//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class KH_TSJL
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public Nullable<decimal> BRID { get; set; }
        public string BRXM { get; set; }
        public string LXDH { get; set; }
        public System.DateTime TSRQ { get; set; }
        public decimal TSLB { get; set; }
        public string TSNR { get; set; }
        public string KSDM { get; set; }
        public string YGDM { get; set; }
        public Nullable<System.DateTime> CLRQ { get; set; }
        public string CLRY { get; set; }
        public string CLJG { get; set; }
        public Nullable<System.DateTime> FKRQ { get; set; }
        public string FKRY { get; set; }
        public Nullable<decimal> FKFS { get; set; }
        public Nullable<decimal> FKJG { get; set; }
    }
}
