//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class KH_ZYJL
    {
        public decimal RYXH { get; set; }
        public decimal JGID { get; set; }
        public decimal RYCS { get; set; }
        public decimal BRID { get; set; }
        public string BRKH { get; set; }
        public string BRXM { get; set; }
        public string BRXB { get; set; }
        public Nullable<System.DateTime> CSRQ { get; set; }
        public string SFZH { get; set; }
        public string HYZK { get; set; }
        public string GJDM { get; set; }
        public string SFDM { get; set; }
        public string JGDM { get; set; }
        public string MZDM { get; set; }
        public string ZYDM { get; set; }
        public Nullable<decimal> BRSG { get; set; }
        public Nullable<decimal> BRTZ { get; set; }
        public string DWMC { get; set; }
        public string DWDZ { get; set; }
        public string DWYB { get; set; }
        public string DWDH { get; set; }
        public string CSDZ { get; set; }
        public string HKDZ { get; set; }
        public string HKYB { get; set; }
        public string JTDH { get; set; }
        public string LXRM { get; set; }
        public string LXDZ { get; set; }
        public string LXYB { get; set; }
        public string LXDH { get; set; }
        public string LXGX { get; set; }
        public string SJHM { get; set; }
        public string XLTH { get; set; }
        public string CZHM { get; set; }
        public string DZYX { get; set; }
        public string BAHM { get; set; }
        public string FKFS { get; set; }
        public System.DateTime RYRQ { get; set; }
        public string RYKS { get; set; }
        public string RYBQ { get; set; }
        public Nullable<System.DateTime> ZKRQ { get; set; }
        public string ZKKS { get; set; }
        public System.DateTime CYRQ { get; set; }
        public string CYKS { get; set; }
        public string CYBQ { get; set; }
        public string CWHM { get; set; }
        public Nullable<System.DateTime> SSRQ { get; set; }
        public string SSMC { get; set; }
        public string SSYS { get; set; }
        public string MZFS { get; set; }
        public string SMYS { get; set; }
        public string ZRYS { get; set; }
        public string ZZYS { get; set; }
        public string ZYYS { get; set; }
        public string MZYS { get; set; }
        public string MZZD { get; set; }
        public string RYZD { get; set; }
        public string BLZD { get; set; }
        public string YNGR { get; set; }
        public string CYZD_1 { get; set; }
        public string CYZD_2 { get; set; }
        public string CYZD_3 { get; set; }
        public Nullable<decimal> CYQK_1 { get; set; }
        public Nullable<decimal> CYQK_2 { get; set; }
        public Nullable<decimal> CYQK_3 { get; set; }
        public string ICD_1 { get; set; }
        public string ICD_2 { get; set; }
        public string ICD_3 { get; set; }
        public decimal CWF { get; set; }
        public decimal XYF { get; set; }
        public decimal ZYF { get; set; }
        public decimal CYF { get; set; }
        public decimal JCF { get; set; }
        public decimal FSF { get; set; }
        public decimal JYF { get; set; }
        public decimal ZLF { get; set; }
        public decimal SYF { get; set; }
        public decimal SXF { get; set; }
        public decimal SSF { get; set; }
        public decimal MZF { get; set; }
        public decimal ZCF { get; set; }
        public decimal HLF { get; set; }
        public decimal JSF { get; set; }
        public decimal YEF { get; set; }
        public decimal PCF { get; set; }
        public decimal QTF { get; set; }
        public string YEXM { get; set; }
        public string YEXB { get; set; }
        public Nullable<System.DateTime> YECSRQ { get; set; }
        public decimal XFJF { get; set; }
        public decimal ZSJF { get; set; }
        public decimal ZSID { get; set; }
        public Nullable<System.DateTime> DRRQ { get; set; }
        public Nullable<System.DateTime> GXRQ { get; set; }
        public string HISID { get; set; }
    }
}
