//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class kj_kyfy
    {
        public decimal fyxh { get; set; }
        public string xmmc { get; set; }
        public Nullable<decimal> lyxh { get; set; }
        public string fuzr { get; set; }
        public Nullable<decimal> jsfe { get; set; }
        public Nullable<decimal> lcfe { get; set; }
        public Nullable<decimal> jdfe { get; set; }
        public Nullable<decimal> qtfy { get; set; }
        public string pydm { get; set; }
    }
}
