//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class l_lis_sqdmx
    {
        public string doctrequestno { get; set; }
        public decimal hyid { get; set; }
        public decimal prehyid { get; set; }
        public string ztmc { get; set; }
        public decimal ylxh { get; set; }
        public string ylmc { get; set; }
        public Nullable<decimal> dj { get; set; }
        public Nullable<decimal> sl { get; set; }
        public Nullable<decimal> feestatus { get; set; }
        public string sampletype { get; set; }
        public Nullable<decimal> zxpb { get; set; }
        public string bz { get; set; }
        public Nullable<System.DateTime> executetime { get; set; }
        public string executor { get; set; }
        public Nullable<System.DateTime> receivetime { get; set; }
        public string receiver { get; set; }
        public string ybh { get; set; }
        public Nullable<decimal> jlxh { get; set; }
        public Nullable<decimal> ysyzbh { get; set; }
        public Nullable<decimal> yjxh { get; set; }
        public Nullable<decimal> cxbz { get; set; }
        public Nullable<decimal> mfxm { get; set; }
        public Nullable<decimal> xmlba { get; set; }
        public Nullable<decimal> djid { get; set; }
        public Nullable<decimal> jgid { get; set; }
    }
}
