//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class l_patientinfo
    {
        public string ybbh { get; set; }
        public string yblx { get; set; }
        public string mzhm { get; set; }
        public string brxm { get; set; }
        public string brxb { get; set; }
        public string brnl { get; set; }
        public string nldw { get; set; }
        public string lxdh { get; set; }
        public string jymd { get; set; }
        public Nullable<System.DateTime> sqrq { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public string doctor { get; set; }
        public Nullable<System.DateTime> cyrq { get; set; }
        public Nullable<System.DateTime> sjrq { get; set; }
        public string cydoctor { get; set; }
        public Nullable<System.DateTime> jcrq { get; set; }
        public string jydoctor { get; set; }
        public Nullable<System.DateTime> bgrq { get; set; }
        public string bgdoctor { get; set; }
        public string diagnose { get; set; }
        public Nullable<int> resultstatus { get; set; }
    }
}
