//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class lg_cwsz
    {
        public string brch { get; set; }
        public string fjhm { get; set; }
        public decimal cwks { get; set; }
        public decimal ksdm { get; set; }
        public decimal cwxb { get; set; }
        public decimal cwfy { get; set; }
        public decimal icu { get; set; }
        public decimal jcpb { get; set; }
        public Nullable<decimal> zyh { get; set; }
    }
}
