//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class MQMS_WH_ZDYJ02
    {
        public decimal SBXH { get; set; }
        public decimal ZDZH { get; set; }
        public decimal JBLB { get; set; }
        public decimal JBXH { get; set; }
        public string JBDM { get; set; }
        public string JBMC { get; set; }
    }
}
