//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class MQMS_JYSQYXYS
    {
        public decimal JLXH { get; set; }
        public string SQDH { get; set; }
        public decimal XMXH { get; set; }
        public string XMMC { get; set; }
        public decimal YSSB { get; set; }
        public decimal JYDM { get; set; }
        public Nullable<decimal> YXSD { get; set; }
        public Nullable<decimal> YXLX { get; set; }
    }
}
