//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class mrqc_zgtz
    {
        public decimal tzid { get; set; }
        public Nullable<decimal> zgks { get; set; }
        public Nullable<System.DateTime> tzrq { get; set; }
        public Nullable<System.DateTime> jzrq { get; set; }
        public Nullable<decimal> msgid { get; set; }
        public Nullable<decimal> ywlb { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
