//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class mrqc_syml
    {
        public decimal mlid { get; set; }
        public decimal bllb { get; set; }
        public string sxjsid { get; set; }
        public string sxjsmc { get; set; }
        public string syjsid { get; set; }
        public string syjsmc { get; set; }
        public Nullable<decimal> sysx { get; set; }
        public Nullable<decimal> tqtxsj { get; set; }
        public string zrys { get; set; }
        public Nullable<decimal> wsyqxid { get; set; }
        public Nullable<decimal> cssyqxid { get; set; }
        public decimal zxbz { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
