//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class mrqc_pf02
    {
        public decimal jlxh { get; set; }
        public decimal pfxh { get; set; }
        public decimal qxid { get; set; }
        public decimal qxqz { get; set; }
        public decimal qxsl { get; set; }
        public decimal kffs { get; set; }
        public decimal dxfj { get; set; }
        public Nullable<decimal> zrks { get; set; }
        public string zrys { get; set; }
        public string bzxx { get; set; }
        public decimal kfgl { get; set; }
    }
}
