//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ms_brda20160707
    {
        public decimal brid { get; set; }
        public string mzhm { get; set; }
        public string brxm { get; set; }
        public string fyzh { get; set; }
        public string sfzh { get; set; }
        public Nullable<decimal> brxz { get; set; }
        public Nullable<decimal> brxb { get; set; }
        public Nullable<System.DateTime> csny { get; set; }
        public Nullable<decimal> hyzk { get; set; }
        public Nullable<decimal> zydm { get; set; }
        public Nullable<decimal> mzdm { get; set; }
        public Nullable<decimal> xxdm { get; set; }
        public Nullable<decimal> gmyw { get; set; }
        public Nullable<decimal> dwxh { get; set; }
        public string dwmc { get; set; }
        public string dwdh { get; set; }
        public string dwyb { get; set; }
        public string hkdz { get; set; }
        public string jtdh { get; set; }
        public string hkyb { get; set; }
        public Nullable<decimal> jzcs { get; set; }
        public Nullable<System.DateTime> jzrq { get; set; }
        public Nullable<System.DateTime> czrq { get; set; }
        public string jzkh { get; set; }
        public string grbh_yh { get; set; }
        public string bxh_yh { get; set; }
        public Nullable<decimal> rylb_yh { get; set; }
        public string lbmc_yh { get; set; }
        public Nullable<decimal> gwyjb { get; set; }
        public string ybkh { get; set; }
        public string icmw { get; set; }
        public string icxx { get; set; }
        public string ickh { get; set; }
        public string grbh { get; set; }
        public string nbkh { get; set; }
        public string bxhm { get; set; }
        public string cabzlx { get; set; }
        public string cajzlx { get; set; }
        public string cahmlx { get; set; }
        public string caxsbz { get; set; }
        public string cazh { get; set; }
        public string cazjlx { get; set; }
        public string cayldh { get; set; }
        public Nullable<decimal> cadxbz { get; set; }
        public string bxlx { get; set; }
        public Nullable<decimal> grzhye { get; set; }
        public string kzhm { get; set; }
        public string rylxmc { get; set; }
        public string xzqydm { get; set; }
        public string rylb_fy { get; set; }
        public Nullable<decimal> jdksdm { get; set; }
        public Nullable<System.DateTime> jdrq { get; set; }
        public Nullable<int> dwbz { get; set; }
        public Nullable<int> drpb { get; set; }
        public Nullable<int> kdpb { get; set; }
        public string blbbh { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> qybr { get; set; }
        public Nullable<decimal> dasc { get; set; }
        public string cardxh { get; set; }
        public Nullable<decimal> jkda { get; set; }
        public string bllx { get; set; }
        public string dbz { get; set; }
        public string dyzt { get; set; }
        public string cardno { get; set; }
        public string rylb { get; set; }
    }
}
