//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ms_cfdp
    {
        public decimal dpsb { get; set; }
        public decimal cfsb { get; set; }
        public Nullable<decimal> yppz { get; set; }
        public Nullable<decimal> kjy { get; set; }
        public Nullable<decimal> zsj { get; set; }
        public Nullable<decimal> jbyw { get; set; }
        public Nullable<decimal> cfje { get; set; }
        public Nullable<decimal> hlpb { get; set; }
        public string wtdm { get; set; }
        public string czwt { get; set; }
        public string cfzw { get; set; }
        public string ysfx { get; set; }
        public string dpgh { get; set; }
        public Nullable<System.DateTime> dprq { get; set; }
        public string sxgh { get; set; }
        public Nullable<System.DateTime> sxrq { get; set; }
        public Nullable<decimal> dppb { get; set; }
    
        public virtual ms_cfdprz ms_cfdprz { get; set; }
    }
}
