//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ms_hzrb_tj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ms_hzrb_tj()
        {
            this.ms_rbmx_tj = new HashSet<ms_rbmx_tj>();
            this.ms_xzmx_tj = new HashSet<ms_xzmx_tj>();
        }
    
        public string czgh { get; set; }
        public System.DateTime jzrq { get; set; }
        public string qzpj { get; set; }
        public decimal zjje { get; set; }
        public decimal xjje { get; set; }
        public decimal zpje { get; set; }
        public decimal zfzf { get; set; }
        public decimal qtys { get; set; }
        public decimal hbwc { get; set; }
        public Nullable<System.DateTime> hzrq { get; set; }
        public decimal fpzs { get; set; }
        public decimal mzlb { get; set; }
        public string zffp { get; set; }
        public Nullable<decimal> zfje { get; set; }
        public string tffp { get; set; }
        public Nullable<decimal> tfje { get; set; }
        public Nullable<decimal> jrzf { get; set; }
        public Nullable<decimal> rlje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ms_rbmx_tj> ms_rbmx_tj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ms_xzmx_tj> ms_xzmx_tj { get; set; }
    }
}
