//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ms_nyzdbg
    {
        public int jlxh { get; set; }
        public string sf { get; set; }
        public string xs { get; set; }
        public string xz { get; set; }
        public string xc { get; set; }
        public Nullable<decimal> kpxh { get; set; }
        public string sfzh { get; set; }
        public string brxm { get; set; }
        public Nullable<int> xb { get; set; }
        public string nl { get; set; }
        public string zdnymc { get; set; }
        public string zdnyzl { get; set; }
        public Nullable<int> zdlx1 { get; set; }
        public Nullable<int> zdlx2 { get; set; }
        public Nullable<int> zdlx3 { get; set; }
        public Nullable<int> zdlx4 { get; set; }
        public Nullable<int> zy { get; set; }
        public Nullable<int> hz { get; set; }
        public Nullable<int> sw { get; set; }
        public Nullable<System.DateTime> zdrq { get; set; }
        public Nullable<System.DateTime> swrq { get; set; }
        public string bz { get; set; }
        public string zddw { get; set; }
        public string dwfzr { get; set; }
        public string tbr { get; set; }
        public Nullable<System.DateTime> tbrq { get; set; }
        public Nullable<int> zfpb { get; set; }
    }
}
