//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class MSG_MESSAGE01
    {
        public decimal MSGID { get; set; }
        public decimal JGID { get; set; }
        public Nullable<decimal> MSGTYPE { get; set; }
        public decimal MSGCODE { get; set; }
        public string MSGSUM { get; set; }
        public string MSGTEXT { get; set; }
        public string SENDUSER { get; set; }
        public System.DateTime SENDTIME { get; set; }
        public string RETRIEVEUSER { get; set; }
        public Nullable<System.DateTime> RETRIEVETIME { get; set; }
        public decimal MSGSTATUS { get; set; }
        public decimal ONLYONE { get; set; }
        public string BRID { get; set; }
        public Nullable<decimal> YWZ { get; set; }
        public string YWID1 { get; set; }
        public string YWID2 { get; set; }
        public string YWID3 { get; set; }
        public string YWID4 { get; set; }
        public string XXCS { get; set; }
        public string SMSTEL { get; set; }
    }
}
