//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class mz_exzlsb
    {
        public decimal jlxh { get; set; }
        public Nullable<int> bqgz { get; set; }
        public Nullable<decimal> jzxh { get; set; }
        public decimal brid { get; set; }
        public string mzhm { get; set; }
        public string sfzh { get; set; }
        public Nullable<decimal> kpbh { get; set; }
        public string icdbm { get; set; }
        public string icd0bm { get; set; }
        public string brxm { get; set; }
        public Nullable<int> xb { get; set; }
        public Nullable<System.DateTime> csny { get; set; }
        public string zy { get; set; }
        public string jtgz { get; set; }
        public string mz { get; set; }
        public string jtdh { get; set; }
        public string gzdw { get; set; }
        public string hkdzs { get; set; }
        public string hkdzs2 { get; set; }
        public string hkdzx { get; set; }
        public string hkdzxz { get; set; }
        public string hkdzc { get; set; }
        public string xdzs { get; set; }
        public string xdzs2 { get; set; }
        public string xdzx { get; set; }
        public string xdzxz { get; set; }
        public string xdzc { get; set; }
        public string xdzmph { get; set; }
        public string zd { get; set; }
        public string bllx { get; set; }
        public string blh { get; set; }
        public string qzsqbt { get; set; }
        public string qzsqbn { get; set; }
        public string qzsqbm { get; set; }
        public Nullable<int> qzsqb { get; set; }
        public Nullable<System.DateTime> sczdrq { get; set; }
        public Nullable<int> zddw { get; set; }
        public string bkdw { get; set; }
        public string bkys { get; set; }
        public Nullable<System.DateTime> bkrq { get; set; }
        public Nullable<System.DateTime> swrq { get; set; }
        public string swyy { get; set; }
        public string yzd { get; set; }
        public Nullable<System.DateTime> yzdrq { get; set; }
        public Nullable<int> lc { get; set; }
        public Nullable<int> xxct { get; set; }
        public Nullable<int> sssj { get; set; }
        public Nullable<int> shmy { get; set; }
        public Nullable<int> xbx { get; set; }
        public Nullable<int> bljf { get; set; }
        public Nullable<int> blyf { get; set; }
        public Nullable<int> sjbl { get; set; }
        public Nullable<int> bx { get; set; }
        public Nullable<int> swbfb { get; set; }
        public Nullable<int> dybz { get; set; }
        public Nullable<int> bgklb { get; set; }
        public string icd9 { get; set; }
        public Nullable<int> bqgzbr { get; set; }
        public Nullable<int> sznl { get; set; }
        public string czhkxxdz { get; set; }
        public string icd0 { get; set; }
        public string m { get; set; }
        public string dlw { get; set; }
        public string zgzddw { get; set; }
        public string bkdws { get; set; }
        public string bkdwx { get; set; }
        public string swyy2 { get; set; }
        public string swicd10 { get; set; }
        public string swicdmc { get; set; }
        public string bszy { get; set; }
        public string zyhm { get; set; }
        public Nullable<decimal> zgbz { get; set; }
    }
}
