//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class omr_bl01
    {
        public decimal blbh { get; set; }
        public decimal jzxh { get; set; }
        public decimal brid { get; set; }
        public decimal bllx { get; set; }
        public decimal bllb { get; set; }
        public string blmc { get; set; }
        public Nullable<decimal> dllb { get; set; }
        public string dlj { get; set; }
        public Nullable<decimal> mblb { get; set; }
        public Nullable<decimal> mbbh { get; set; }
        public Nullable<System.DateTime> jlsj { get; set; }
        public System.DateTime cjsj { get; set; }
        public Nullable<System.DateTime> wcsj { get; set; }
        public string sxys { get; set; }
        public Nullable<decimal> sxks { get; set; }
        public Nullable<decimal> brks { get; set; }
        public Nullable<decimal> blzt { get; set; }
        public Nullable<decimal> sybz { get; set; }
        public Nullable<decimal> bzmbbh { get; set; }
        public Nullable<decimal> blbbz { get; set; }
        public Nullable<decimal> blpf { get; set; }
        public Nullable<decimal> zzdy { get; set; }
        public Nullable<decimal> ptid { get; set; }
        public string blnr_txt { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
