//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class omr_pfmx
    {
        public decimal pfxh { get; set; }
        public string blbh { get; set; }
        public decimal pfxm { get; set; }
        public string pfqx { get; set; }
        public Nullable<decimal> qxkf { get; set; }
        public string qxms { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
