//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pd_dltz
    {
        public decimal jlxh { get; set; }
        public decimal dlid { get; set; }
        public decimal rdid { get; set; }
        public decimal pdhm { get; set; }
        public string pdcy { get; set; }
        public decimal mddl { get; set; }
        public decimal czlb { get; set; }
        public System.DateTime czsj { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
