//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pd_pdhm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pd_pdhm()
        {
            this.pd_yyhm = new HashSet<pd_yyhm>();
        }
    
        public decimal hmid { get; set; }
        public string hmbh { get; set; }
        public string hmmc { get; set; }
        public string hmjc { get; set; }
        public decimal hmlb { get; set; }
        public decimal hmcd { get; set; }
        public System.DateTime dqrq { get; set; }
        public decimal dqhm { get; set; }
        public decimal yyhm { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> ZBLB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pd_yyhm> pd_yyhm { get; set; }
    }
}
