//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class PDJK_DLDY_JCXM
    {
        public decimal JLXH { get; set; }
        public decimal JCXM { get; set; }
        public decimal JGID { get; set; }
        public decimal DLID { get; set; }
        public decimal KSDM { get; set; }
        public Nullable<decimal> SBDJ { get; set; }
    }
}
