//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class price_i_itemprice
    {
        public Nullable<int> yiyuanjb { get; set; }
        public Nullable<decimal> xiangmujj { get; set; }
        public Nullable<decimal> shangfubl { get; set; }
        public Nullable<decimal> xiafubl { get; set; }
        public string wenjianbm { get; set; }
        public string dayinbm { get; set; }
        public string jiamim_mac { get; set; }
        public string xiangmumc { get; set; }
        public string pinyinm { get; set; }
        public string xiangmunh { get; set; }
        public string qitanr { get; set; }
        public string jijiadw { get; set; }
        public string shuoming { get; set; }
        public string xiangmulb { get; set; }
        public Nullable<int> zhuangtai { get; set; }
        public Nullable<int> jijiaxgqx { get; set; }
        public string caozuorq { get; set; }
        public string caozuor { get; set; }
        public string zhixingrq { get; set; }
        public string xiangmubm { get; set; }
        public Nullable<decimal> yiyuandj { get; set; }
        public string piaojuflbm { get; set; }
        public string piaojuflmc { get; set; }
        public Nullable<decimal> zfpb { get; set; }
    }
}
