//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pt_information
    {
        public string jgdm { get; set; }
        public string kh { get; set; }
        public string klx { get; set; }
        public string sfbslb { get; set; }
        public string sfbshm { get; set; }
        public string xm { get; set; }
        public Nullable<System.DateTime> csrq { get; set; }
        public string xbdm { get; set; }
        public string mzdm { get; set; }
        public string gjdm { get; set; }
        public string hyzk { get; set; }
        public string zydm { get; set; }
        public string gzdwmc { get; set; }
        public string gzdwdz { get; set; }
        public string gzddyb { get; set; }
        public string hzdz { get; set; }
        public Nullable<decimal> hzdzdyb { get; set; }
        public string brhkdz { get; set; }
        public string lxdhlb { get; set; }
        public string lxdhlbdm { get; set; }
        public string lxdhhm { get; set; }
        public string lxrxm { get; set; }
        public string lxryhzgx { get; set; }
        public string lxrdz { get; set; }
        public string lxrdh { get; set; }
        public string yl1 { get; set; }
        public string yl2 { get; set; }
        public decimal scbz { get; set; }
    }
}
