//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pt_labreport
    {
        public string jgdm { get; set; }
        public string jzlsh { get; set; }
        public string jybgdh { get; set; }
        public Nullable<decimal> brbslb { get; set; }
        public string jybgddm { get; set; }
        public string jybgdmc { get; set; }
        public string shysgh { get; set; }
        public string shysxm { get; set; }
        public string bgysgh { get; set; }
        public string bgysxm { get; set; }
        public string sqysgh { get; set; }
        public string sqysxm { get; set; }
        public string bz { get; set; }
        public string jybgdjg { get; set; }
        public string sqksdm { get; set; }
        public string shysgh2 { get; set; }
        public Nullable<System.DateTime> sqrq { get; set; }
        public string cjbw { get; set; }
        public Nullable<System.DateTime> ybjssj { get; set; }
        public Nullable<System.DateTime> cjsj { get; set; }
        public Nullable<decimal> jzbz { get; set; }
        public Nullable<decimal> yebz { get; set; }
        public string ybzt { get; set; }
        public string jcsbyqmc { get; set; }
        public string bblbdm { get; set; }
        public Nullable<System.DateTime> bgrq { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public decimal scbz { get; set; }
    }
}
