//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class pt_medicinerely
    {
        public string jgdm { get; set; }
        public string jzlsh { get; set; }
        public string yllsh { get; set; }
        public string ydwbm { get; set; }
        public string ydwmc { get; set; }
        public string pl { get; set; }
        public string jl { get; set; }
        public Nullable<decimal> jlly { get; set; }
        public Nullable<decimal> ljsysj { get; set; }
        public Nullable<System.DateTime> jlsj { get; set; }
        public decimal scbz { get; set; }
    }
}
