//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class py_zwsx
    {
        public decimal sxid { get; set; }
        public string sxmc { get; set; }
        public Nullable<decimal> sxys { get; set; }
        public decimal zwsx { get; set; }
    }
}
