//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class rs_gzffmx2
    {
        public string ssnf { get; set; }
        public string ssyf { get; set; }
        public string ygdm { get; set; }
        public string jbgz { get; set; }
        public string yf01 { get; set; }
        public string yf02 { get; set; }
        public string yf03 { get; set; }
        public string yf04 { get; set; }
        public string yf05 { get; set; }
        public string yf06 { get; set; }
        public string yf07 { get; set; }
        public string yf08 { get; set; }
        public string yf09 { get; set; }
        public string yf10 { get; set; }
        public string yf11 { get; set; }
        public string yf12 { get; set; }
        public string yf13 { get; set; }
        public string yf14 { get; set; }
        public string yf15 { get; set; }
        public string kc01 { get; set; }
        public string kc02 { get; set; }
        public string kc03 { get; set; }
        public string kc04 { get; set; }
        public string kc05 { get; set; }
        public string kc06 { get; set; }
        public string kc07 { get; set; }
        public string kqkc { get; set; }
        public string sds { get; set; }
        public string dkbx { get; set; }
        public string qtyf { get; set; }
        public string qtkc { get; set; }
        public string xm01 { get; set; }
        public string xm02 { get; set; }
        public string xm03 { get; set; }
        public string xm04 { get; set; }
        public string xm05 { get; set; }
        public string xm06 { get; set; }
        public string xm07 { get; set; }
        public string xm08 { get; set; }
        public string xm09 { get; set; }
        public string xm10 { get; set; }
        public string xm11 { get; set; }
        public string xm12 { get; set; }
        public string xm13 { get; set; }
        public string xm14 { get; set; }
        public string xm15 { get; set; }
        public string xm16 { get; set; }
        public string xm17 { get; set; }
        public string xm18 { get; set; }
        public string xm19 { get; set; }
        public string xm20 { get; set; }
    }
}
