//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class rs_gzxm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rs_gzxm()
        {
            this.rs_gzhd = new HashSet<rs_gzhd>();
            this.rs_gztz = new HashSet<rs_gztz>();
        }
    
        public decimal xmbm { get; set; }
        public string xmmc { get; set; }
        public Nullable<int> plxh { get; set; }
        public Nullable<decimal> qsje { get; set; }
        public string jjbz { get; set; }
        public string jsbz { get; set; }
        public string jsgs { get; set; }
        public string gsms { get; set; }
        public string zfbz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_gzhd> rs_gzhd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_gztz> rs_gztz { get; set; }
    }
}
