//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class rs_kqjl
    {
        public decimal kqnf { get; set; }
        public decimal kqyf { get; set; }
        public string ygdm { get; set; }
        public Nullable<decimal> cdcs { get; set; }
        public Nullable<decimal> ztcs { get; set; }
        public Nullable<decimal> kgts { get; set; }
        public Nullable<decimal> gsj { get; set; }
        public Nullable<decimal> gxj { get; set; }
        public Nullable<decimal> bj { get; set; }
        public Nullable<decimal> shj { get; set; }
        public Nullable<decimal> hj { get; set; }
        public Nullable<decimal> cj { get; set; }
        public Nullable<decimal> sj { get; set; }
        public Nullable<decimal> tqj { get; set; }
        public Nullable<decimal> bxj { get; set; }
        public Nullable<decimal> cxj { get; set; }
        public Nullable<decimal> jsj { get; set; }
        public Nullable<decimal> hjj { get; set; }
        public Nullable<decimal> cjj { get; set; }
        public Nullable<decimal> qtj { get; set; }
        public Nullable<decimal> dxts { get; set; }
        public Nullable<decimal> sxjb { get; set; }
        public Nullable<decimal> ycqs { get; set; }
        public Nullable<decimal> scqs { get; set; }
        public Nullable<decimal> gyqj { get; set; }
        public Nullable<decimal> zjqj { get; set; }
        public string fzr { get; set; }
        public string tbr { get; set; }
        public Nullable<System.DateTime> tbrq { get; set; }
    
        public virtual rs_jbxx rs_jbxx { get; set; }
    }
}
