//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class rs_lsgda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rs_lsgda()
        {
            this.rs_lsggz = new HashSet<rs_lsggz>();
        }
    
        public int lsgdm { get; set; }
        public string ksdm { get; set; }
        public string xm { get; set; }
        public Nullable<int> xb { get; set; }
        public Nullable<int> mz { get; set; }
        public Nullable<int> jg { get; set; }
        public Nullable<System.DateTime> csrq { get; set; }
        public string zz { get; set; }
        public string sfzh { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public Nullable<System.DateTime> lyrq { get; set; }
        public string jszh { get; set; }
        public string zzzh { get; set; }
        public Nullable<System.DateTime> sgrq { get; set; }
        public Nullable<decimal> jbgz { get; set; }
        public Nullable<decimal> qtjt { get; set; }
        public string ryzt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rs_lsggz> rs_lsggz { get; set; }
    }
}
