//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class rs_txsp
    {
        public string ygdm { get; set; }
        public Nullable<int> ygnl { get; set; }
        public Nullable<System.DateTime> cjgzsj { get; set; }
        public string txzl { get; set; }
        public Nullable<System.DateTime> txsj { get; set; }
        public Nullable<System.DateTime> fcdagzsj { get; set; }
        public Nullable<int> jfns { get; set; }
        public Nullable<int> jfys { get; set; }
        public Nullable<decimal> stjfns { get; set; }
        public Nullable<decimal> stjfys { get; set; }
        public Nullable<decimal> snpjgz { get; set; }
        public Nullable<decimal> ybfylj { get; set; }
        public Nullable<decimal> qtdy { get; set; }
        public Nullable<decimal> jcylj { get; set; }
        public Nullable<decimal> grzhylj { get; set; }
        public Nullable<decimal> gdxylj { get; set; }
        public Nullable<decimal> hytjxbt { get; set; }
        public string bdwyj { get; set; }
        public string bdwjbr { get; set; }
        public Nullable<System.DateTime> bdwsprq { get; set; }
        public string zgbmyj { get; set; }
        public string zgbmjbr { get; set; }
        public Nullable<System.DateTime> zgbmsprq { get; set; }
        public string sbjgyj { get; set; }
        public string sbjgjbr { get; set; }
        public Nullable<System.DateTime> sbjgsprq { get; set; }
        public Nullable<System.DateTime> sptxrq { get; set; }
        public Nullable<decimal> spjbylj { get; set; }
        public string spjg { get; set; }
        public string jbr { get; set; }
        public Nullable<System.DateTime> sprq { get; set; }
    }
}
