//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sb_jksq
    {
        public decimal sqdh { get; set; }
        public string kfsb { get; set; }
        public string zgdw { get; set; }
        public string jkdw { get; set; }
        public string address { get; set; }
        public string jbr { get; set; }
        public string phone { get; set; }
        public string zip { get; set; }
        public string htdw { get; set; }
        public string cpyt { get; set; }
        public Nullable<decimal> myfs { get; set; }
        public Nullable<decimal> whly { get; set; }
        public string bgka { get; set; }
        public decimal zcxh { get; set; }
        public string sshy { get; set; }
        public Nullable<decimal> sqsl { get; set; }
        public Nullable<decimal> xjpb { get; set; }
        public string hgbh { get; set; }
        public Nullable<decimal> manu { get; set; }
        public Nullable<decimal> sellor { get; set; }
        public string off_advi { get; set; }
        public System.DateTime sqrq { get; set; }
        public Nullable<System.DateTime> sprq { get; set; }
        public string czgh { get; set; }
        public string spgh { get; set; }
        public Nullable<decimal> spbz { get; set; }
        public string bzxx { get; set; }
    }
}
