//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sb_jjjl
    {
        public decimal sbxh { get; set; }
        public string kfsb { get; set; }
        public string jlbh { get; set; }
        public string yjd { get; set; }
        public string xjd { get; set; }
        public decimal jjdh { get; set; }
        public System.DateTime jjrq { get; set; }
        public string czgh { get; set; }
    
        public virtual sb_jjd sb_jjd { get; set; }
    }
}
