//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sb_pmjh
    {
        public decimal zbxh { get; set; }
        public System.DateTime pmrq { get; set; }
        public string kfsb { get; set; }
        public string wxry { get; set; }
        public string czgh { get; set; }
        public Nullable<decimal> jhzt { get; set; }
        public Nullable<decimal> wxdh { get; set; }
    }
}
