//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class SDCC_YHCS
    {
        public decimal CSBH { get; set; }
        public decimal JGID { get; set; }
        public decimal GSJB { get; set; }
        public string GSDX { get; set; }
        public string CSMC { get; set; }
        public string CSQZ { get; set; }
        public string CSBZ { get; set; }
    }
}
