//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sm_ssfy
    {
        public decimal fybh { get; set; }
        public Nullable<decimal> ssbh { get; set; }
        public Nullable<decimal> zyh { get; set; }
        public string fymc { get; set; }
        public Nullable<decimal> fylx { get; set; }
        public Nullable<decimal> fyxh { get; set; }
        public Nullable<decimal> fyxm { get; set; }
        public Nullable<decimal> ypcd { get; set; }
        public Nullable<decimal> fysl { get; set; }
        public Nullable<decimal> fydj { get; set; }
        public Nullable<decimal> zfbl { get; set; }
        public Nullable<System.DateTime> jfrq { get; set; }
        public Nullable<System.DateTime> jzrq { get; set; }
        public Nullable<decimal> fyks { get; set; }
        public Nullable<decimal> fybq { get; set; }
        public Nullable<decimal> zxks { get; set; }
        public string ysgh { get; set; }
        public string jfgh { get; set; }
        public string jzgh { get; set; }
        public Nullable<decimal> JZBZ { get; set; }
        public Nullable<decimal> zjje { get; set; }
        public Nullable<decimal> zfje { get; set; }
        public Nullable<decimal> rkbz { get; set; }
        public string ZTMC { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> JLXH { get; set; }
    
        public virtual sm_ssap sm_ssap { get; set; }
    }
}
