//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class sms_dxfs
    {
        public decimal jlxh { get; set; }
        public System.DateTime jlsj { get; set; }
        public string telnumber { get; set; }
        public string send_name { get; set; }
        public string template { get; set; }
        public string xxt { get; set; }
        public decimal fscs { get; set; }
        public decimal fsbz { get; set; }
        public Nullable<System.DateTime> fssj { get; set; }
        public string glid { get; set; }
        public Nullable<decimal> brid { get; set; }
        public Nullable<decimal> brlb { get; set; }
    }
}
