//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class tj_bqbb
    {
        public decimal ksdm { get; set; }
        public System.DateTime tjrq { get; set; }
        public Nullable<decimal> kybc { get; set; }
        public Nullable<decimal> yyrs { get; set; }
        public Nullable<decimal> ryrs { get; set; }
        public Nullable<decimal> tkzr { get; set; }
        public Nullable<decimal> cyrs { get; set; }
        public Nullable<decimal> zyrs { get; set; }
        public Nullable<decimal> hzrs { get; set; }
        public Nullable<decimal> wyrs { get; set; }
        public Nullable<decimal> swrs { get; set; }
        public Nullable<decimal> qtrs { get; set; }
        public Nullable<decimal> zwtk { get; set; }
        public Nullable<decimal> lyrs { get; set; }
        public Nullable<decimal> rcrc { get; set; }
        public Nullable<decimal> yngr { get; set; }
        public Nullable<decimal> bzrs { get; set; }
        public Nullable<decimal> bwrs { get; set; }
        public Nullable<decimal> pkrs { get; set; }
        public Nullable<decimal> qjrc { get; set; }
        public Nullable<decimal> cgrc { get; set; }
        public Nullable<decimal> wxrc { get; set; }
        public Nullable<decimal> qjsw { get; set; }
        public Nullable<decimal> sxrc { get; set; }
        public Nullable<decimal> sxfy { get; set; }
        public Nullable<decimal> syrc { get; set; }
        public Nullable<decimal> syfy { get; set; }
        public Nullable<decimal> pbzc { get; set; }
        public Nullable<decimal> zycr { get; set; }
        public Nullable<decimal> brcr { get; set; }
        public Nullable<decimal> cyfy { get; set; }
        public Nullable<decimal> brfy { get; set; }
        public Nullable<decimal> thhm { get; set; }
        public Nullable<decimal> hdrs { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> JLXH { get; set; }
    }
}
