//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class tj_mmbb
    {
        public decimal ksdm { get; set; }
        public System.DateTime tjrq { get; set; }
        public decimal mzdm { get; set; }
        public decimal mzlb { get; set; }
        public Nullable<decimal> mzrc { get; set; }
        public Nullable<decimal> mzsw { get; set; }
        public Nullable<decimal> wzmz { get; set; }
        public Nullable<decimal> cgrc { get; set; }
        public Nullable<decimal> wxrc { get; set; }
        public Nullable<decimal> swrc { get; set; }
        public Nullable<decimal> mzsr { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> JLXH { get; set; }
    }
}
