//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class v_ka25
    {
        public string aka080 { get; set; }
        public string aka081 { get; set; }
        public string aka060 { get; set; }
        public string aka061 { get; set; }
        public string aka062 { get; set; }
        public string aka066 { get; set; }
        public string aka067 { get; set; }
        public string aka068 { get; set; }
        public decimal aka083 { get; set; }
        public string aka084 { get; set; }
        public string aka085 { get; set; }
        public string aka070 { get; set; }
        public Nullable<decimal> aka071 { get; set; }
        public Nullable<decimal> aka072 { get; set; }
        public string aka073 { get; set; }
        public string aka074 { get; set; }
        public string aka075 { get; set; }
        public string aka064 { get; set; }
        public string aka076 { get; set; }
        public string aka077 { get; set; }
        public string aka078 { get; set; }
        public Nullable<decimal> aka079 { get; set; }
        public Nullable<decimal> aka086 { get; set; }
        public Nullable<decimal> aka087 { get; set; }
        public Nullable<decimal> aka088 { get; set; }
        public Nullable<decimal> aka089 { get; set; }
        public string aae011 { get; set; }
        public System.DateTime aae036 { get; set; }
        public string aae013 { get; set; }
        public string aka063 { get; set; }
        public string akb037 { get; set; }
        public string aka093 { get; set; }
        public string aka094 { get; set; }
        public string aka095 { get; set; }
        public string aka096 { get; set; }
        public string aka097 { get; set; }
        public string aka098 { get; set; }
        public string aka099 { get; set; }
        public string aka100 { get; set; }
        public string aka113 { get; set; }
        public System.DateTime aka090 { get; set; }
        public Nullable<System.DateTime> aka091 { get; set; }
        public string aka065 { get; set; }
        public double xzxh { get; set; }
    }
}
