//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wh_gnmk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wh_gnmk()
        {
            this.wh_gnyh = new HashSet<wh_gnyh>();
        }
    
        public decimal gnbh { get; set; }
        public string gnbm { get; set; }
        public string gnmc { get; set; }
        public decimal sjbh { get; set; }
        public string gnck { get; set; }
        public string tbmc { get; set; }
        public Nullable<int> gnlb { get; set; }
        public string gnbz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wh_gnyh> wh_gnyh { get; set; }
    }
}
