//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wh_menu
    {
        public int xtsb { get; set; }
        public string cdmc { get; set; }
        public int cdsx { get; set; }
        public string sjmc { get; set; }
        public string cdwb { get; set; }
        public int cdcc { get; set; }
    }
}
