//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class WXYB_ZFBR_XXSC
    {
        public string FPHM { get; set; }
        public decimal JZLX { get; set; }
        public decimal JZXX_SCBZ { get; set; }
        public decimal JZMX_SCBZ { get; set; }
    }
}
