//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class WXYKT_JYMXXZ
    {
        public string PTLSH { get; set; }
        public string ZXLSH { get; set; }
        public string XZDM { get; set; }
        public string JYLSH { get; set; }
        public string BXLX { get; set; }
        public string GRBH { get; set; }
        public string BRXM { get; set; }
        public Nullable<System.DateTime> JSRQ { get; set; }
        public Nullable<decimal> FYZE { get; set; }
        public Nullable<decimal> ZFJE { get; set; }
        public Nullable<decimal> ZLJE { get; set; }
        public Nullable<decimal> ZYZF { get; set; }
        public Nullable<decimal> QFBZ { get; set; }
        public Nullable<decimal> BXJE { get; set; }
        public Nullable<decimal> XJJE { get; set; }
        public Nullable<decimal> TCJJ { get; set; }
        public Nullable<decimal> LNZH { get; set; }
        public Nullable<decimal> DNZH { get; set; }
        public Nullable<decimal> DBJZ { get; set; }
        public Nullable<decimal> GWBZ { get; set; }
        public Nullable<decimal> EYJJ { get; set; }
        public Nullable<decimal> LXJJ { get; set; }
        public Nullable<decimal> LMJJ { get; set; }
        public Nullable<decimal> BZJJ { get; set; }
        public Nullable<decimal> MZBZ { get; set; }
    }
}
