//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wz_bs02
    {
        public decimal mxbh { get; set; }
        public Nullable<decimal> djbh { get; set; }
        public Nullable<decimal> wpbh { get; set; }
        public Nullable<decimal> cjbh { get; set; }
        public string bsyy { get; set; }
        public decimal lsjg { get; set; }
        public decimal pfjg { get; set; }
        public decimal jhjg { get; set; }
        public decimal sqsl { get; set; }
        public decimal wpsl { get; set; }
        public decimal lsje { get; set; }
        public decimal pfje { get; set; }
        public decimal jhje { get; set; }
        public decimal jlxh { get; set; }
    
        public virtual wz_bs01 wz_bs01 { get; set; }
    }
}
