//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wz_db01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wz_db01()
        {
            this.wz_db02 = new HashSet<wz_db02>();
        }
    
        public decimal djbh { get; set; }
        public string lzdh { get; set; }
        public Nullable<decimal> ckck { get; set; }
        public Nullable<decimal> rkck { get; set; }
        public Nullable<System.DateTime> zdsj { get; set; }
        public string zdgh { get; set; }
        public Nullable<System.DateTime> cksj { get; set; }
        public string ckgh { get; set; }
        public Nullable<System.DateTime> rksj { get; set; }
        public string rkgh { get; set; }
        public string djzt { get; set; }
        public decimal sjkf_sqpb { get; set; }
        public decimal dbth { get; set; }
        public string djbz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wz_db02> wz_db02 { get; set; }
    }
}
