//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class wz_jh02
    {
        public decimal mxbh { get; set; }
        public decimal djbh { get; set; }
        public decimal wpbh { get; set; }
        public decimal cjbh { get; set; }
        public Nullable<decimal> kcsl { get; set; }
        public Nullable<decimal> dcsl { get; set; }
        public Nullable<decimal> wpdj { get; set; }
        public Nullable<decimal> jhsl { get; set; }
        public Nullable<decimal> spsl { get; set; }
        public string mxbz { get; set; }
        public decimal ygsl { get; set; }
    
        public virtual wz_jh01 wz_jh01 { get; set; }
    }
}
