//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yb_mzjs
    {
        public string fphm { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public string bxhm { get; set; }
        public string ryxz { get; set; }
        public string cbxz { get; set; }
        public Nullable<decimal> zfje { get; set; }
        public Nullable<decimal> jrjs { get; set; }
        public Nullable<decimal> kfje { get; set; }
        public Nullable<decimal> xjzf { get; set; }
        public Nullable<decimal> tczf { get; set; }
        public Nullable<decimal> jzje { get; set; }
        public Nullable<decimal> dbjj { get; set; }
        public Nullable<decimal> gwybz1 { get; set; }
        public Nullable<decimal> gwybz2 { get; set; }
        public string tsmz { get; set; }
        public Nullable<decimal> zfpb { get; set; }
        public Nullable<System.DateTime> zfrq { get; set; }
        public Nullable<decimal> gwybz { get; set; }
    }
}
