//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YF_KCRB
    {
        public decimal RBXH { get; set; }
        public decimal JGID { get; set; }
        public decimal YFSB { get; set; }
        public System.DateTime RBRQ { get; set; }
        public System.DateTime QSSJ { get; set; }
        public System.DateTime ZZSJ { get; set; }
        public Nullable<decimal> WCBZ { get; set; }
        public string BZXX { get; set; }
    }
}
