//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yf_kcmx
    {
        public decimal sbxh { get; set; }
        public decimal yfsb { get; set; }
        public decimal ckbh { get; set; }
        public decimal ypxh { get; set; }
        public decimal ypcd { get; set; }
        public string ypph { get; set; }
        public Nullable<System.DateTime> ypxq { get; set; }
        public decimal ypsl { get; set; }
        public decimal jybz { get; set; }
        public decimal lsjg { get; set; }
        public decimal pfjg { get; set; }
        public decimal jhjg { get; set; }
        public decimal lsje { get; set; }
        public decimal pfje { get; set; }
        public decimal jhje { get; set; }
        public Nullable<decimal> ykjh { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<System.DateTime> YWSJ { get; set; }
        public Nullable<decimal> JYYY { get; set; }
        public Nullable<decimal> KCLY { get; set; }
        public Nullable<decimal> YKKCSB { get; set; }
        public Nullable<decimal> YWLX { get; set; }
        public Nullable<decimal> YKPJ { get; set; }
        public Nullable<decimal> YKJJ { get; set; }
        public Nullable<decimal> YKLJ { get; set; }
    }
}
