//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yf_rbmx
    {
        public decimal yfsb { get; set; }
        public System.DateTime rbrq { get; set; }
        public decimal ypxh { get; set; }
        public decimal ypcd { get; set; }
        public Nullable<decimal> brsr { get; set; }
        public Nullable<decimal> brzc { get; set; }
        public Nullable<decimal> brjc { get; set; }
        public Nullable<decimal> yfbz { get; set; }
        public Nullable<decimal> JGID { get; set; }
    
        public virtual yf_yfrb yf_yfrb { get; set; }
    }
}
