//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YF_YPGG
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public decimal YFSB { get; set; }
        public decimal YPXH { get; set; }
        public string YFGG { get; set; }
        public Nullable<decimal> YFBZ { get; set; }
        public string YFDW { get; set; }
        public Nullable<decimal> MZSY { get; set; }
        public Nullable<decimal> ZYSY { get; set; }
        public Nullable<decimal> TBBZ { get; set; }
        public Nullable<decimal> ZFBZ { get; set; }
    }
}
