//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yj_bgmb02
    {
        public decimal sbxh { get; set; }
        public Nullable<decimal> mbxh { get; set; }
        public string nbmc { get; set; }
        public string dxmc { get; set; }
        public string dxlx { get; set; }
        public string dxqz { get; set; }
        public Nullable<decimal> hxzb { get; set; }
        public Nullable<decimal> zxzb { get; set; }
        public Nullable<decimal> dxkd { get; set; }
        public Nullable<decimal> dxgd { get; set; }
        public string dxys { get; set; }
        public string ssbg { get; set; }
        public Nullable<decimal> szhs { get; set; }
        public Nullable<decimal> szls { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
