//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YJ_BG01_JJHS
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public Nullable<decimal> YJXH { get; set; }
        public Nullable<decimal> MBXH { get; set; }
        public Nullable<decimal> MZZY { get; set; }
        public string TJHM { get; set; }
        public string BRHM { get; set; }
        public Nullable<decimal> ZYH { get; set; }
        public string BRXM { get; set; }
        public string BRXB { get; set; }
        public Nullable<decimal> BRNL { get; set; }
        public string SJYS { get; set; }
        public Nullable<decimal> SJKS { get; set; }
        public string JCYS { get; set; }
        public Nullable<decimal> JCKS { get; set; }
        public Nullable<System.DateTime> JCRQ { get; set; }
        public Nullable<decimal> XMXH { get; set; }
        public string XMMC { get; set; }
        public Nullable<decimal> HJJE { get; set; }
        public string ZDDM { get; set; }
        public string YQDH { get; set; }
        public string BBBM { get; set; }
        public string YJPH { get; set; }
        public Nullable<decimal> QXZX { get; set; }
        public Nullable<decimal> YJZX { get; set; }
    }
}
