//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yj_damb_old
    {
        public decimal jcks { get; set; }
        public string tjhm { get; set; }
        public string brhm { get; set; }
        public Nullable<decimal> zyh { get; set; }
        public string brxm { get; set; }
        public Nullable<decimal> brxb { get; set; }
        public string sjys { get; set; }
        public Nullable<decimal> sjks { get; set; }
        public string sjbm { get; set; }
        public string jcys { get; set; }
        public Nullable<System.DateTime> jcrq { get; set; }
        public Nullable<decimal> xmxh { get; set; }
        public string jcxm { get; set; }
        public decimal hjje { get; set; }
        public string jgbg { get; set; }
        public Nullable<decimal> xgpb { get; set; }
        public Nullable<decimal> mzzy { get; set; }
        public string bbbm { get; set; }
        public string zd1 { get; set; }
        public string zd2 { get; set; }
        public string zd3 { get; set; }
        public string zd4 { get; set; }
        public string yqdh { get; set; }
    }
}
