//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yj_zy02
    {
        public decimal sbxh { get; set; }
        public decimal yjxh { get; set; }
        public decimal ylxh { get; set; }
        public Nullable<decimal> xmlx { get; set; }
        public Nullable<decimal> yjzx { get; set; }
        public decimal yldj { get; set; }
        public decimal ylsl { get; set; }
        public Nullable<decimal> fygb { get; set; }
        public decimal zfbl { get; set; }
        public Nullable<decimal> yzxh { get; set; }
        public string tplj { get; set; }
        public string ZTMC { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public Nullable<decimal> JHH { get; set; }
        public Nullable<decimal> YEPB { get; set; }
    
        public virtual yj_zy01 yj_zy01 { get; set; }
    }
}
