//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YJYY_TZJL
    {
        public decimal JLXH { get; set; }
        public decimal JGID { get; set; }
        public decimal DXXH { get; set; }
        public System.DateTime KSRQ { get; set; }
        public System.DateTime JSRQ { get; set; }
        public decimal SWQYBZ { get; set; }
        public string SWKSSJ { get; set; }
        public string SWJSSJ { get; set; }
        public decimal SWQYJQS { get; set; }
        public decimal XWQYBZ { get; set; }
        public string XWKSSJ { get; set; }
        public string XWJSSJ { get; set; }
        public decimal XWQYJQS { get; set; }
        public decimal WSQYBZ { get; set; }
        public string WSKSSJ { get; set; }
        public string WSJSSJ { get; set; }
        public decimal WSQYJQS { get; set; }
        public decimal ZJXE { get; set; }
        public decimal ZZXE { get; set; }
        public decimal DHXE { get; set; }
        public Nullable<decimal> ZFPB { get; set; }
    }
}
