//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ykt_hz_jsjl
    {
        public string fphm { get; set; }
        public decimal jzlx { get; set; }
        public string yylsh { get; set; }
        public string zxlsh { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public string czgh { get; set; }
        public string yllb { get; set; }
        public string rylb { get; set; }
        public Nullable<decimal> zfpb { get; set; }
        public Nullable<System.DateTime> zfrq { get; set; }
        public string ywzq { get; set; }
        public string zfzq { get; set; }
        public string ybkh { get; set; }
        public string grbh { get; set; }
        public Nullable<decimal> zjje { get; set; }
        public Nullable<decimal> ybjj { get; set; }
        public Nullable<decimal> dnzh { get; set; }
        public Nullable<decimal> lnzh { get; set; }
        public Nullable<decimal> xjje { get; set; }
        public Nullable<decimal> tcjj { get; set; }
        public Nullable<decimal> dbjz { get; set; }
        public Nullable<decimal> shjz { get; set; }
        public Nullable<decimal> gwbz { get; set; }
        public Nullable<decimal> mzyf { get; set; }
        public Nullable<decimal> mzbz { get; set; }
        public Nullable<decimal> lzje { get; set; }
        public Nullable<decimal> zlje { get; set; }
        public Nullable<decimal> zfje { get; set; }
        public Nullable<decimal> zyqf { get; set; }
        public Nullable<decimal> mzqf { get; set; }
        public Nullable<decimal> mzlj { get; set; }
        public Nullable<decimal> zycs { get; set; }
        public Nullable<decimal> fdzf1 { get; set; }
        public Nullable<decimal> fdzf2 { get; set; }
        public Nullable<decimal> fdzf3 { get; set; }
        public Nullable<decimal> fdzf4 { get; set; }
        public Nullable<decimal> fdzf5 { get; set; }
        public Nullable<decimal> fdzf6 { get; set; }
        public string zflsh { get; set; }
        public string xzdm { get; set; }
        public string jylsh { get; set; }
        public Nullable<decimal> dnye { get; set; }
        public Nullable<decimal> lnye { get; set; }
    }
}
