//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YS_JBJL_XGJL
    {
        public decimal JLXH { get; set; }
        public Nullable<decimal> KSDM { get; set; }
        public string YGDM { get; set; }
        public Nullable<decimal> JBLX { get; set; }
        public Nullable<System.DateTime> JBSJ { get; set; }
        public Nullable<decimal> ZFBZ { get; set; }
        public Nullable<System.DateTime> SQSJ { get; set; }
        public string SQGH { get; set; }
        public decimal JGID { get; set; }
    }
}
