//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ys_mz_zt02
    {
        public decimal jlbh { get; set; }
        public decimal ztbh { get; set; }
        public decimal ypzh { get; set; }
        public decimal xmbh { get; set; }
        public string xmmc { get; set; }
        public decimal xmsl { get; set; }
        public decimal ycjl { get; set; }
        public string sypc { get; set; }
        public decimal mrcs { get; set; }
        public decimal yyts { get; set; }
        public decimal gytj { get; set; }
        public string bzmc { get; set; }
        public string ksdm { get; set; }
        public Nullable<decimal> plxh { get; set; }
    
        public virtual ys_mz_zt01 ys_mz_zt01 { get; set; }
    }
}
