//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class YS_MZ_BRXY
    {
        public decimal JLXH { get; set; }
        public decimal JZXH { get; set; }
        public decimal BRID { get; set; }
        public decimal SSYZ { get; set; }
        public decimal SZYZ { get; set; }
        public System.DateTime CLSJ { get; set; }
        public string CLGH { get; set; }
        public decimal XYQK { get; set; }
        public decimal CKSSY { get; set; }
        public decimal CKSZY { get; set; }
        public decimal JGID { get; set; }
    }
}
