//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ys_psjl
    {
        public decimal jlbh { get; set; }
        public string jzhm { get; set; }
        public string brbh { get; set; }
        public string ypdm { get; set; }
        public string ypmc { get; set; }
        public Nullable<decimal> psjg { get; set; }
        public decimal wcbz { get; set; }
        public string sqys { get; set; }
        public System.DateTime sqsj { get; set; }
        public string psys { get; set; }
        public Nullable<System.DateTime> pssj { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
