//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class ys_zt01
    {
        public decimal ztbh { get; set; }
        public string ztmc { get; set; }
        public decimal ztlb { get; set; }
        public decimal gslb { get; set; }
        public string gsdm { get; set; }
        public string pydm { get; set; }
        public string wbdm { get; set; }
        public string qtdm { get; set; }
        public decimal xmxq { get; set; }
    }
}
