//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yw_sjzk
    {
        public decimal nf { get; set; }
        public decimal yf { get; set; }
        public Nullable<decimal> pjvis { get; set; }
        public Nullable<decimal> pjdi { get; set; }
        public Nullable<decimal> gsdf { get; set; }
        public Nullable<decimal> xjjd { get; set; }
        public Nullable<decimal> ksjd { get; set; }
        public Nullable<decimal> gymy { get; set; }
        public string zbr { get; set; }
        public Nullable<System.DateTime> zbrq { get; set; }
        public Nullable<int> qrbz { get; set; }
    }
}
