//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yy_cpmx
    {
        public decimal cpxh { get; set; }
        public decimal cfbm { get; set; }
        public decimal cfsl { get; set; }
        public Nullable<decimal> cfsb { get; set; }
    
        public virtual yy_yycp_wh yy_yycp_wh { get; set; }
    }
}
