//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yy_xhzd
    {
        public decimal hdxh { get; set; }
        public decimal xhyy { get; set; }
        public Nullable<decimal> xhsl { get; set; }
    
        public virtual yy_hdzd yy_hdzd { get; set; }
    }
}
