//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yy_yycf_wh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yy_yycf_wh()
        {
            this.yy_swcf = new HashSet<yy_swcf>();
        }
    
        public decimal cfxh { get; set; }
        public string cfmc { get; set; }
        public string cfdm { get; set; }
        public string cfdw { get; set; }
        public string cfgs { get; set; }
        public Nullable<decimal> gssy { get; set; }
        public Nullable<decimal> flpb { get; set; }
        public string pydm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yy_swcf> yy_swcf { get; set; }
    }
}
