//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yz_fyxx
    {
        public decimal jlxh { get; set; }
        public System.DateTime hzrq { get; set; }
        public decimal kslb { get; set; }
        public decimal ksdm { get; set; }
        public string ysdm { get; set; }
        public decimal jbxh { get; set; }
        public decimal brxz { get; set; }
        public decimal fylx { get; set; }
        public decimal fyxm { get; set; }
        public decimal fyxh { get; set; }
        public decimal fysl { get; set; }
        public decimal fyje { get; set; }
        public decimal tjfs { get; set; }
        public decimal jhje { get; set; }
        public decimal pfje { get; set; }
        public decimal lsje { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
