//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class yz_ykkc
    {
        public System.DateTime hzrq { get; set; }
        public decimal xtsb { get; set; }
        public decimal ypxh { get; set; }
        public decimal ypcd { get; set; }
        public decimal qcsl { get; set; }
        public decimal qcjh { get; set; }
        public decimal qcpf { get; set; }
        public decimal qcls { get; set; }
        public decimal rksl { get; set; }
        public decimal rkjh { get; set; }
        public decimal rkpf { get; set; }
        public decimal rkls { get; set; }
        public decimal cksl { get; set; }
        public decimal ckjh { get; set; }
        public decimal ckpf { get; set; }
        public decimal ckls { get; set; }
        public decimal tjsl { get; set; }
        public decimal tjpf { get; set; }
        public decimal tjls { get; set; }
        public decimal qmsl { get; set; }
        public decimal qmjh { get; set; }
        public decimal qmpf { get; set; }
        public decimal qmls { get; set; }
        public Nullable<decimal> JGID { get; set; }
    }
}
