//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_bqyz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zj_bqyz()
        {
            this.zj_bqyz2 = new HashSet<zj_bqyz2>();
        }
    
        public string sbh { get; set; }
        public int fjh { get; set; }
        public string pb { get; set; }
        public string qyr { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zj_bqyz2> zj_bqyz2 { get; set; }
    }
}
