//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_szjy
    {
        public decimal jldh { get; set; }
        public string jyxm { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public Nullable<decimal> xlh { get; set; }
        public Nullable<System.DateTime> xmsj { get; set; }
        public Nullable<decimal> jlys { get; set; }
        public Nullable<decimal> dsts { get; set; }
        public string jjh { get; set; }
        public string xsl { get; set; }
        public Nullable<decimal> ygjh { get; set; }
        public Nullable<decimal> hgjh { get; set; }
        public Nullable<decimal> zls { get; set; }
        public string jyjg { get; set; }
        public string jyr { get; set; }
        public string fjy { get; set; }
    }
}
