//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_xjjy
    {
        public string sbh { get; set; }
        public int fjh { get; set; }
        public int xlh { get; set; }
        public string bcbz { get; set; }
        public Nullable<decimal> ypbh { get; set; }
        public string ypmc { get; set; }
        public string ypgg { get; set; }
        public string ypph { get; set; }
        public Nullable<System.DateTime> jyrq { get; set; }
        public Nullable<System.DateTime> bgrq { get; set; }
        public string kcry { get; set; }
        public string ph1 { get; set; }
        public string gg1 { get; set; }
        public string cj { get; set; }
        public string bzxs { get; set; }
        public string gsxs { get; set; }
        public Nullable<decimal> ygsy { get; set; }
        public string ygbw { get; set; }
        public string yggc { get; set; }
        public string ygjl { get; set; }
        public Nullable<decimal> ggsy1 { get; set; }
        public string ggbw { get; set; }
        public string gggc1 { get; set; }
        public string ggjl { get; set; }
        public Nullable<decimal> ggsy2 { get; set; }
        public string ggbw2 { get; set; }
        public string jg { get; set; }
        public string jyr { get; set; }
        public string fjr { get; set; }
    }
}
