//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_yfmx
    {
        public string zjph { get; set; }
        public int fjh { get; set; }
        public int xlh { get; set; }
        public decimal jydh { get; set; }
        public Nullable<int> wzlx { get; set; }
        public string ypmc { get; set; }
        public Nullable<decimal> ypbh { get; set; }
        public string ypgg { get; set; }
        public string ypdw { get; set; }
        public Nullable<decimal> ypcd { get; set; }
        public Nullable<decimal> ypsl { get; set; }
        public Nullable<decimal> hgsl { get; set; }
    
        public virtual zj_yfqy zj_yfqy { get; set; }
    }
}
