//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_zjzc
    {
        public decimal zcbh { get; set; }
        public Nullable<decimal> ypxh { get; set; }
        public string ypmc { get; set; }
        public string ypph { get; set; }
        public Nullable<decimal> ypsx { get; set; }
        public string ypbz { get; set; }
        public string ypbqsm { get; set; }
        public Nullable<decimal> ypjg { get; set; }
        public string ypgg { get; set; }
        public Nullable<decimal> ypsl { get; set; }
        public string bz { get; set; }
        public string zcr { get; set; }
        public Nullable<System.DateTime> zcsj { get; set; }
    }
}
