//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_zyzj
    {
        public string sbh { get; set; }
        public string qlgh { get; set; }
        public string fhgh { get; set; }
        public Nullable<System.DateTime> tlrq { get; set; }
        public Nullable<decimal> ycsl { get; set; }
        public string sxcl { get; set; }
        public Nullable<System.DateTime> fsrq { get; set; }
        public Nullable<decimal> fshs { get; set; }
        public string czgh { get; set; }
        public Nullable<System.DateTime> zjrq { get; set; }
        public string yffj { get; set; }
        public string fsgh { get; set; }
        public Nullable<System.DateTime> bzrq { get; set; }
        public string bzcl { get; set; }
        public Nullable<decimal> zjsl { get; set; }
        public string bzgh { get; set; }
        public string zjgh { get; set; }
    }
}
