//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zj_zjhsxm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zj_zjhsxm()
        {
            this.zj_zjhsmx = new HashSet<zj_zjhsmx>();
        }
    
        public decimal xmxh { get; set; }
        public string xmmc { get; set; }
        public string jsgs { get; set; }
        public Nullable<decimal> xmbz { get; set; }
        public Nullable<decimal> clz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zj_zjhsmx> zj_zjhsmx { get; set; }
    }
}
