//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zy_dbxm
    {
        public decimal brxz { get; set; }
        public decimal xmxh { get; set; }
        public string xmmc { get; set; }
        public string xmdw { get; set; }
        public string bz1 { get; set; }
        public string bz2 { get; set; }
        public string bz3 { get; set; }
        public string bz4 { get; set; }
    }
}
