//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndModel
{
    using System;
    using System.Collections.Generic;
    
    public  class zy_yybr
    {
        public decimal sbxh { get; set; }
        public string bahm { get; set; }
        public string mzhm { get; set; }
        public decimal brxz { get; set; }
        public string gfzh { get; set; }
        public string brxm { get; set; }
        public decimal brxb { get; set; }
        public Nullable<System.DateTime> csny { get; set; }
        public string sfzh { get; set; }
        public Nullable<decimal> hyzk { get; set; }
        public Nullable<decimal> zydm { get; set; }
        public Nullable<decimal> sfdm { get; set; }
        public Nullable<decimal> jgdm { get; set; }
        public Nullable<decimal> mzdm { get; set; }
        public Nullable<decimal> gjdm { get; set; }
        public Nullable<decimal> dwbh { get; set; }
        public string gzdw { get; set; }
        public string dwdh { get; set; }
        public string dwyb { get; set; }
        public string hkdz { get; set; }
        public string hkyb { get; set; }
        public string lxrm { get; set; }
        public Nullable<decimal> lxgx { get; set; }
        public string lxdz { get; set; }
        public string lxdh { get; set; }
        public string pzhm { get; set; }
        public string sbhm { get; set; }
        public string dbrm { get; set; }
        public Nullable<decimal> dbgx { get; set; }
        public Nullable<decimal> zztx { get; set; }
        public Nullable<decimal> dbbz { get; set; }
        public decimal yyks { get; set; }
        public System.DateTime yyrq { get; set; }
        public Nullable<System.DateTime> ryrq { get; set; }
        public System.DateTime djrq { get; set; }
        public decimal jgbz { get; set; }
        public string czgh { get; set; }
        public string jtdh { get; set; }
        public Nullable<decimal> JGID { get; set; }
        public string HKDZ_QTDZ { get; set; }
        public string XZZ_QTDZ { get; set; }
        public string XZZ_DH { get; set; }
        public string XZZ_YB { get; set; }
        public Nullable<decimal> ZYH { get; set; }
        public Nullable<decimal> FZXH { get; set; }
        public Nullable<decimal> JZXH { get; set; }
        public Nullable<decimal> BSLZT { get; set; }
        public Nullable<decimal> BRTZ { get; set; }
        public Nullable<decimal> BRSG { get; set; }
        public Nullable<decimal> HKDZ_X { get; set; }
        public Nullable<decimal> HKDZ_S { get; set; }
        public Nullable<decimal> HKDZ_SQS { get; set; }
        public Nullable<decimal> XZZ_X { get; set; }
        public Nullable<decimal> XZZ_S { get; set; }
        public Nullable<decimal> XZZ_SQS { get; set; }
        public Nullable<decimal> JGDM_S { get; set; }
        public Nullable<decimal> JGDM_SQS { get; set; }
        public Nullable<decimal> CSD_X { get; set; }
        public Nullable<decimal> CSD_S { get; set; }
        public Nullable<decimal> CSD_SQS { get; set; }
        public Nullable<decimal> BRID { get; set; }
    }
}
